-- KAN-7: Total number of schemas in SNOWFLAKE_SAMPLE_DATA (excluding INFORMATION_SCHEMA)

SELECT COUNT(DISTINCT table_schema) as total_schemas
FROM SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.TABLES
WHERE table_schema <> 'INFORMATION_SCHEMA';
