-- Analysis of SIMM Placement for Delinquent Loans
-- Delinquent loans are defined as: 3-119 DPD and not charged off or paid in full

WITH simm_placements AS (
    SELECT 
        PAYOFFUID,
        MIN(LOAN_TAPE_ASOFDATE) as FIRST_SIMM_DATE
    FROM BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST
    WHERE SET_NAME = 'SIMM'
        AND SUPPRESSION_FLAG = FALSE
    GROUP BY PAYOFFUID
),
delinquent_loans AS (
    SELECT 
        rr.ASOFDATE,
        rr.PAYOFFUID,
        rr.CURRENT_DPD,
        rr.CURRENT_STATUS,
        rr.ROLL_STATUS,
        rr.REMAINING_PRINCIPAL,
        CASE 
            WHEN s.PAYOFFUID IS NOT NULL 
                AND rr.ASOFDATE >= s.FIRST_SIMM_DATE 
            THEN 1 
            ELSE 0 
        END AS SIMM_PLACEMENT_FLAG,
        s.FIRST_SIMM_DATE
    FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION rr
    LEFT JOIN simm_placements s ON rr.PAYOFFUID = s.PAYOFFUID
    WHERE rr.CURRENT_DPD BETWEEN 3 AND 119
        AND rr.CURRENT_STATUS NOT IN ('CHARGED_OFF', 'PAID_IN_FULL')
        AND rr.ASOFDATE >= '2025-05-01'
)

-- Summary by date
SELECT 
    ASOFDATE,
    COUNT(DISTINCT PAYOFFUID) as TOTAL_DELINQUENT_LOANS,
    COUNT(DISTINCT CASE WHEN SIMM_PLACEMENT_FLAG = 1 THEN PAYOFFUID END) as SIMM_PLACED_DELINQUENT,
    ROUND(COUNT(DISTINCT CASE WHEN SIMM_PLACEMENT_FLAG = 1 THEN PAYOFFUID END) * 100.0 / 
          COUNT(DISTINCT PAYOFFUID), 2) as SIMM_DELINQUENT_PCT,
    
    -- DPD buckets for delinquent loans
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 3 AND 30 THEN PAYOFFUID END) as DPD_3_30,
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 3 AND 30 AND SIMM_PLACEMENT_FLAG = 1 THEN PAYOFFUID END) as DPD_3_30_SIMM,
    
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 31 AND 60 THEN PAYOFFUID END) as DPD_31_60,
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 31 AND 60 AND SIMM_PLACEMENT_FLAG = 1 THEN PAYOFFUID END) as DPD_31_60_SIMM,
    
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 61 AND 90 THEN PAYOFFUID END) as DPD_61_90,
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 61 AND 90 AND SIMM_PLACEMENT_FLAG = 1 THEN PAYOFFUID END) as DPD_61_90_SIMM,
    
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 91 AND 119 THEN PAYOFFUID END) as DPD_91_119,
    COUNT(DISTINCT CASE WHEN CURRENT_DPD BETWEEN 91 AND 119 AND SIMM_PLACEMENT_FLAG = 1 THEN PAYOFFUID END) as DPD_91_119_SIMM,
    
    -- Principal at risk
    ROUND(SUM(CASE WHEN SIMM_PLACEMENT_FLAG = 1 THEN REMAINING_PRINCIPAL END), 2) as SIMM_PRINCIPAL_AT_RISK,
    ROUND(SUM(REMAINING_PRINCIPAL), 2) as TOTAL_PRINCIPAL_AT_RISK

FROM delinquent_loans
GROUP BY ASOFDATE
ORDER BY ASOFDATE DESC
LIMIT 10;