-- Validation Query for SIMM Flag Implementation
-- This query validates the SIMM flag implementation by showing summary statistics

WITH simm_flagged_data AS (
    SELECT 
        rr.ASOFDATE,
        rr.PAYOFFUID,
        rr.DPD,
        rr.STATUSCURRENT,
        rr.PORTFOLIONAME,
        CASE 
            WHEN s.PAYOFFUID IS NOT NULL 
                AND rr.ASOFDATE >= s.FIRST_SIMM_DATE 
            THEN 1 
            ELSE 0 
        END AS SIMM_PLACEMENT_FLAG
    FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION rr
    LEFT JOIN (
        SELECT 
            PAYOFFUID,
            MIN(LOAN_TAPE_ASOFDATE) as FIRST_SIMM_DATE
        FROM BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST
        WHERE SET_NAME = 'SIMM'
            AND SUPPRESSION_FLAG = FALSE
        GROUP BY PAYOFFUID
    ) s ON rr.PAYOFFUID = s.PAYOFFUID
    WHERE rr.ASOFDATE >= '2025-05-01'  -- Recent months only
)

-- Summary statistics
SELECT 
    ASOFDATE,
    COUNT(*) as TOTAL_LOANS,
    SUM(SIMM_PLACEMENT_FLAG) as SIMM_PLACED_LOANS,
    ROUND(SUM(SIMM_PLACEMENT_FLAG) * 100.0 / COUNT(*), 2) as SIMM_PCT,
    
    -- DPD breakdown for SIMM vs non-SIMM
    ROUND(AVG(CASE WHEN SIMM_PLACEMENT_FLAG = 1 THEN DPD END), 1) as AVG_DPD_SIMM,
    ROUND(AVG(CASE WHEN SIMM_PLACEMENT_FLAG = 0 THEN DPD END), 1) as AVG_DPD_NON_SIMM,
    
    -- Status breakdown
    COUNT(CASE WHEN SIMM_PLACEMENT_FLAG = 1 AND STATUSCURRENT = 'CHARGED_OFF' THEN 1 END) as SIMM_CHARGED_OFF,
    COUNT(CASE WHEN SIMM_PLACEMENT_FLAG = 0 AND STATUSCURRENT = 'CHARGED_OFF' THEN 1 END) as NON_SIMM_CHARGED_OFF
    
FROM simm_flagged_data
GROUP BY ASOFDATE
ORDER BY ASOFDATE DESC;