/* AUDIENCE LIST FOR CUSTOMER REFERRAL EMAIL CAMPAIGN - 9/30/2025
 *
 * Business Requirements:
 * - All current customers in good standing
 * - Active loans (not closed, not charged off)
 * - Less than 3 days past due
 *
 * Exclusions:
 * - Cease and desists
 * - Email suppression flags
 *
 * Output Fields:
 * - Email, LOS Customer ID, LMS Customer ID, PayoffUID
 * - LP Loan Status, Application ID, First Name, Last Name, State
 *
 * Note: SFMC opt-outs CTE removed as it was causing performance issues
 * and currently filters 0 records. SFMC will handle unsubscribe scrubbing.
 */

SELECT DISTINCT
    C.EMAIL,
    E.CUSTOMER_ID AS LOS_CUSTOMER_ID,
    A.MEMBER_ID AS LMS_CUSTOMER_ID,
    A.LEAD_GUID AS PAYOFFUID,
    B.LOAN_SUB_STATUS_TEXT AS LP_LOAN_STATUS,
    A.APPLICATION_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.STATE
FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN A
INNER JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_STATUS_ARCHIVE_CURRENT B
    ON A.LOAN_ID::VARCHAR = B.LOAN_ID::VARCHAR
    AND B.DATE = CURRENT_DATE
    AND B.DAYS_PAST_DUE < 3
INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII C
    ON A.MEMBER_ID = C.MEMBER_ID
    AND C.MEMBER_PII_END_DATE IS NULL
INNER JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_CUSTOMER_CURRENT E
    ON A.APPLICATION_ID::VARCHAR = E.LOAN_ID::VARCHAR
    AND E.SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LOS_SCHEMA()
INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_CONTACT_RULES F
    ON A.LOAN_ID::VARCHAR = F.LOAN_ID::VARCHAR
    AND F.CEASE_AND_DESIST = FALSE
    AND F.SUPPRESS_EMAIL = FALSE
WHERE 1=1
    AND A.LOAN_CLOSED_DATE IS NULL
    AND A.CHARGE_OFF_DATE IS NULL;