DROP view BUSINESS_INTELLIGENCE.BRIDGE.VW_APPL_HISTORY;

create or replace view BUSINESS_INTELLIGENCE.ANALYTICS.VW_APPL_HISTORY COPY GRANTS as
WITH LOANPRO_APPL_HISTORY AS (select record_id,
    app_id,
    NOTE_TITLE_DETAIL,
    NOTE_OLD_VALUE_LABEL,
    NOTE_NEW_VALUE_LABEL,
    CREATED_TS,
    CASE WHEN deleted = 0 THEN false ELSE true END as DELETED,
    'LOANPRO' as SOURCE,
ROW_NUMBER() OVER ( PARTITION BY APP_ID, NOTE_OLD_VALUE_LABEL, NOTE_NEW_VALUE_LABEL ORDER BY RECORD_ID ) as rnk,
LAG(NOTE_OLD_VALUE_LABEL) OVER (PARTITION BY APP_ID ORDER BY RECORD_ID) AS REPEAT_OLD_STATUS,
(rnk > 1 AND REPEAT_OLD_STATUS = NOTE_OLD_VALUE_LABEL) AS REPEAT_REMOVAL_IND
from BUSINESS_INTELLIGENCE.BRIDGE.LOANPRO_APP_SYSTEM_NOTES
WHERE 1=1
AND IFNULL(NOTE_OLD_VALUE_LABEL,'') <> IFNULL(NOTE_NEW_VALUE_LABEL,'')
AND NOTE_TITLE_DETAIL NOT IN ('Apply Default Field Map','Loan Sub Status', 'Loan Status - Loan Sub Status','Portfolios Removed','Portfolios Added'))
SELECT record_id,
    app_id,
    NOTE_TITLE_DETAIL,
    NOTE_OLD_VALUE_LABEL,
    NOTE_NEW_VALUE_LABEL,
    CREATED_TS,
    DELETED,
    SOURCE
FROM LOANPRO_APPL_HISTORY
WHERE REPEAT_REMOVAL_IND = FALSE
UNION ALL
select
    ID AS record_id,
    application_id::String AS app_id,
    FIELD as NOTE_TITLE_DETAIL,
    OLDVALUE as NOTE_OLD_VALUE_LABEL,
    NEWVALUE as NOTE_NEW_VALUE_LABEL,
    CREATEDDATE_PST as CREATED_TS,
    ISDELETED as DELETED,
    'CLS' as SOURCE
from BUSINESS_INTELLIGENCE.BRIDGE.VW_CLS_APPL_HISTORY;