-- Top 10 CO2 Emitting Countries in 2024
-- Source: Our World in Data (OWID) CO2 Dataset
-- Table: ANALYTICS.DEVELOPMENT.CO2_EMISSIONS

SELECT
    COUNTRY,
    YEAR,
    ROUND(CO2, 2) AS CO2_MILLION_TONNES,
    ROUND(CO2_PER_CAPITA, 2) AS CO2_PER_CAPITA,
    ROUND(SHARE_GLOBAL_CO2, 2) AS SHARE_GLOBAL_PCT
FROM ANALYTICS.DEVELOPMENT.CO2_EMISSIONS
WHERE YEAR = 2024
  AND ISO_CODE IS NOT NULL
  AND ISO_CODE NOT IN ('OWID_WRL', 'OWID_INT')  -- Exclude world/international aggregates
  AND CO2 IS NOT NULL
ORDER BY CO2 DESC
LIMIT 10;
