-- US CO2 Emissions Trend (2000-2024)
-- Source: Our World in Data (OWID) CO2 Dataset
-- Table: ANALYTICS.DEVELOPMENT.CO2_EMISSIONS

SELECT
    YEAR,
    ROUND(CO2, 2) AS CO2_MILLION_TONNES,
    ROUND(CO2_PER_CAPITA, 2) AS CO2_PER_CAPITA,
    ROUND(CO2_GROWTH_PRCT, 2) AS YOY_GROWTH_PCT,
    ROUND(SHARE_GLOBAL_CO2, 2) AS SHARE_GLOBAL_PCT
FROM ANALYTICS.DEVELOPMENT.CO2_EMISSIONS
WHERE COUNTRY = 'United States'
  AND YEAR >= 2000
ORDER BY YEAR;
