/*
DI-1262: LOAN_DEBT_SETTLEMENT Data Object Creation
Independent Data Exploration and Validation

CRITICAL: This analysis validates PRP findings before implementation
*/

-- ============================================
-- INDEPENDENT DATA VALIDATION
-- ============================================

-- 1. VALIDATE SOURCE COUNTS (Match PRP expectations)
SELECT 'Custom Field Loans' as source_type, COUNT(*) as loan_count
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
WHERE (SETTLEMENTSTATUS IS NOT NULL AND SETTLEMENTSTATUS <> '')
   OR (SETTLEMENT_AMOUNT IS NOT NULL AND SETTLEMENT_AMOUNT > 0)
   OR (DEBT_SETTLEMENT_COMPANY IS NOT NULL AND DEBT_SETTLEMENT_COMPANY <> '')

UNION ALL

SELECT 'Portfolio Loans' as source_type, COUNT(DISTINCT LOAN_ID) as loan_count
FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_PORTFOLIOS_AND_SUB_PORTFOLIOS
WHERE PORTFOLIO_CATEGORY = 'Settlement'

UNION ALL

SELECT 'Sub Status Loans' as source_type, COUNT(DISTINCT LOAN_ID) as loan_count
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_STATUS_ARCHIVE_CURRENT
WHERE LOAN_SUB_STATUS_TEXT = 'Closed - Settled in Full'
  AND SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LMS_SCHEMA();

-- 2. ESTIMATE TOTAL UNION POPULATION
WITH all_settlement_loans AS (
    SELECT LOAN_ID FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
    WHERE (SETTLEMENTSTATUS IS NOT NULL AND SETTLEMENTSTATUS <> '')
       OR (SETTLEMENT_AMOUNT IS NOT NULL AND SETTLEMENT_AMOUNT > 0)
       OR (DEBT_SETTLEMENT_COMPANY IS NOT NULL AND DEBT_SETTLEMENT_COMPANY <> '')

    UNION

    SELECT DISTINCT LOAN_ID FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_PORTFOLIOS_AND_SUB_PORTFOLIOS
    WHERE PORTFOLIO_CATEGORY = 'Settlement'

    UNION

    SELECT DISTINCT LOAN_ID FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_STATUS_ARCHIVE_CURRENT
    WHERE LOAN_SUB_STATUS_TEXT = 'Closed - Settled in Full'
      AND SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LMS_SCHEMA()
)
SELECT 'Total Union Population' as metric, COUNT(*) as value FROM all_settlement_loans;

-- 3. VALIDATE SETTLEMENT FIELD POPULATION RATES
SELECT
    'SETTLEMENTSTATUS' as field_name,
    COUNT(*) as total_records,
    COUNT(SETTLEMENTSTATUS) as non_null_count,
    ROUND((COUNT(SETTLEMENTSTATUS) * 100.0) / COUNT(*), 2) as population_pct
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_AMOUNT' as field_name,
    COUNT(*) as total_records,
    COUNT(SETTLEMENT_AMOUNT) as non_null_count,
    ROUND((COUNT(SETTLEMENT_AMOUNT) * 100.0) / COUNT(*), 2) as population_pct
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'DEBT_SETTLEMENT_COMPANY' as field_name,
    COUNT(*) as total_records,
    COUNT(DEBT_SETTLEMENT_COMPANY) as non_null_count,
    ROUND((COUNT(DEBT_SETTLEMENT_COMPANY) * 100.0) / COUNT(*), 2) as population_pct
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

ORDER BY population_pct DESC;