/*
DI-1262: Settlement Field Analysis
Identify which settlement fields to include/exclude based on NULL prevalence
*/

-- Check all settlement-related fields for population rates
SELECT
    'SETTLEMENTSTATUS' as field_name,
    COUNT(*) as total_records,
    COUNT(SETTLEMENTSTATUS) as non_null_count,
    ROUND((COUNT(SETTLEMENTSTATUS) * 100.0) / COUNT(*), 2) as population_pct
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_AMOUNT',
    COUNT(*), COUNT(SETTLEMENT_AMOUNT),
    ROUND((COUNT(SETTLEMENT_AMOUNT) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_AMOUNT_PAID',
    COUNT(*), COUNT(SETTLEMENT_AMOUNT_PAID),
    ROUND((COUNT(SETTLEMENT_AMOUNT_PAID) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_AGREEMENT_AMOUNT_DCA',
    COUNT(*), COUNT(SETTLEMENT_AGREEMENT_AMOUNT_DCA),
    ROUND((COUNT(SETTLEMENT_AGREEMENT_AMOUNT_DCA) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENTCOMPANY',
    COUNT(*), COUNT(SETTLEMENTCOMPANY),
    ROUND((COUNT(SETTLEMENTCOMPANY) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_COMPANY_DCA',
    COUNT(*), COUNT(SETTLEMENT_COMPANY_DCA),
    ROUND((COUNT(SETTLEMENT_COMPANY_DCA) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_ACCEPTED_DATE',
    COUNT(*), COUNT(SETTLEMENT_ACCEPTED_DATE),
    ROUND((COUNT(SETTLEMENT_ACCEPTED_DATE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_SETUP_DATE',
    COUNT(*), COUNT(SETTLEMENT_SETUP_DATE),
    ROUND((COUNT(SETTLEMENT_SETUP_DATE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENT_END_DATE',
    COUNT(*), COUNT(SETTLEMENT_END_DATE),
    ROUND((COUNT(SETTLEMENT_END_DATE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENTAGREEMENTAMOUNT',
    COUNT(*), COUNT(SETTLEMENTAGREEMENTAMOUNT),
    ROUND((COUNT(SETTLEMENTAGREEMENTAMOUNT) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENTCOMPLETIONDATE',
    COUNT(*), COUNT(SETTLEMENTCOMPLETIONDATE),
    ROUND((COUNT(SETTLEMENTCOMPLETIONDATE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENTCOMPLETIONPERCENTAGE',
    COUNT(*), COUNT(SETTLEMENTCOMPLETIONPERCENTAGE),
    ROUND((COUNT(SETTLEMENTCOMPLETIONPERCENTAGE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'SETTLEMENTSTARTDATE',
    COUNT(*), COUNT(SETTLEMENTSTARTDATE),
    ROUND((COUNT(SETTLEMENTSTARTDATE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'UNPAID_SETTLEMENT_BALANCE',
    COUNT(*), COUNT(UNPAID_SETTLEMENT_BALANCE),
    ROUND((COUNT(UNPAID_SETTLEMENT_BALANCE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'DEBT_SETTLEMENT_COMPANY',
    COUNT(*), COUNT(DEBT_SETTLEMENT_COMPANY),
    ROUND((COUNT(DEBT_SETTLEMENT_COMPANY) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'DEBTSETTLEMENTPAYMENTTERMS',
    COUNT(*), COUNT(DEBTSETTLEMENTPAYMENTTERMS),
    ROUND((COUNT(DEBTSETTLEMENTPAYMENTTERMS) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT',
    COUNT(*), COUNT(PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT),
    ROUND((COUNT(PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'TOTAL_PAID_AT_TIME_OF_SETTLEMENT',
    COUNT(*), COUNT(TOTAL_PAID_AT_TIME_OF_SETTLEMENT),
    ROUND((COUNT(TOTAL_PAID_AT_TIME_OF_SETTLEMENT) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'AMOUNT_FORGIVEN',
    COUNT(*), COUNT(AMOUNT_FORGIVEN),
    ROUND((COUNT(AMOUNT_FORGIVEN) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'EXPECTEDSETTLEMENTENDDATE',
    COUNT(*), COUNT(EXPECTEDSETTLEMENTENDDATE),
    ROUND((COUNT(EXPECTEDSETTLEMENTENDDATE) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

UNION ALL

SELECT
    'THIRD_PARTY_COLLECTION_AGENCY',
    COUNT(*), COUNT(THIRD_PARTY_COLLECTION_AGENCY),
    ROUND((COUNT(THIRD_PARTY_COLLECTION_AGENCY) * 100.0) / COUNT(*), 2)
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

ORDER BY population_pct DESC;