-- DI-974: Create Snowflake Task to Refresh Dynamic Table Daily at 7am ET
-- This task will refresh the DSH_GR_DAILY_ROLL_TRANSITION dynamic table every morning

-- First, set the dynamic table to downstream refresh mode
ALTER DYNAMIC TABLE BUSINESS_INTELLIGENCE.REPORTING.DSH_GR_DAILY_ROLL_TRANSITION 
SET REFRESH_MODE = DOWNSTREAM;

CREATE OR REPLACE TASK BUSINESS_INTELLIGENCE.REPORTING.TASK_REFRESH_DSH_GR_DAILY_ROLL_TRANSITION
  WAREHOUSE = BUSINESS_INTELLIGENCE
  SCHEDULE = 'USING CRON 0 7 * * * America/New_York'  -- 7:00 AM ET daily
  COMMENT = 'DI-974: Daily refresh of DSH_GR_DAILY_ROLL_TRANSITION dynamic table with SIMM flags at 7am ET'
AS
  ALTER DYNAMIC TABLE BUSINESS_INTELLIGENCE.REPORTING.DSH_GR_DAILY_ROLL_TRANSITION REFRESH;

-- Enable the task
ALTER TASK BUSINESS_INTELLIGENCE.REPORTING.TASK_REFRESH_DSH_GR_DAILY_ROLL_TRANSITION RESUME;

-- Verify task creation
SHOW TASKS LIKE 'TASK_REFRESH_DSH_GR_DAILY_ROLL_TRANSITION' IN SCHEMA BUSINESS_INTELLIGENCE.REPORTING;