-- DI-1137: Massachusetts Regulator Request
-- Query 1: Loans of $6,000 or less with rates above 12% per annum for MA residents
-- Purpose: Identify if Happy Money has processed applications or arranged such loans

-- Set parameters for easy modification
SET MAX_LOAN_AMOUNT = 6000;
SET MIN_INTEREST_RATE = 12.0;  -- 12% per annum
SET STATE_FILTER = 'MA';

-- Main query for small dollar high rate loans
WITH MA_SMALL_HIGH_RATE_LOANS AS (
    SELECT 
        -- Application Information
        B.APPLICATION_ID,
        B.APPLICATION_STARTED_DATE AS APPLICATION_DATE,
        
        -- Member Information
        C.FIRST_NAME AS APPLICATION_FIRST_NAME,
        C.LAST_NAME AS APPLICATION_LAST_NAME,
        A.APPLICANT_RESIDENCE_STATE AS APPLICANTRESIDENCESTATE,
        
        -- Loan Information
        A.LOAN_ID AS LOANID,
        A.LEGACY_LOAN_ID,
        A.LOAN_AMOUNT AS LOANAMOUNT,
        
        -- Status Information
        E.TITLE AS CURRENT_STATUS, -- Will need to determine proper status source
        
        -- Rate Information
        B.APR,
        B.INTEREST_RATE,
        
        -- Date Information
        A.ORIGINATION_DATE AS ORIGINATION_DATE
        
    FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN A
    
    -- Join with application data for APR and interest rate
    INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_APPLICATION B
        ON A.APPLICATION_ID = B.APPLICATION_ID
    
    -- Join with member PII for names
    LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII C
        ON A.MEMBER_ID::STRING = C.MEMBER_ID::STRING
        AND C.MEMBER_PII_END_DATE IS NULL
    LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_SETTINGS_ENTITY_CURRENT D
        ON A.LOAN_ID::STRING = D.LOAN_ID::STRING
        AND D.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA()
    LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_SUB_STATUS_ENTITY_CURRENT E
        ON D.LOAN_SUB_STATUS_ID = E.ID
    
    WHERE 
        -- Massachusetts residents only
        UPPER(A.APPLICANT_RESIDENCE_STATE) = $STATE_FILTER
        -- Loan amount $6,000 or less
        AND A.LOAN_AMOUNT <= $MAX_LOAN_AMOUNT
        -- Interest rate above 12% per annum
        AND B.INTEREST_RATE > $MIN_INTEREST_RATE
)

-- Final output (get most recent status per loan)
SELECT DISTINCT
    APPLICATION_DATE,
    APPLICATION_FIRST_NAME,
    APPLICATION_LAST_NAME,
    APPLICANTRESIDENCESTATE,
    LOANID,
    LOANAMOUNT,
    FIRST_VALUE(CURRENT_STATUS) OVER (PARTITION BY LOANID ORDER BY LOANID) AS CURRENT_STATUS,
    APR,
    INTEREST_RATE,
    ORIGINATION_DATE
FROM MA_SMALL_HIGH_RATE_LOANS
ORDER BY ORIGINATION_DATE DESC;

-- Summary statistics
WITH MA_SMALL_HIGH_RATE_LOANS_SUMMARY AS (
    SELECT 
        A.LOAN_ID AS LOANID,
        A.LOAN_AMOUNT AS LOANAMOUNT,
        A.ORIGINATION_DATE,
        B.INTEREST_RATE,
        B.APR
    FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN A
    INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_APPLICATION B
        ON A.APPLICATION_ID = B.APPLICATION_ID
    WHERE 
        UPPER(A.APPLICANT_RESIDENCE_STATE) = $STATE_FILTER
        AND A.LOAN_AMOUNT <= $MAX_LOAN_AMOUNT
        AND B.INTEREST_RATE > $MIN_INTEREST_RATE
)
SELECT 
    'MA Loans ≤$6K with Rate >12%' AS QUERY_TYPE,
    COUNT(DISTINCT LOANID) AS TOTAL_LOANS,
    SUM(LOANAMOUNT) AS TOTAL_LOAN_AMOUNT,
    MIN(ORIGINATION_DATE) AS EARLIEST_LOAN,
    MAX(ORIGINATION_DATE) AS LATEST_LOAN,
    ROUND(AVG(INTEREST_RATE), 2) AS AVG_INTEREST_RATE,
    ROUND(AVG(APR), 2) AS AVG_APR
FROM MA_SMALL_HIGH_RATE_LOANS_SUMMARY;