-- DI-1137: Massachusetts Regulator Request (MVW_LOAN_TAPE VERSION)
-- Query 1: Loans of $6,000 or less with rates above 12% per annum for MA residents
-- Purpose: Identify if Happy Money has processed applications or arranged such loans
-- Data Source: BUSINESS_INTELLIGENCE.DATA_STORE.MVW_LOAN_TAPE

-- Set parameters for easy modification
SET MAX_LOAN_AMOUNT = 6000;
SET MIN_INTEREST_RATE = 12.0;  -- 12% per annum (as decimal 0.12)
SET STATE_FILTER = 'MA';

-- Main query for small dollar high rate loans using main loan tape
WITH MA_LOAN_TAPE_CURRENT AS (
    -- Get most recent loan tape record for each loan
    SELECT 
        LOANID,
        PAYOFFUID,
        APPLICANTRESIDENCESTATE,
        LOANAMOUNT,
        INTERESTRATE,
        APR,
        ORIGINATIONDATE,
        STATUS,
        PORTFOLIONAME,
        PLACEMENT_STATUS,
        -- Use most recent record for each loan
        ROW_NUMBER() OVER (PARTITION BY LOANID ORDER BY ASOFDATE DESC) as rn
    FROM BUSINESS_INTELLIGENCE.DATA_STORE.MVW_LOAN_TAPE
    WHERE UPPER(APPLICANTRESIDENCESTATE) = $STATE_FILTER
),

MA_SMALL_HIGH_RATE_LOANS AS (
    SELECT 
        -- Loan Information
        LT.LOANID,
        LT.LOANAMOUNT,
        LT.INTERESTRATE,
        LT.APR,
        LT.ORIGINATIONDATE,
        LT.STATUS AS CURRENT_STATUS,
        
        -- Additional context
        LT.PORTFOLIONAME,
        LT.APPLICANTRESIDENCESTATE,
        
        -- Attempt to get application date from VW_LOAN (if available)
        VL.APPLICATION_ID,
        VA.APPLICATION_STARTED_DATE AS APPLICATION_DATE,
        
        -- Attempt to get member names (if available)
        MP.FIRST_NAME AS APPLICATION_FIRST_NAME,
        MP.LAST_NAME AS APPLICATION_LAST_NAME
        
    FROM MA_LOAN_TAPE_CURRENT LT
    
    -- LEFT JOIN to get application info if available
    LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN VL
        ON LT.LOANID = VL.LOAN_ID::VARCHAR
    LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_APPLICATION VA
        ON VL.APPLICATION_ID = VA.APPLICATION_ID
    LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII MP
        ON VL.MEMBER_ID::STRING = MP.MEMBER_ID::STRING
        AND MP.MEMBER_PII_END_DATE IS NULL
    
    WHERE 
        LT.rn = 1  -- Most recent record per loan
        -- Loan amount $6,000 or less
        AND LT.LOANAMOUNT <= $MAX_LOAN_AMOUNT
        -- Interest rate above 12% per annum (stored as decimal, so 0.12 = 12%)
        AND LT.INTERESTRATE > ($MIN_INTEREST_RATE / 100)
)

-- Final output with required regulatory fields
SELECT 
    COALESCE(APPLICATION_DATE, ORIGINATIONDATE) AS APPLICATION_DATE,
    COALESCE(APPLICATION_FIRST_NAME, 'DATA NOT AVAILABLE') AS APPLICATION_FIRST_NAME,
    COALESCE(APPLICATION_LAST_NAME, 'DATA NOT AVAILABLE') AS APPLICATION_LAST_NAME,
    APPLICANTRESIDENCESTATE,
    LOANID,
    LOANAMOUNT,
    CURRENT_STATUS,
    APR,
    INTERESTRATE,
    ORIGINATIONDATE
FROM MA_SMALL_HIGH_RATE_LOANS
ORDER BY ORIGINATIONDATE DESC;

-- Summary statistics for validation
WITH MA_LOAN_TAPE_CURRENT AS (
    SELECT 
        LOANID, LOANAMOUNT, ORIGINATIONDATE, INTERESTRATE, APR,
        ROW_NUMBER() OVER (PARTITION BY LOANID ORDER BY ASOFDATE DESC) as rn
    FROM BUSINESS_INTELLIGENCE.DATA_STORE.MVW_LOAN_TAPE
    WHERE UPPER(APPLICANTRESIDENCESTATE) = $STATE_FILTER
),
MA_SMALL_HIGH_RATE_SUMMARY AS (
    SELECT 
        LT.LOANID,
        LT.LOANAMOUNT,
        LT.ORIGINATIONDATE,
        LT.INTERESTRATE,
        LT.APR
    FROM MA_LOAN_TAPE_CURRENT LT
    WHERE 
        LT.rn = 1
        AND LT.LOANAMOUNT <= $MAX_LOAN_AMOUNT
        AND LT.INTERESTRATE > ($MIN_INTEREST_RATE / 100)
)
SELECT 
    'MA Loans ≤$6K with Rate >12% (MVW_LOAN_TAPE)' AS QUERY_TYPE,
    COUNT(DISTINCT LOANID) AS TOTAL_LOANS,
    SUM(LOANAMOUNT) AS TOTAL_LOAN_AMOUNT,
    MIN(ORIGINATIONDATE) AS EARLIEST_LOAN,
    MAX(ORIGINATIONDATE) AS LATEST_LOAN,
    ROUND(AVG(INTERESTRATE * 100), 2) AS AVG_INTEREST_RATE_PCT,
    ROUND(AVG(APR), 2) AS AVG_APR
FROM MA_SMALL_HIGH_RATE_SUMMARY;