-- DI-1099: Detailed Portfolio Breakdown QC
-- Shows exact portfolio distribution in the goodbye letter data

SELECT 
    A.PORTFOLIONAME,
    COUNT(*) as loan_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) as percentage,
    CASE 
        WHEN A.PORTFOLIONAME LIKE '%Theorem%' THEN 'THEOREM PORTFOLIO'
        ELSE 'NON-THEOREM PORTFOLIO'
    END as portfolio_classification
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.THEOREM_DEBT_SALE_Q1_2025_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
    ON LA.LEGACY_LOAN_ID = C.LOANID
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII ci
    ON ci.MEMBER_ID::VARCHAR = la.MEMBER_ID::VARCHAR 
    AND ci.MEMBER_PII_END_DATE IS NULL
LEFT JOIN business_intelligence.bridge.vw_los_custom_loan_settings_current los
    ON los.APPLICATION_GUID = la.LEAD_GUID
INNER JOIN business_intelligence.bridge.VW_LOAN_CUSTOMER_CURRENT cust
    ON los.loan_id = cust.loan_id 
    AND cust.SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LOS_SCHEMA()
INNER JOIN BUSINESS_INTELLIGENCE_DEV.CRON_STORE.THEOREM_DEBT_SALE_Q1_2025_SALE A
    ON C.LOANID = A.LOANID
GROUP BY A.PORTFOLIONAME
ORDER BY loan_count DESC;
