create or replace view BUSINESS_INTELLIGENCE.BRIDGE.VW_APPL_HISTORY(
	ID,
	APPLICATION_ID,
	NOTE_TITLE,
	NOTE_DATA,
	REFERENCE_TYPE,
	OPERATION_TYPE,
	OPERATION_SUB_TYPE,
	ROW_EVENT_TYPE,
	CREATE_USER,
	CREATE_USER_NAME,
	CREATED,
	LASTUPDATED,
	DELETED,
	IS_HARD_DELETED,
	BEFORE_VALUES,
	NEWVALUE,
	NEWVALUE_LABEL,
	OLDVALUE,
	OLDVALUE_LABEL,
	NOTE_TITLE_DETAIL
) as
        WITH FINAL AS (select *,
     ROW_NUMBER() OVER ( PARTITION BY APPLICATION_ID, OLDVALUE, NEWVALUE ORDER BY ID ) as rnk,
    LAG(OLDVALUE) OVER (PARTITION BY APPLICATION_ID ORDER BY ID) AS REPEAT_OLD_STATUS,
    (rnk > 1 AND REPEAT_OLD_STATUS = OLDVALUE) AS REPEAT_REMOVAL_IND
        from ARCA.FRESHSNOW.APPL_HISTORY
        WHERE 1=1
AND IFNULL(OLDVALUE,'') <> IFNULL(NEWVALUE,''))
SELECT * EXCLUDE (rnk, REPEAT_OLD_STATUS, REPEAT_REMOVAL_IND)
FROM FINAL
WHERE REPEAT_REMOVAL_IND = FALSE;


        CREATE OR REPLACE VIEW BUSINESS_INTELLIGENCE.ANALYTICS.VW_APPL_HISTORY COPY GRANTS AS
select
    ID AS application_history_id,
    application_id::String AS application_id,
    FIELD,
    OLDVALUE,
    NEWVALUE,
    CREATEDDATE_PST as created_datetime_utc,
    CREATEDBYID::string as created_by_user_id,
    ISDELETED as is_deleted,
    'CLS' as source
from BUSINESS_INTELLIGENCE.BRIDGE.VW_CLS_APPL_HISTORY
union ALL
select
    ID AS application_history_id,
    application_id::String as application_id,
    NOTE_TITLE_DETAIL as field,
    OLDVALUE_LABEL as old_value,
    NEWVALUE_LABEL as new_value,
    created as created_datetime_utc,
    create_user::string as created_by_user_id,
    CASE
        WHEN deleted = 0 THEN false
        ELSE true
    END as is_deleted,
    'LOANPRO' as SOURCE
    FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_APPL_HISTORY
WHERE UPPER(NOTE_TITLE_DETAIL) NOT IN ('LOAN SUB STATUS', 'LOAN STATUS - LOAN SUB STATUS');