-- DI-926: BRIDGE and ANALYTICS layers for LoanPro App System Notes
-- BRIDGE: Simple pass-through from FRESHSNOW
-- ANALYTICS: Business-ready data with analytical enhancements

-- BRIDGE Layer: Simple pass-through (following APPL_HISTORY pattern)
CREATE OR REPLACE VIEW BUSINESS_INTELLIGENCE.BRIDGE.VW_LOANPRO_APP_SYSTEM_NOTES(
    RECORD_ID,
    APP_ID,
    CREATED_TS,
    LASTUPDATED_TS,
    LOAN_STATUS_NEW,
    LOAN_STATUS_OLD,
    NOTE_NEW_VALUE,
    NOTE_NEW_VALUE_LABEL,
    NOTE_OLD_VALUE,
    NOTE_OLD_VALUE_LABEL,
    NOTE_TITLE_DETAIL,
    NOTE_TITLE,
    NOTE_DATA,
    DELETED,
    IS_HARD_DELETED,
    PORTFOLIOS_ADDED,
    PORTFOLIOS_ADDED_CATEGORY,
    PORTFOLIOS_ADDED_LABEL
) COPY GRANTS AS 
SELECT * FROM ARCA.FRESHSNOW.VW_LOANPRO_APP_SYSTEM_NOTES;

-- ANALYTICS Layer: Business-ready data with analytical enhancements
CREATE OR REPLACE VIEW BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOANPRO_APP_SYSTEM_NOTES(
    RECORD_ID,
    APP_ID,
    CREATED_TS,
    CREATED_DATE,
    LASTUPDATED_TS,
    LOAN_STATUS_NEW,
    LOAN_STATUS_OLD,
    LOAN_STATUS_CHANGED_FLAG,
    NOTE_NEW_VALUE,
    NOTE_NEW_VALUE_LABEL,
    NOTE_OLD_VALUE,
    NOTE_OLD_VALUE_LABEL,
    VALUE_CHANGED_FLAG,
    NOTE_TITLE_DETAIL,
    CHANGE_TYPE_CATEGORY,
    CREATED_HOUR,
    CREATED_DAY_OF_WEEK,
    CREATED_WEEK,
    CREATED_MONTH,
    IS_SUB_STATUS_CHANGE,
    IS_PORTFOLIO_CHANGE,
    IS_AGENT_CHANGE,
    IS_SOURCE_COMPANY_CHANGE,
    NOTE_TITLE,
    DELETED,
    IS_HARD_DELETED,
    PORTFOLIOS_ADDED,
    PORTFOLIOS_ADDED_CATEGORY,
    PORTFOLIOS_ADDED_LABEL
) COPY GRANTS AS 
SELECT
    RECORD_ID, 
    APP_ID, 
    CREATED_TS, 
    CREATED_TS::date as CREATED_DATE, 
    LASTUPDATED_TS,
    LOAN_STATUS_NEW, 
    LOAN_STATUS_OLD,
    case when LOAN_STATUS_NEW != LOAN_STATUS_OLD then 1 else 0 end as LOAN_STATUS_CHANGED_FLAG,
    NOTE_NEW_VALUE,
    NOTE_NEW_VALUE_LABEL, 
    NOTE_OLD_VALUE,
    NOTE_OLD_VALUE_LABEL,
    case when NOTE_NEW_VALUE is not null and NOTE_OLD_VALUE is not null 
         and NOTE_NEW_VALUE != NOTE_OLD_VALUE then 1 else 0 end as VALUE_CHANGED_FLAG,
    NOTE_TITLE_DETAIL,
    case when NOTE_TITLE_DETAIL like '%Status%' then 'Status Change'
         when NOTE_TITLE_DETAIL like '%Portfolio%' then 'Portfolio Management'
         when NOTE_TITLE_DETAIL = 'Agent' then 'Agent Assignment'
         when NOTE_TITLE_DETAIL = 'Source Company' then 'Source Management'
         else 'Other' end as CHANGE_TYPE_CATEGORY,
    EXTRACT(HOUR FROM CREATED_TS) as CREATED_HOUR,
    EXTRACT(DAYOFWEEK FROM CREATED_TS) as CREATED_DAY_OF_WEEK,
    DATE_TRUNC('week', CREATED_TS::date) as CREATED_WEEK,
    DATE_TRUNC('month', CREATED_TS::date) as CREATED_MONTH,
    case when NOTE_TITLE_DETAIL like '%Loan Sub Status%' then 1 else 0 end as IS_SUB_STATUS_CHANGE,
    case when NOTE_TITLE_DETAIL like '%Portfolio%' then 1 else 0 end as IS_PORTFOLIO_CHANGE,
    case when NOTE_TITLE_DETAIL = 'Agent' then 1 else 0 end as IS_AGENT_CHANGE,
    case when NOTE_TITLE_DETAIL = 'Source Company' then 1 else 0 end as IS_SOURCE_COMPANY_CHANGE,
    NOTE_TITLE, 
    DELETED, 
    IS_HARD_DELETED,
    PORTFOLIOS_ADDED,
    PORTFOLIOS_ADDED_CATEGORY,
    PORTFOLIOS_ADDED_LABEL
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOANPRO_APP_SYSTEM_NOTES;