-- Simple test to verify SIMM join doesn't affect existing row counts
-- Tests that adding the LEFT JOIN for SIMM doesn't filter any existing records

-- Test 1: Verify row count remains the same for daily table
WITH test_date AS (
    SELECT '2025-07-30'::DATE as ASOFDATE
)
SELECT 
    'Original Daily Table' as TEST_NAME,
    COUNT(*) as RECORD_COUNT,
    COUNT(DISTINCT PAYOFFUID) as UNIQUE_LOANS
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION
WHERE ASOFDATE = (SELECT ASOFDATE FROM test_date)

UNION ALL

-- Test with SIMM LEFT JOIN added (should be same count) - using corrected join logic
SELECT 
    'With SIMM LEFT JOIN' as TEST_NAME,
    COUNT(*) as RECORD_COUNT,
    COUNT(DISTINCT dt.PAYOFFUID) as UNIQUE_LOANS
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION dt
LEFT JOIN BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST simm
    ON simm.SET_NAME = 'SIMM' 
    AND simm.SUPPRESSION_FLAG = FALSE
    AND simm.PAYOFFUID = dt.PAYOFFUID
    AND simm.LOAN_TAPE_ASOFDATE = dt.ASOFDATE
WHERE dt.ASOFDATE = (SELECT ASOFDATE FROM test_date);

-- Test 2: Verify SIMM flag calculation using corrected join logic
SELECT 
    'SIMM Flag Distribution' as TEST_NAME,
    CASE 
        WHEN simm.PAYOFFUID IS NOT NULL THEN 1 
        ELSE 0 
    END AS SIMM_FLAG,
    COUNT(*) as RECORD_COUNT
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION dt
LEFT JOIN BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST simm
    ON simm.SET_NAME = 'SIMM' 
    AND simm.SUPPRESSION_FLAG = FALSE
    AND simm.PAYOFFUID = dt.PAYOFFUID
    AND simm.LOAN_TAPE_ASOFDATE = dt.ASOFDATE
WHERE dt.ASOFDATE = '2025-07-30'
GROUP BY SIMM_FLAG;