-- Test both SIMM flag approaches: Current (exact date) vs Historical (cumulative)
-- This validates the difference between daily activity and cumulative status

WITH test_date AS (
    SELECT '2025-07-30'::DATE as ASOFDATE
),
simm_placements AS (
    SELECT 
        PAYOFFUID,
        MIN(LOAN_TAPE_ASOFDATE) as FIRST_SIMM_DATE
    FROM BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST
    WHERE SET_NAME = 'SIMM'
        AND SUPPRESSION_FLAG = FALSE
    GROUP BY PAYOFFUID
)
SELECT 
    'CURRENT SIMM (Exact Date Match)' as FLAG_TYPE,
    COUNT(*) as TOTAL_RECORDS,
    SUM(CASE WHEN simm_current.PAYOFFUID IS NOT NULL THEN 1 ELSE 0 END) as SIMM_FLAG_COUNT,
    ROUND(SUM(CASE WHEN simm_current.PAYOFFUID IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) as SIMM_PERCENTAGE
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION dt
LEFT JOIN BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST simm_current
    ON simm_current.SET_NAME = 'SIMM' 
    AND simm_current.SUPPRESSION_FLAG = FALSE
    AND simm_current.PAYOFFUID = dt.PAYOFFUID
    AND simm_current.LOAN_TAPE_ASOFDATE = dt.ASOFDATE
WHERE dt.ASOFDATE = (SELECT ASOFDATE FROM test_date)

UNION ALL

SELECT 
    'HISTORICAL SIMM (Ever Placed)' as FLAG_TYPE,
    COUNT(*) as TOTAL_RECORDS,  
    SUM(CASE 
        WHEN s.PAYOFFUID IS NOT NULL AND dt.ASOFDATE >= s.FIRST_SIMM_DATE 
        THEN 1 ELSE 0 
    END) as SIMM_FLAG_COUNT,
    ROUND(SUM(CASE 
        WHEN s.PAYOFFUID IS NOT NULL AND dt.ASOFDATE >= s.FIRST_SIMM_DATE 
        THEN 1 ELSE 0 
    END) * 100.0 / COUNT(*), 2) as SIMM_PERCENTAGE
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION dt
LEFT JOIN simm_placements s ON dt.PAYOFFUID = s.PAYOFFUID
WHERE dt.ASOFDATE = (SELECT ASOFDATE FROM test_date);

-- Show breakdown by flag combination
SELECT 
    'COMBINATION ANALYSIS' as ANALYSIS_TYPE,
    CASE 
        WHEN simm_current.PAYOFFUID IS NOT NULL THEN 'Current=1' 
        ELSE 'Current=0' 
    END as CURRENT_FLAG,
    CASE 
        WHEN s.PAYOFFUID IS NOT NULL AND dt.ASOFDATE >= s.FIRST_SIMM_DATE 
        THEN 'Historical=1' 
        ELSE 'Historical=0' 
    END as HISTORICAL_FLAG,
    COUNT(*) as RECORD_COUNT
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_GR_DAILY_ROLL_TRANSITION dt
LEFT JOIN BUSINESS_INTELLIGENCE.CRON_STORE.RPT_OUTBOUND_LISTS_HIST simm_current
    ON simm_current.SET_NAME = 'SIMM' 
    AND simm_current.SUPPRESSION_FLAG = FALSE
    AND simm_current.PAYOFFUID = dt.PAYOFFUID
    AND simm_current.LOAN_TAPE_ASOFDATE = dt.ASOFDATE
LEFT JOIN simm_placements s ON dt.PAYOFFUID = s.PAYOFFUID
WHERE dt.ASOFDATE = '2025-07-30'
GROUP BY CURRENT_FLAG, HISTORICAL_FLAG
ORDER BY CURRENT_FLAG, HISTORICAL_FLAG;