-- DI-1140: LOS Applications Analysis - BMO Bank Fraud Ring
-- SYSTEM: LoanPro LOS (Loan Origination System) - Applications
-- RT# 071025661 = BMO Harris Bank
-- ENHANCED: Includes loan amounts, applicant state, and capital partner (GIACT excluded due to data quality issues)

-- Variables for easy modification
SET ROUTING_NUMBER = '071025661';  -- BMO Harris Bank routing number
SET ANALYSIS_DATE = '2025-08-01';  -- Friday when request was submitted
SET DAYS_THRESHOLD = (SELECT (30 + DATEDIFF('day', $ANALYSIS_DATE, CURRENT_DATE())));  -- Dynamic: 30 days + difference between analysis date and today

-- LOS APPLICATIONS QUERY
with fraud_portfolios as (
    select 
        listagg(PORTFOLIO_NAME,',') as CURRENT_fraud_portfolios, 
        APPLICATION_ID 
    from BUSINESS_INTELLIGENCE.ANALYTICS.VW_APP_PORTFOLIOS_AND_SUB_PORTFOLIOS
    where PORTFOLIO_CATEGORY = 'Fraud' 
    group by all
)
SELECT 
    -- === APPLICATION IDENTIFICATION ===
    bi.LOAN_ID as APPLICATION_ID,
    -- === LMS PROGRESSION TRACKING ===
    LMS.LOAN_ID as LMS_LOAN_ID,
    vlcc.CUSTOMER_ID,
    -- === BANKING DETAILS ===
    bi.ROUTING_NUMBER,
    bi.ACCOUNT_TYPE,
    bi.ACCOUNT_NUMBER,
    -- === DATE ANALYSIS ===
    le.CREATED as APPLICATION_CREATED_DATE,
    DATEDIFF('day', le.CREATED, CURRENT_DATE()) as DAYS_SINCE_CREATION,
    $DAYS_THRESHOLD AS CREATION_DAYS_THRESHOLD_BOUNDARY,
    le.CREATED >= DATEADD('day', -$DAYS_THRESHOLD, CURRENT_DATE) as APP_CREATED_INSIDE_OF_BOUNDARY_IND,
    giact.ACCOUNT_ADDED_DATE >= DATEADD('day', -$DAYS_THRESHOLD, CURRENT_DATE) as GIACT_ACCOUNT_CREATED_INSIDE_OF_BOUNDARY_IND,
    -- === GIACT BANK ACCOUNT INFORMATION ===
    giact.ACCOUNT_ADDED_DATE as GIACT_ACCOUNT_CREATION_DATE,
    giact.ACCOUNT_CLOSED_DATE as GIACT_ACCOUNT_CLOSED_DATE,
    giact.ACCOUNT_LAST_UPDATED_DATE as GIACT_ACCOUNT_LAST_UPDATED,
    giact.ACCOUNT_AGE_DAYS as GIACT_ACCOUNT_AGE_DAYS,
    giact.BANK_ACCOUNT_TYPE as GIACT_ACCOUNT_TYPE,
    giact.BANK_NAME as GIACT_BANK_NAME,
    -- === APPLICATION STATUS ===
    /* le.ACTIVE,
    le.DELETED,
    le.ARCHIVED, */
    lssec.TITLE as APP_STATUS,

    CLS.APPLICATION_GUID as LEAD_GUID,
    CLS.FIRST_NAME as FIRST_NAME,
    CLS.LAST_NAME as LAST_NAME,
    CLS.FRAUD_STATUS,
    CLS.FRAUD_REASON,
    vapasp.current_fraud_portfolios,
    -- === ENHANCED LOAN AND APPLICATION DATA ===
    CLS.REQUESTED_LOAN_AMOUNT as REQUESTED_LOAN_AMOUNT,
    CLS.LOAN_AMOUNT as FINAL_LOAN_AMOUNT,
    CLS.CAPITAL_PARTNER,
    CLS.HOME_ADDRESS_STATE as APPLICANT_STATE,
    CLS.BUREAU_STATE,
    CLS.UTM_SOURCE,
    CLS.UTM_MEDIUM,
    CLS.LOAN_PURPOSE,
    CLS.BORROWER_STATED_ANNUAL_INCOME
    /*giact.ACCOUNT_RESPONSE_CODE as GIACT_ACCOUNT_RESPONSE_CODE,
    giact.CUSTOMER_RESPONSE_CODE as GIACT_CUSTOMER_RESPONSE_CODE,
    giact.VERIFICATION_RESPONSE as GIACT_VERIFICATION_RESPONSE,
    giact.FUNDS_CONFIRMATION_RESULT as GIACT_FUNDS_CONFIRMATION,
    giact.CONSUMER_ALERT_MESSAGES as GIACT_CONSUMER_ALERTS,
    giact.GIACT_AUTHENTICATE_ENABLED,
    giact.GIACT_VERIFY_ENABLED*/
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_BANK_INFO bi
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_ENTITY_CURRENT le 
    ON bi.LOAN_ID = le.ID AND le.SCHEMA_NAME = ARCA.CONFIG.LOS_SCHEMA()
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_SETTINGS_ENTITY_CURRENT lsec
    ON bi.LOAN_ID = lsec.LOAN_ID and lsec.SCHEMA_NAME = ARCA.CONFIG.LOS_SCHEMA()
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_SUB_STATUS_ENTITY_CURRENT lssec
    ON lsec.LOAN_SUB_STATUS_ID = lssec.id and lssec.SCHEMA_NAME = ARCA.CONFIG.LOS_SCHEMA()
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_CUSTOMER_CURRENT vlcc
    on bi.LOAN_ID = vlcc.LOAN_ID and vlcc.SCHEMA_NAME = ARCA.CONFIG.LOS_SCHEMA()
JOIN ARCA.FRESHSNOW.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT as CLS
    on LE.ID = CLS.LOAN_ID

LEFT JOIN fraud_portfolios vapasp
    on bi.LOAN_ID = vapasp.APPLICATION_ID

-- Join to LMS to check if application became a loan
LEFT JOIN ARCA.FRESHSNOW.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT LMS
    ON CLS.APPLICATION_GUID = LMS.LEAD_GUID

-- Join to GIACT data for bank account information and creation dates
LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_OSCILAR_GIACT_DATA giact
    ON CAST(bi.LOAN_ID AS VARCHAR) = CAST(giact.APPLICATION_ID AS VARCHAR)
    AND CAST(bi.ROUTING_NUMBER AS VARCHAR) = CAST(giact.GIACT_ROUTING_NUMBER AS VARCHAR)
    AND CAST(bi.ACCOUNT_NUMBER AS VARCHAR) = CAST(giact.GIACT_ACCOUNT_NUMBER AS VARCHAR)
WHERE 1=1
    -- BMO Bank filtering
    AND bi.ROUTING_NUMBER = $ROUTING_NUMBER
    -- LOS system only (applications)
    AND le.SCHEMA_NAME = ARCA.CONFIG.LOS_SCHEMA()
    -- Active applications only
    AND le.ACTIVE = 1
    AND le.DELETED = 0
ORDER BY le.CREATED DESC;