-- DI-1140: LMS Originated Loans Analysis - BMO Bank Fraud Ring  
-- SYSTEM: LoanPro LMS (Loan Management System) - Originated/Funded Loans
-- RT# 071025661 = BMO Harris Bank
-- ENHANCED: Includes loan amounts, applicant state, and capital partner (GIACT excluded due to data quality issues)

-- Variables for easy modification
SET ROUTING_NUMBER = '071025661';  -- BMO Harris Bank routing number
SET ANALYSIS_DATE = '2025-08-01';  -- Friday when request was submitted
SET DAYS_THRESHOLD = (SELECT (30 + DATEDIFF('day', $ANALYSIS_DATE, CURRENT_DATE())));  -- Dynamic: 30 days + difference between analysis date and today

-- Create LMS version of bank info (VW_BANK_INFO is LOS-only)
WITH lms_bank_info AS (
    SELECT 
        le.id AS LOAN_ID, 
        cae.ACCOUNT_TYPE, 
        cae.ACCOUNT_NUMBER, 
        cae.ROUTING_NUMBER
    FROM ARCA.FRESHSNOW.loan_entity_current le
    JOIN ARCA.FRESHSNOW.loan_settings_entity_current lse ON le.settings_id = lse.id
    JOIN ARCA.FRESHSNOW.loan_customer_current lc ON lc.loan_id = le.id AND customer_role = 'loan.customerRole.primary'
    JOIN ARCA.pii.customer_entity_current ce ON ce.id = lc.customer_id
    LEFT JOIN ARCA.FRESHSNOW.vw_source_company_entity_current sce ON sce.id = lse.source_company
    LEFT JOIN ARCA.FRESHSNOW.payment_account_entity_current pae ON ce.id = pae.entity_id AND pae.is_primary = 1 AND pae.active = 1
    LEFT JOIN ARCA.FRESHSNOW.checking_account_entity_current cae ON pae.checking_account_id = cae.id
    WHERE 1=1
      AND le.SCHEMA_NAME = ARCA.config.lms_schema()
      AND lc.SCHEMA_NAME = ARCA.config.lms_schema()
      AND ce.SCHEMA_NAME = ARCA.config.lms_schema()
      AND sce.SCHEMA_NAME = ARCA.config.lms_schema()
      AND pae.SCHEMA_NAME = ARCA.config.lms_schema()
      AND cae.SCHEMA_NAME = ARCA.config.lms_schema()
      AND lse.SCHEMA_NAME = ARCA.config.lms_schema()
)

SELECT 
    -- === LOAN IDENTIFICATION ===
    bi.LOAN_ID,
    vlcc.CUSTOMER_ID,
    -- === BANKING DETAILS ===
    bi.ROUTING_NUMBER,
    bi.ACCOUNT_TYPE,
    bi.ACCOUNT_NUMBER,
    -- === DATE ANALYSIS ===
    le.CREATED as LOAN_ORIGINATED_DATE,
    DATEDIFF('day', le.CREATED, CURRENT_DATE()) as DAYS_SINCE_ORIGINATION,
    $DAYS_THRESHOLD AS ORIGINATION_DAYS_THRESHOLD_BOUNDARY,
    le.CREATED >= DATEADD('day', -$DAYS_THRESHOLD, CURRENT_DATE) as LOAN_ORIGINATED_INSIDE_OF_BOUNDARY_IND,
    giact.ACCOUNT_ADDED_DATE >= DATEADD('day', -$DAYS_THRESHOLD, CURRENT_DATE) as GIACT_ACCOUNT_CREATED_INSIDE_OF_BOUNDARY_IND,
    -- === GIACT BANK ACCOUNT INFORMATION ===
    giact.ACCOUNT_ADDED_DATE as GIACT_ACCOUNT_CREATION_DATE,
    giact.ACCOUNT_CLOSED_DATE as GIACT_ACCOUNT_CLOSED_DATE,
    giact.ACCOUNT_LAST_UPDATED_DATE as GIACT_ACCOUNT_LAST_UPDATED,
    giact.ACCOUNT_AGE_DAYS as GIACT_ACCOUNT_AGE_DAYS,
    giact.BANK_ACCOUNT_TYPE as GIACT_ACCOUNT_TYPE,
    giact.BANK_NAME as GIACT_BANK_NAME,
    -- === LOAN STATUS ===
    /* le.ACTIVE,
    le.DELETED,
    le.ARCHIVED, */
    lssec.TITLE as LOAN_STATUS,
    -- === LMS LOAN DATA ===
    CLS.LEAD_GUID,
    CLS.FRAUD_CONFIRMED_DATE,
    CLS.FRAUD_INVESTIGATION_RESULTS,
    CLS.FRAUD_NOTIFICATION_RECEIVED,
    -- === ENHANCED LOAN AND APPLICATION DATA ===
    LOS.REQUESTED_LOAN_AMOUNT as REQUESTED_LOAN_AMOUNT,
    LOS.LOAN_AMOUNT as FINAL_LOAN_AMOUNT,
    LOS.CAPITAL_PARTNER,
    LOS.HOME_ADDRESS_STATE as APPLICANT_STATE,
    LOS.BUREAU_STATE,
    LOS.UTM_SOURCE,
    LOS.UTM_MEDIUM,
    LOS.LOAN_PURPOSE,
    LOS.BORROWER_STATED_ANNUAL_INCOME
    /*giact.ACCOUNT_RESPONSE_CODE as GIACT_ACCOUNT_RESPONSE_CODE,
    giact.CUSTOMER_RESPONSE_CODE as GIACT_CUSTOMER_RESPONSE_CODE,
    giact.VERIFICATION_RESPONSE as GIACT_VERIFICATION_RESPONSE,
    giact.FUNDS_CONFIRMATION_RESULT as GIACT_FUNDS_CONFIRMATION,
    giact.CONSUMER_ALERT_MESSAGES as GIACT_CONSUMER_ALERTS,
    giact.GIACT_AUTHENTICATE_ENABLED,
    giact.GIACT_VERIFY_ENABLED,
    giact.ERROR_MESSAGE as GIACT_ERROR_MESSAGE*/

FROM lms_bank_info bi
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_ENTITY_CURRENT le 
    ON bi.LOAN_ID = le.ID 
    AND le.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA()
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_SETTINGS_ENTITY_CURRENT lsec
    ON bi.LOAN_ID = lsec.LOAN_ID
    AND lsec.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA()
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_SUB_STATUS_ENTITY_CURRENT lssec
    ON lsec.LOAN_SUB_STATUS_ID = lssec.ID 
    AND lssec.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA()
JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_CUSTOMER_CURRENT vlcc
    ON bi.LOAN_ID = vlcc.LOAN_ID 
    AND vlcc.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA()
LEFT JOIN ARCA.FRESHSNOW.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT CLS
    ON le.ID = CLS.LOAN_ID
LEFT JOIN ARCA.FRESHSNOW.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT LOS
    ON CLS.LEAD_GUID = LOS.APPLICATION_GUID

-- Join to GIACT data for bank account information and creation dates
LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_OSCILAR_GIACT_DATA giact
    ON CAST(LOS.LOAN_ID AS VARCHAR) = CAST(giact.APPLICATION_ID AS VARCHAR)
    AND CAST(bi.ROUTING_NUMBER AS VARCHAR) = CAST(giact.GIACT_ROUTING_NUMBER AS VARCHAR)
    AND CAST(bi.ACCOUNT_NUMBER AS VARCHAR) = CAST(giact.GIACT_ACCOUNT_NUMBER AS VARCHAR)

WHERE 1=1
    AND bi.ROUTING_NUMBER = $ROUTING_NUMBER
    AND le.ACTIVE = 1
    AND le.DELETED = 0
    
ORDER BY le.CREATED DESC;