/***********************************************************************************************************************
DI-1131 Sample Validation Examples
Date: 2025-08-20
Author: Kyle Chalmers

Purpose: Show specific examples of contact date logic working correctly
***********************************************************************************************************************/

-- Example 1: Phone with exactly 1 PayoffUID (should show NULL dates)
SELECT 'PHONE_1_PAYOFF_EXAMPLE' as EXAMPLE_TYPE, PHONE, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_PHONE_TO_PAYOFFUID_MATCH
WHERE PHONE IN (
    SELECT PHONE 
    FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_PHONE_TO_PAYOFFUID_MATCH 
    GROUP BY PHONE 
    HAVING COUNT(DISTINCT PAYOFFUID) = 1
    LIMIT 5
)

UNION ALL

-- Example 2: Phone with exactly 2 PayoffUIDs (should show one NULL first, one NULL last)
SELECT 'PHONE_2_PAYOFF_EXAMPLE' as EXAMPLE_TYPE, PHONE, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_PHONE_TO_PAYOFFUID_MATCH
WHERE PHONE IN (
    SELECT PHONE 
    FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_PHONE_TO_PAYOFFUID_MATCH 
    GROUP BY PHONE 
    HAVING COUNT(DISTINCT PAYOFFUID) = 2
    LIMIT 3
)

UNION ALL

-- Example 3: Phone with 3+ PayoffUIDs (should show boundary and middle rows)
SELECT 'PHONE_3_PLUS_PAYOFF_EXAMPLE' as EXAMPLE_TYPE, PHONE, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_PHONE_TO_PAYOFFUID_MATCH
WHERE PHONE IN (
    SELECT PHONE 
    FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_PHONE_TO_PAYOFFUID_MATCH 
    GROUP BY PHONE 
    HAVING COUNT(DISTINCT PAYOFFUID) >= 3
    LIMIT 2
)

UNION ALL

-- Example 4: Email with exactly 1 PayoffUID (should show NULL dates)
SELECT 'EMAIL_1_PAYOFF_EXAMPLE' as EXAMPLE_TYPE, EMAIL as PHONE, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_EMAIL_TO_PAYOFFUID_MATCH
WHERE EMAIL IN (
    SELECT EMAIL 
    FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_EMAIL_TO_PAYOFFUID_MATCH 
    GROUP BY EMAIL 
    HAVING COUNT(DISTINCT PAYOFFUID) = 1
    LIMIT 5
)

UNION ALL

-- Example 5: Email with exactly 2 PayoffUIDs (should show one NULL first, one NULL last)
SELECT 'EMAIL_2_PAYOFF_EXAMPLE' as EXAMPLE_TYPE, EMAIL as PHONE, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_EMAIL_TO_PAYOFFUID_MATCH
WHERE EMAIL IN (
    SELECT EMAIL 
    FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS_PII.VW_EMAIL_TO_PAYOFFUID_MATCH 
    GROUP BY EMAIL 
    HAVING COUNT(DISTINCT PAYOFFUID) = 2
    LIMIT 3
)

ORDER BY EXAMPLE_TYPE, PHONE, FIRST_POSSIBLE_CONTACT_DATE;