/*
Multi-Remediation Loans Settlement Analysis
Join CO_LOANS_WITH_MULTI_REMEDIATIONS with VW_LOAN_DEBT_SETTLEMENT
Purpose: Determine how many multi-remediation loans have settlement data
*/

/*USE WAREHOUSE BUSINESS_INTELLIGENCE;
USE ROLE BUSINESS_INTELLIGENCE;
USE SCHEMA BUSINESS_INTELLIGENCE.ANALYTICS;

-- Create a file format for CSV processing
CREATE OR REPLACE FILE FORMAT csv_format
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Query to analyze settlement data for multi-remediation loans
WITH multi_remediation_loans AS (
    SELECT
        TRIM($1, '"') as PAYOFF_LOAN_ID,
        $2 as LEAD_GUID
    FROM @~/COloanswithmultipleremediations.csv.gz
    (FILE_FORMAT => csv_format)
)*/
SELECT
    multi.PAYOFF_LOAN_ID,
    LOWER(multi.LEAD_GUID) AS LEAD_GUID,
    -- All settlement fields from VW_LOAN_DEBT_SETTLEMENT
    vlds.LOAN_ID::varchar as loan_id,
    vlds.SETTLEMENTSTATUS,
    vlds.CURRENT_STATUS,
    vlds.SETTLEMENT_AMOUNT,
    vlds.SETTLEMENT_AMOUNT_PAID,
    vlds.SETTLEMENTAGREEMENTAMOUNT,
    vlds.TOTAL_PAID_AT_TIME_OF_SETTLEMENT,
    vlds.PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT,
    vlds.AMOUNT_FORGIVEN,
    vlds.SETTLEMENT_COMPANY,
    vlds.SETTLEMENT_ACCEPTED_DATE,
    vlds.SETTLEMENT_START_DATE,
    vlds.SETTLEMENT_COMPLETION_DATE,
    vlds.EXPECTED_SETTLEMENT_END_DATE,
    vlds.DEBT_SETTLEMENT_PAYMENT_TERMS,
    vlds.SETTLEMENT_PORTFOLIOS,
    vlds.SETTLEMENT_PORTFOLIO_COUNT,
    vlds.HAS_CUSTOM_FIELDS,
    vlds.HAS_SETTLEMENT_PORTFOLIO,
    vlds.HAS_SETTLEMENT_SUB_STATUS,
    vlds.DATA_SOURCE_COUNT,
    vlds.DATA_COMPLETENESS_FLAG,
    vlds.DATA_SOURCE_LIST
FROM "BUSINESS_INTELLIGENCE_DEV"."CRON_STORE"."CO_LOANS_WITH_MULTI_REMEDIATIONS" multi
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT vlds
    ON lower(multi.LEAD_GUID) = lower(vlds.LEAD_GUID)
ORDER BY vlds.data_source_count DESC nulls last, multi.PAYOFF_LOAN_ID;