/*
DI-1262: LOAN_DEBT_SETTLEMENT Quality Control Validation
MANDATORY QC SUITE - Testing ACTUAL Development Object with Production Data

TARGET: BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT
CRITICAL: Execute all sections and validate results before proceeding
*/

-- ============================================
-- 1. RECORD COUNT VALIDATION
-- ============================================

--1.1: Record Count Comparison
SELECT
    'Development Object' as source,
    COUNT(*) as record_count
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT

UNION ALL

SELECT
    'Custom Field Loans' as source,
    COUNT(*) as record_count
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
WHERE (SETTLEMENTSTATUS IS NOT NULL AND SETTLEMENTSTATUS <> '')
   OR (SETTLEMENT_AMOUNT IS NOT NULL AND SETTLEMENT_AMOUNT > 0)
   OR (DEBT_SETTLEMENT_COMPANY IS NOT NULL AND DEBT_SETTLEMENT_COMPANY <> '')
   OR (SETTLEMENTCOMPANY IS NOT NULL AND SETTLEMENTCOMPANY <> '')
   OR SETTLEMENTSTARTDATE IS NOT NULL
   OR SETTLEMENTAGREEMENTAMOUNT IS NOT NULL
   OR DEBTSETTLEMENTPAYMENTTERMS IS NOT NULL
   OR EXPECTEDSETTLEMENTENDDATE IS NOT NULL

UNION ALL

SELECT
    'Portfolio Loans' as source,
    COUNT(DISTINCT LOAN_ID) as record_count
FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_PORTFOLIOS_AND_SUB_PORTFOLIOS
WHERE PORTFOLIO_CATEGORY = 'Settlement'

UNION ALL

SELECT
    'Sub Status Loans' as source,
    COUNT(DISTINCT LOAN_ID) as record_count
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_STATUS_ARCHIVE_CURRENT
WHERE LOAN_SUB_STATUS_TEXT = 'Closed - Settled in Full'
  AND SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LMS_SCHEMA()

UNION ALL

SELECT
    'Expected Union Total' as source,
    COUNT(*) as record_count
FROM (
    SELECT LOAN_ID FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
    WHERE (SETTLEMENTSTATUS IS NOT NULL AND SETTLEMENTSTATUS <> '')
       OR (SETTLEMENT_AMOUNT IS NOT NULL AND SETTLEMENT_AMOUNT > 0)
       OR (DEBT_SETTLEMENT_COMPANY IS NOT NULL AND DEBT_SETTLEMENT_COMPANY <> '')
       OR (SETTLEMENTCOMPANY IS NOT NULL AND SETTLEMENTCOMPANY <> '')
       OR SETTLEMENTSTARTDATE IS NOT NULL
       OR SETTLEMENTAGREEMENTAMOUNT IS NOT NULL
       OR DEBTSETTLEMENTPAYMENTTERMS IS NOT NULL
       OR EXPECTEDSETTLEMENTENDDATE IS NOT NULL
    UNION
    SELECT DISTINCT LOAN_ID FROM BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_PORTFOLIOS_AND_SUB_PORTFOLIOS
    WHERE PORTFOLIO_CATEGORY = 'Settlement'
    UNION
    SELECT DISTINCT LOAN_ID FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_STATUS_ARCHIVE_CURRENT
    WHERE LOAN_SUB_STATUS_TEXT = 'Closed - Settled in Full'
      AND SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LMS_SCHEMA()
) union_result;

-- ============================================
-- 2. DUPLICATE DETECTION & DATA COMPLETENESS
-- ============================================

--2.1: Duplicate Check and Data Source Distribution
SELECT
    'Duplicates Found' as metric,
    COUNT(*) as count
FROM (
    SELECT LOAN_ID, COUNT(*) as dup_count
    FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT
    GROUP BY LOAN_ID
    HAVING COUNT(*) > 1
) duplicates

UNION ALL

SELECT
    CONCAT('Data Source Count: ', DATA_SOURCE_COUNT) as metric,
    COUNT(*) as count
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT
GROUP BY DATA_SOURCE_COUNT
ORDER BY metric;

-- ============================================
-- 3. BUSINESS LOGIC & DATA QUALITY
-- ============================================

--3.1: Settlement Status Values and Data Quality Issues
SELECT
    'Settlement Status' as data_type,
    SETTLEMENTSTATUS as value,
    COUNT(*) as count
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT
WHERE SETTLEMENTSTATUS IS NOT NULL AND SETTLEMENTSTATUS <> ''
GROUP BY SETTLEMENTSTATUS

UNION ALL

SELECT
    'Portfolio Type' as data_type,
    TRIM(value) as value,
    COUNT(*) as count
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT,
     LATERAL SPLIT_TO_TABLE(SETTLEMENT_PORTFOLIOS, '; ')
WHERE SETTLEMENT_PORTFOLIOS IS NOT NULL
GROUP BY TRIM(value)

UNION ALL

SELECT
    'Negative Settlement Amounts' as data_type,
    'Count Found' as value,
    COUNT(*) as count
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT
WHERE SETTLEMENT_AMOUNT < 0

ORDER BY data_type, value;

-- ============================================
-- 4. FINAL SUMMARY METRICS
-- ============================================

--4.1: Overall Performance and Join Summary
SELECT
    COUNT(*) as total_loans,
    COUNT(CASE WHEN SETTLEMENTSTATUS IS NOT NULL OR DEBT_SETTLEMENT_COMPANY IS NOT NULL THEN 1 END) as loans_with_settlement_data,
    COUNT(CASE WHEN CURRENT_SUB_STATUS_TEXT IS NOT NULL THEN 1 END) as loans_with_sub_status,
    COUNT(CASE WHEN SETTLEMENT_PORTFOLIOS IS NOT NULL THEN 1 END) as loans_with_portfolios,
    ROUND((COUNT(CASE WHEN CURRENT_SUB_STATUS_TEXT IS NOT NULL THEN 1 END) * 100.0) / COUNT(*), 2) as sub_status_join_success_rate,
    MIN(SETTLEMENT_AMOUNT) as min_settlement_amount,
    MAX(SETTLEMENT_AMOUNT) as max_settlement_amount,
    AVG(SETTLEMENT_AMOUNT) as avg_settlement_amount
FROM BUSINESS_INTELLIGENCE_DEV.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT;