-- Current Production DDL for VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
-- Extracted: 2025-09-24
-- Source: ARCA.FRESHSNOW.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT

create or replace view ARCA.FRESHSNOW.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT  as
select le.id as loan_id
,cs.entity_id as settings_id
,TRY_CAST(CUSTOM_FIELD_VALUES:PROCESSINGFEESPAID::VARCHAR AS NUMERIC(30,2)) as PROCESSING_FEES_PAID
,CUSTOM_FIELD_VALUES:BANKRUPTCYCASENUMBER::VARCHAR as BANKRUPTCY_CASE_NUMBER
,CUSTOM_FIELD_VALUES:BANKRUPTCYCOURTDISTRICT::VARCHAR as BANKRUPTCY_COURT_DISTRICT
,TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYFILINGDATE::VARCHAR AS DATE) as BANKRUPTCY_FILING_DATE
,CUSTOM_FIELD_VALUES:BANKRUPTCYVENDOR::VARCHAR as BANKRUPTCY_VENDOR
,TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWLOANAMOUNT::VARCHAR AS NUMERIC(30,2)) as BANKRUPTCY_ORDERED_NEW_LOAN_AMOUNT
,CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWINTERESTRATE::VARCHAR as BANKRUPTCY_ORDERED_NEW_INTEREST_RATE
,CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNUMBEROFPAYMENTS::VARCHAR as BANKRUPTCY_ORDERED_NUMBER_OF_PAYMENTS
,TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2)) as BANKRUPTCY_ORDERED_NEW_PAYMENT_AMOUNT
,CUSTOM_FIELD_VALUES:COMPLIANCECONDITIONCODE::VARCHAR as COMPLIANCE_CONDITION_CODE
,CUSTOM_FIELD_VALUES:REPOSSESSIONREVIEWDECISION::VARCHAR as REPOSSESSION_REVIEW_DECISION
,CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYNAME::VARCHAR as REPOSSESSION_COMPANY_NAME
,CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYCONTACTNAME::VARCHAR as REPOSSESSION_COMPANY_CONTACT_NAME
,CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYPHONENUMBER::VARCHAR as REPOSSESSION_COMPANY_PHONE_NUMBER
,CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYEMAILADDRESS::VARCHAR as REPOSSESSION_COMPANY_EMAIL_ADDRESS
,TRY_CAST(CUSTOM_FIELD_VALUES:REPOSSESSIONMANAGERDECLINEDATE::VARCHAR AS DATE) as REPOSSESSION_MANAGER_DECLINE_DATE
,CUSTOM_FIELD_VALUES:REPOSSESSIONCITY::VARCHAR as REPOSSESSION_CITY
,CUSTOM_FIELD_VALUES:REPOSSESSIONCOUNTY::VARCHAR as REPOSSESSION_COUNTY
,CUSTOM_FIELD_VALUES:REPOSSESSIONSTATE::VARCHAR as REPOSSESSION_STATE
,CUSTOM_FIELD_VALUES:REPOSSESSIONCASENUMBER::VARCHAR as REPOSSESSION_CASE_NUMBER
,TRY_CAST(CUSTOM_FIELD_VALUES:REPOSSESSIONDATE::VARCHAR AS DATE) as REPOSSESSION_DATE
,CUSTOM_FIELD_VALUES:CUSTOMERREDEEMEDCOLLATERAL::VARCHAR as CUSTOMER_REDEEMED_COLLATERAL
,TRY_CAST(CUSTOM_FIELD_VALUES:COLLECTIBLECHARGEOFFDATE::VARCHAR AS DATE) as COLLECTIBLE_CHARGE_OFF_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDATE::VARCHAR AS DATE) as CHARGE_OFF_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DATEOFDEATH::VARCHAR AS DATE) as DATE_OF_DEATH
,TRY_CAST(CUSTOM_FIELD_VALUES:DECEASEDNOTIFICATIONDATE::VARCHAR AS DATE) as DECEASED_NOTIFICATION_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:BALANCEATTHETIMEOFDECEASEDNOTIFICATION::VARCHAR AS NUMERIC(30,2)) as BALANCE_AT_THE_TIME_OF_DECEASED_NOTIFICATION
,CUSTOM_FIELD_VALUES:FRAUDINVESTIGATIONRESULTS::VARCHAR as FRAUD_INVESTIGATION_RESULTS
,TRY_CAST(CUSTOM_FIELD_VALUES:FRAUDCONFIRMEDDATE::VARCHAR AS DATE) as FRAUD_CONFIRMED_DATE
,CUSTOM_FIELD_VALUES:ATTORNEYRETAINED::VARCHAR as ATTORNEY_RETAINED
,CUSTOM_FIELD_VALUES:ATTORNEYTYPE::VARCHAR as ATTORNEY_TYPE
,CUSTOM_FIELD_VALUES:ATTORNEYNAME::VARCHAR as ATTORNEY_NAME
,CUSTOM_FIELD_VALUES:FIRMNAME::VARCHAR as FIRM_NAME
,CUSTOM_FIELD_VALUES:ATTORNEYADDRESS::VARCHAR as ATTORNEY_ADDRESS
,CUSTOM_FIELD_VALUES:ATTORNEYCITY::VARCHAR as ATTORNEY_CITY
,CUSTOM_FIELD_VALUES:ATTORNEYSTATE::VARCHAR as ATTORNEY_STATE
,CUSTOM_FIELD_VALUES:ATTORNEYZIP::VARCHAR as ATTORNEY_ZIP
,CUSTOM_FIELD_VALUES:ATTORNEYPHONE::VARCHAR as ATTORNEY_PHONE
,CUSTOM_FIELD_VALUES:ATTORNEYFAX::VARCHAR as ATTORNEY_FAX
,CUSTOM_FIELD_VALUES:ATTORNEYEMAIL::VARCHAR as ATTORNEY_EMAIL
,TRY_CAST(CUSTOM_FIELD_VALUES:ATTORNEYRETAINEDDATE::VARCHAR AS DATE) as ATTORNEY_RETAINED_DATE
-- === SCRA FIELDS ===
--SCRA NOTIFICATION FIELDS
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE1::VARCHAR AS DATE) as SCRA_NOTIFICATION_DATE1
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE2::VARCHAR AS DATE) as SCRA_NOTIFICATION_DATE2
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE3::VARCHAR AS DATE) as SCRA_NOTIFICATION_DATE3
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE4::VARCHAR AS DATE) as SCRA_NOTIFICATION_DATE4
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE5::VARCHAR AS DATE) as SCRA_NOTIFICATION_DATE5
--END SCRA NOTIFICATION FIELDS
--SCRA START FIELDS
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE1::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_START_DATE1
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE2::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_START_DATE2
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE3::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_START_DATE3
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE4::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_START_DATE4
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE5::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_START_DATE5
--END SCRA START FIELDS
--SCRA END FIELDS
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE1::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_END_DATE1
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE2::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_END_DATE2
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE3::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_END_DATE3
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE4::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_END_DATE4
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE5::VARCHAR AS DATE) as SCRA_ACTIVE_DUTY_END_DATE5
--END SCRA END FIELDS
,CUSTOM_FIELD_VALUES:SCRACUSTOMERISTHESERVICEMEMBER::VARCHAR as SCRA_CUSTOMER_IS_THE_SERVICE_MEMBER
,CUSTOM_FIELD_VALUES:SCRACUSTOMERISADEPENDENTOFTHESERVICEMEMBER::VARCHAR as SCRA_CUSTOMER_IS_A_DEPENDENT_OF_THE_SERVICE_MEMBER
,CUSTOM_FIELD_VALUES:SCRATYPEOFSERVICE::VARCHAR as SCRA_TYPE_OF_SERVICE
,CUSTOM_FIELD_VALUES:SCRADECLINEREASON::VARCHAR as SCRA_DECLINE_REASON
,CUSTOM_FIELD_VALUES:SCRAORDERSRECEIVED::VARCHAR as SCRA_ORDERS_RECEIVED
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAORDERSRECEIVEDDATE::VARCHAR AS DATE) as SCRA_ORDERS_RECEIVED_DATE
,CUSTOM_FIELD_VALUES:SCRAINTERESTRATEADJUSTED::VARCHAR as SCRA_INTEREST_RATE_ADJUSTED
-- === END SCRA FIELDS ===
,TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYNOTIFICATIONRECEIVEDDATE::VARCHAR AS DATE) as BANKRUPTCY_NOTIFICATION_RECEIVED_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DISCHARGEDATE::VARCHAR AS DATE) as DISCHARGE_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DISMISSALDATE::VARCHAR AS DATE) as DISMISSAL_DATE
,CUSTOM_FIELD_VALUES:COMPLAINTSTATUS::VARCHAR as COMPLAINT_STATUS
,CUSTOM_FIELD_VALUES:FUNDINGSTATUS::VARCHAR as FUNDING_STATUS
,TRY_CAST(CUSTOM_FIELD_VALUES:REQUESTEDFIRSTPAYMENTDATE::VARCHAR AS DATE) as REQUESTED_FIRST_PAYMENT_DATE
,CUSTOM_FIELD_VALUES:PAYMENTRATING::VARCHAR as PAYMENT_RATING
,CUSTOM_FIELD_VALUES:SPECIALCOMMENT::VARCHAR as SPECIAL_COMMENT
,CUSTOM_FIELD_VALUES:CONSUMERINDICATOR::VARCHAR as CONSUMER_INDICATOR
,TRY_CAST(CUSTOM_FIELD_VALUES:SOLDDATE::VARCHAR AS DATE) as SOLD_DATE
,CUSTOM_FIELD_VALUES:DEBTSALESTATUS::VARCHAR as DEBT_SALE_STATUS
,CUSTOM_FIELD_VALUES:DEBTBUYER::VARCHAR as DEBT_BUYER
,CUSTOM_FIELD_VALUES:VALIDATIONOFDEBTSTATUS::VARCHAR as VALIDATION_OF_DEBT_STATUS
,TRY_CAST(CUSTOM_FIELD_VALUES:DEBTREQUESTTEST::VARCHAR AS DATE) as DEBT_REQUEST_TEST
,TRY_CAST(CUSTOM_FIELD_VALUES:DEBTREQUESTSENTTEST::VARCHAR AS DATE) as DEBT_REQUEST_SENT_TEST
,TRY_CAST(CUSTOM_FIELD_VALUES:PROMOPERIODEXPIRATIONDATE::VARCHAR AS DATE) as PROMO_PERIOD_EXPIRATION_DATE
,CUSTOM_FIELD_VALUES:BANKRUPTCYSTATUS::VARCHAR as BANKRUPTCY_STATUS
,CUSTOM_FIELD_VALUES:FUNDINGCANCELLATIONREASON::VARCHAR as FUNDING_CANCELLATION_REASON
,TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDUEPRINCIPAL::VARCHAR AS NUMERIC(30,2)) as CHARGE_OFF_DUE_PRINCIPAL
,TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDUEINTEREST::VARCHAR AS NUMERIC(30,2)) as CHARGE_OFF_DUE_INTEREST
,TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDUEFEES::VARCHAR AS NUMERIC(30,2)) as CHARGE_OFF_DUE_FEES
,CUSTOM_FIELD_VALUES:HARDSHIPDESCRIPTION::VARCHAR as HARDSHIP_DESCRIPTION
,CUSTOM_FIELD_VALUES:DPDATHARDSHIPENROLLMENT::VARCHAR as DPD_AT_HARDSHIP_ENROLLMENT
,TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPENROLLMENTSTARTDATE::VARCHAR AS DATE) as HARDSHIP_ENROLLMENT_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPENROLLMENTENDDATE::VARCHAR AS DATE) as HARDSHIP_ENROLLMENT_END_DATE
,CUSTOM_FIELD_VALUES:HARDSHIPDURATION::VARCHAR as HARDSHIP_DURATION
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTAMOUNT::VARCHAR AS NUMERIC(30,2)) as SETTLEMENT_AMOUNT
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTACCEPTEDDATE::VARCHAR AS DATE) as SETTLEMENT_ACCEPTED_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:PAYOFFATTHETIMEOFSETTLEMENTARRANGEMENT::VARCHAR AS NUMERIC(30,2)) as PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTSETUPDATE::VARCHAR AS DATE) as SETTLEMENT_SETUP_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTFORGIVEN::VARCHAR AS NUMERIC(30,2)) as AMOUNT_FORGIVEN
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTAMOUNTPAID::VARCHAR AS NUMERIC(30,2)) as SETTLEMENT_AMOUNT_PAID
,TRY_CAST(CUSTOM_FIELD_VALUES:UNPAIDSETTLEMENTBALANCE::VARCHAR AS NUMERIC(30,2)) as UNPAID_SETTLEMENT_BALANCE
,TRY_CAST(CUSTOM_FIELD_VALUES:BALANCEATTIMEOFDEBTSALE::VARCHAR AS NUMERIC(30,2)) as BALANCE_AT_TIME_OF_DEBT_SALE
,CUSTOM_FIELD_VALUES:STATERATE::VARCHAR as STATE_RATE
,CUSTOM_FIELD_VALUES:CREDITCOUNSELORCOMPANY::VARCHAR as CREDIT_COUNSELOR_COMPANY
,CUSTOM_FIELD_VALUES:THIRDPARTYCOLLECTIONAGENCY::VARCHAR as THIRD_PARTY_COLLECTION_AGENCY
,TRY_CAST(CUSTOM_FIELD_VALUES:REPURCHASEAMOUNT::VARCHAR AS NUMERIC(30,2)) as REPURCHASE_AMOUNT
,CUSTOM_FIELD_VALUES:DEBTREPURCHASESTATUS::VARCHAR as DEBT_REPURCHASE_STATUS
,TRY_CAST(CUSTOM_FIELD_VALUES:TOTALPAIDATTIMEOFSETTLEMENT::VARCHAR AS NUMERIC(30,2)) AS TOTAL_PAID_AT_TIME_OF_SETTLEMENT
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTENDDATE::VARCHAR AS DATE) AS SETTLEMENT_END_DATE
,CUSTOM_FIELD_VALUES:PROGRAMID::VARCHAR AS PROGRAM_ID
--,TRY_CAST(CUSTOM_FIELD_VALUES:EXECUTIONDATE::VARCHAR AS DATE) AS EXECUTION_DATE
,COALESCE( CONVERT_TIMEZONE('UTC'
                            ,'America/Los_Angeles'
                            ,TRY_CAST(CUSTOM_FIELD_VALUES:EXECUTIONDATE::VARCHAR AS TIMESTAMP_NTZ)
                            )::date
           ,TRY_CAST(CUSTOM_FIELD_VALUES:EXECUTIONDATE::VARCHAR AS DATE)
         ) as EXECUTION_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:INDIRECTPURCHASEDATE::VARCHAR AS DATE) AS INDIRECT_PURCHASE_DATE
,CUSTOM_FIELD_VALUES:INDIRECTLENDERORIGINATIONFEE::VARCHAR AS INDIRECT_LENDER_ORIGINATION_FEE
,CUSTOM_FIELD_VALUES:INDIRECTAMOUNTORIGINATIONINTEREST::VARCHAR AS INDIRECT_AMOUNT_ORIGINATION_INTEREST
,TRY_CAST(CUSTOM_FIELD_VALUES:PREMIUMRATE::VARCHAR as NUMERIC(30,3)) AS PREMIUM_RATE
,TRY_CAST(CUSTOM_FIELD_VALUES:PREMIUMAMOUNT::VARCHAR as NUMERIC(30,3)) AS PREMIUM_AMOUNT
,CUSTOM_FIELD_VALUES:TENANT_ID::VARCHAR AS TENANT_ID
,CUSTOM_FIELD_VALUES:CHANNEL::VARCHAR AS CHANNEL
,CUSTOM_FIELD_VALUES:LOANPURPOSE::VARCHAR AS LOAN_PURPOSE
,CUSTOM_FIELD_VALUES:LOANTIER::VARCHAR AS LOAN_TIER
,CUSTOM_FIELD_VALUES:CPVERSION::VARCHAR AS CP_VERSION
,CUSTOM_FIELD_VALUES:APPLICANTRESIDENCESTATE::VARCHAR AS APPLICANT_RESIDENCE_STATE
,CUSTOM_FIELD_VALUES:EMPLOYMENTSTATUS::VARCHAR AS EMPLOYMENT_STATUS
,CUSTOM_FIELD_VALUES:HOUSINGSTATUS::VARCHAR AS HOUSING_STATUS
,CUSTOM_FIELD_VALUES:ANNUALINCOME::VARCHAR AS ANNUAL_INCOME
,TRY_CAST(CUSTOM_FIELD_VALUES:BUREAUSCORE::VARCHAR as NUMERIC(30,0)) AS BUREAU_SCORE
,CUSTOM_FIELD_VALUES:BUREAUSCORETYPE::VARCHAR AS BUREAU_SCORE_TYPE
,TRY_CAST(CUSTOM_FIELD_VALUES:NDI::VARCHAR AS NUMERIC(30,2)) AS NDI
,TRY_CAST(CUSTOM_FIELD_VALUES:DTI::VARCHAR AS NUMERIC(30,3)) AS DTI
,CUSTOM_FIELD_VALUES:APPMOSSINCEDEROGPUBREC::VARCHAR AS APP_MOS_SINCE_DEROG_PUB_REC
,CUSTOM_FIELD_VALUES:MLAFLAG::VARCHAR AS MLA_FLAG
,CUSTOM_FIELD_VALUES:REFRESHEDBUREAUSCORE::VARCHAR AS REFRESHED_BUREAU_SCORE
,CUSTOM_FIELD_VALUES:REFRESHEDBUREAUSCOREDATE::VARCHAR AS REFRESHED_BUREAU_SCORE_DATE
,CUSTOM_FIELD_VALUES:SECONDARYBUYER::VARCHAR AS SECONDARY_BUYER
,CUSTOM_FIELD_VALUES:SECONDARYSELLER::VARCHAR AS SECONDARY_SELLER
,TRY_CAST(CUSTOM_FIELD_VALUES:SECONDARYPURCHASEDATE::VARCHAR AS DATE) AS SECONDARY_PURCHASE_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:SECONDARYSOLDDATE::VARCHAR AS DATE) AS SECONDARY_SOLD_DATE
,CUSTOM_FIELD_VALUES:CPDFLAG::VARCHAR AS CPD_FLAG
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRASTARTDATE::VARCHAR AS DATE) AS SCRA_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:SCRAENDDATE::VARCHAR AS DATE) AS SCRA_END_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:CPDPROCESSINGDATE::VARCHAR AS DATE) AS CPD_PROCESSING_DATE
,CUSTOM_FIELD_VALUES:INSURANCEFLAG::VARCHAR AS INSURANCE_FLAG
,TRY_CAST(CUSTOM_FIELD_VALUES:INSURANCESTARTDATE::VARCHAR AS DATE) AS INSURANCE_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:INSURANCEENDDATE::VARCHAR AS DATE) AS INSURANCE_END_DATE
,CUSTOM_FIELD_VALUES:AUTOPAYOPTIN::VARCHAR AS AUTOPAY_OPT_IN
,CUSTOM_FIELD_VALUES:DEBTSETTLEMENTCOMPANY::VARCHAR AS DEBT_SETTLEMENT_COMPANY
,TRY_CAST(CUSTOM_FIELD_VALUES:CEASEANDDESISTDATE::VARCHAR AS DATE) AS CEASE_AND_DESIST_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:PRINCIPALADVANCEREMAINING::VARCHAR AS NUMERIC(30,2)) AS PRINCIPAL_ADVANCE_REMAINING
,CUSTOM_FIELD_VALUES:ORIGINATINGPARTNER::VARCHAR AS ORIGINATING_PARTNER
,TRY_CAST(CUSTOM_FIELD_VALUES:ORIGINATIONFEE::VARCHAR AS NUMERIC(30,2)) AS ORIGINATION_FEE
,TRY_CAST(CUSTOM_FIELD_VALUES:LOANAMOUNT::VARCHAR AS NUMERIC(30,2)) AS LOAN_AMOUNT_C
,TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTFUNDED::VARCHAR AS NUMERIC(30,2)) AS AMOUNT_FUNDED
,TRY_CAST(CUSTOM_FIELD_VALUES:TOTALPREPAIDFEES::VARCHAR AS NUMERIC(30,2)) AS TOTAL_PREPAID_FEES
,CUSTOM_FIELD_VALUES:THIRDPARTYCOMMUNICATIONWITHHMABOUTDEBT::VARCHAR AS THIRD_PARTY_COMMUNICATION_WITH_HM_ABOUT_DEBT
,CUSTOM_FIELD_VALUES:DELINQUENCYREASON::VARCHAR AS DELINQUENCY_REASON
,CUSTOM_FIELD_VALUES:FRAUDCONTACTEMAIL::VARCHAR AS FRAUD_CONTACT_EMAIL
,CUSTOM_FIELD_VALUES:FOLLOWUPINFORMATION::VARCHAR AS FOLLOW_UP_INFORMATION
,TRY_CAST(CUSTOM_FIELD_VALUES:FRAUDNOTIFICATIONRECEIVED::VARCHAR AS DATE) AS FRAUD_NOTIFICATION_RECEIVED
,TRY_CAST(CUSTOM_FIELD_VALUES:EXPECTEDRESPONSEDATE::VARCHAR AS DATE) AS EXPECTED_RESPONSE_DATE
,CUSTOM_FIELD_VALUES:EOSCARDISPUTECODE::VARCHAR AS EOS_CARD_DISPUTE_CODE
,CUSTOM_FIELD_VALUES:ORIGINATOR::VARCHAR AS ORIGINATOR
,CUSTOM_FIELD_VALUES:ACDVNUMBER::VARCHAR AS ACDV_NUMBER
,CUSTOM_FIELD_VALUES:SOURCEOFREFERRAL::VARCHAR AS SOURCE_OF_REFERRAL
,TRY_CAST(CUSTOM_FIELD_VALUES:DATE_SUBMITTED_TO_REFERRER::VARCHAR AS DATE) AS DATE_SUBMITTED_TO_REFERRER
,TRY_CAST(CUSTOM_FIELD_VALUES:REAFFIRMATIONDATE::VARCHAR AS DATE) AS REAFFIRMATION_DATE
,CUSTOM_FIELD_VALUES:INCORRECTCREDITREPORTINGITEM::VARCHAR AS INCORRECT_CREDIT_REPORTING_ITEM
,CUSTOM_FIELD_VALUES:CORRECTEDCREDITREPORTINGITEM::VARCHAR AS CORRECTED_CREDIT_REPORTING_ITEM
,TRY_CAST(CUSTOM_FIELD_VALUES:NEXTWORKABLEDATE::VARCHAR AS DATE) AS NEXT_WORKABLE_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:LASTCOLLECTIONSCONTACTDATE::VARCHAR AS DATE) AS LAST_COLLECTIONS_CONTACT_DATE
,CUSTOM_FIELD_VALUES:NUMBEROFSKIPS::VARCHAR AS NUMBER_OF_SKIPS
,CUSTOM_FIELD_VALUES:SETTLEMENTSTATUSDCA::VARCHAR AS SETTLEMENT_STATUS_DCA
,CUSTOM_FIELD_VALUES:FEERATEDCA::VARCHAR AS FEE_RATE_DCA
,TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTDUETOHAPPYMONEYDCA::VARCHAR AS NUMERIC(30,2)) AS AMOUNT_DUE_TO_HAPPY_MONEY_DCA
,CUSTOM_FIELD_VALUES:SETTLEMENTCOMPANYDCA::VARCHAR AS SETTLEMENT_COMPANY_DCA
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTAGREEMENTAMOUNTDCA::VARCHAR AS NUMERIC(30,2)) AS SETTLEMENT_AGREEMENT_AMOUNT_DCA
,CUSTOM_FIELD_VALUES:HARDSHIPREASON::VARCHAR AS HARDSHIP_REASON
,TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODIFICATIONAGREEMENTSENTDATE::VARCHAR AS DATE) AS LOAN_MODIFICATION_AGREEMENT_SENT_DATE
,CUSTOM_FIELD_VALUES:INVESTOR1::VARCHAR AS INVESTOR1
,CUSTOM_FIELD_VALUES:INVESTOR2::VARCHAR AS INVESTOR2
,CUSTOM_FIELD_VALUES:INVESTOR3::VARCHAR AS INVESTOR3
,CUSTOM_FIELD_VALUES:INVESTOR4::VARCHAR AS INVESTOR4
,CUSTOM_FIELD_VALUES:INVESTOR5::VARCHAR AS INVESTOR5
,CUSTOM_FIELD_VALUES:INVESTOR6::VARCHAR AS INVESTOR6
,CUSTOM_FIELD_VALUES:INVESTOR7::VARCHAR AS INVESTOR7
,CUSTOM_FIELD_VALUES:INVESTOR8::VARCHAR AS INVESTOR8
,CUSTOM_FIELD_VALUES:INVESTOR9::VARCHAR AS INVESTOR9
,CUSTOM_FIELD_VALUES:INVESTOR10::VARCHAR AS INVESTOR10
,CUSTOM_FIELD_VALUES:INVESTOR11::VARCHAR AS INVESTOR11
,CUSTOM_FIELD_VALUES:INVESTOR12::VARCHAR AS INVESTOR12
,CUSTOM_FIELD_VALUES:INVESTOR13::VARCHAR AS INVESTOR13
,CUSTOM_FIELD_VALUES:INVESTOR14::VARCHAR AS INVESTOR14
,CUSTOM_FIELD_VALUES:INVESTOR15::VARCHAR AS INVESTOR15
,TRY_CAST(CUSTOM_FIELD_VALUES:DNU::VARCHAR AS NUMERIC(30,2)) AS DNU
,TRY_CAST(CUSTOM_FIELD_VALUES:MODIFICATIONAGREEMENTEXPIRATIONDATE::VARCHAR AS DATE) AS MODIFICATION_AGREEMENT_EXPIRATION_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODIFICATIONAGREEMENTSIGNEDDATE::VARCHAR AS DATE) AS LOAN_MODIFICATION_AGREEMENT_SIGNED_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:STANDARDSKIPAPAYENROLLMENTSTARTDATE::VARCHAR AS DATE) AS STANDARD_SKIP_A_PAY_ENROLLMENT_START_DATE
,CUSTOM_FIELD_VALUES:TEMPORARYPAYMENTREDUCTIONTERM::VARCHAR AS TEMPORARY_PAYMENT_REDUCTION_TERM
,CUSTOM_FIELD_VALUES:PERCENTAGEOFCURRENTPAYMENT::VARCHAR AS PERCENTAGE_OF_CURRENT_PAYMENT
,TRY_CAST(CUSTOM_FIELD_VALUES:TEMPORARYPAYMENTREDUCTIONENROLLMENTDATE::VARCHAR AS DATE) AS TEMPORARY_PAYMENT_REDUCTION_ENROLLMENT_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:LOANBALANCEATMODIFICATION::VARCHAR AS NUMERIC(30,2)) AS LOAN_BALANCE_AT_MODIFICATION
,CUSTOM_FIELD_VALUES:CLSLOANACCOUNTID::VARCHAR AS CLS_LOAN_ACCOUNT_ID
,CUSTOM_FIELD_VALUES:CLSLOANACCOUNTNAME::VARCHAR as CLS_LOAN_ACCOUNT_NAME
,CUSTOM_FIELD_VALUES:PAYOFFLOANID::VARCHAR as PAYOFF_LOAN_ID
,CUSTOM_FIELD_VALUES:LEADGUID::VARCHAR as LEAD_GUID
,TRY_CAST(CUSTOM_FIELD_VALUES:PAYMENTAMOUNTBEFOREMODIFICATION::VARCHAR AS NUMERIC(30,2)) as PAYMENT_AMOUNT_BEFORE_MODIFICATION
,CUSTOM_FIELD_VALUES:MIGRATEDFROMCLS::VARCHAR as MIGRATED_FROM_CLS
,CUSTOM_FIELD_VALUES:MIGRATEDFROMLAPRO::VARCHAR as MIGRATED_FROM_LA_PRO
,CUSTOM_FIELD_VALUES:MIGRATIONBATCHID::VARCHAR as MIGRATION_BATCH_ID
,TRY_CAST(CUSTOM_FIELD_VALUES:PERMANENTPAYMENTREDUCTIONENROLLMENTDATE::VARCHAR AS DATE) as PERMANENT_PAYMENT_REDUCTION_ENROLLMENT_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DISASTERSKIPAPAYENROLLMENT::VARCHAR AS DATE) as DISASTER_SKIP_A_PAY_ENROLLMENT
,CUSTOM_FIELD_VALUES:MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE::VARCHAR as MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE
,CUSTOM_FIELD_VALUES:ATTORNEY_PREFERRED_METHOD_OF_CONTACT::VARCHAR as ATTORNEY_PREFERRED_METHOD_OF_CONTACT
,TRY_CAST(CUSTOM_FIELD_VALUES:MATURITY_DATE_BEFORE_MOD::VARCHAR AS DATE) as MATURITY_DATE_BEFORE_MOD
,CUSTOM_FIELD_VALUES:MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT::VARCHAR as MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT
,TRY_CAST(CUSTOM_FIELD_VALUES:TRUSTAGESTARTDATE::VARCHAR AS DATE) as TRUSTAGE_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:TRUSTAGEENDDATE::VARCHAR AS DATE) as TRUSTAGE_END_DATE
,CUSTOM_FIELD_VALUES:TRUSTAGECLAIMNUMBER::VARCHAR as TRUSTAGE_CLAIM_NUMBER
,TRY_CAST(CUSTOM_FIELD_VALUES:TRUSTAGEPAYMENTGUARDINSURANCEPROGRAMENROLLMENTDATE::VARCHAR AS DATE) as TRUSTAGE_PAYMENT_GUARD_INSURANCE_PROGRAM_ENROLLMENT_DATE
,CUSTOM_FIELD_VALUES:STATUSPRIORTOMODIFICATION::VARCHAR as STATUS_PRIOR_TO_MODIFICATION
,CUSTOM_FIELD_VALUES:NUMBERPAYMENTSSKIPPED::VARCHAR as NUMBER_PAYMENTS_SKIPPED
,TRY_CAST(CUSTOM_FIELD_VALUES:PAYMENTFORBEARANCEAMOUNT::VARCHAR AS NUMERIC(30,2)) as PAYMENT_FOR_BEARANCE_AMOUNT
,TRY_CAST(CUSTOM_FIELD_VALUES:BALLOONPAYMENT::VARCHAR AS NUMERIC(30,2)) as BALLOON_PAYMENT
,CUSTOM_FIELD_VALUES:MODTERMEXTENSION::VARCHAR as MOD_TERM_EXTENSION
,CUSTOM_FIELD_VALUES:PORTFOLIOID::VARCHAR as PORTFOLIO_ID_C
,CUSTOM_FIELD_VALUES:PORTFOLIONAME::VARCHAR as PORTFOLIO_NAME_C
,CUSTOM_FIELD_VALUES:BANKRUPTCYFLAG::VARCHAR as BANKRUPTCY_FLAG
,CUSTOM_FIELD_VALUES:BAKRUPTCYCHAPTER::VARCHAR as BANKRUPTCY_CHAPTER
,TRY_CAST(CUSTOM_FIELD_VALUES:SSAP2MODENDDATE::VARCHAR AS DATE) as SSAP2_MOD_END_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:TPRMODSTARTDATE::VARCHAR AS DATE) as TPR_MOD_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:TPRMODENDDATE::VARCHAR AS DATE) as TPR_MOD_END_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:PPRMODSTARTDATE::VARCHAR AS DATE) as PPR_MOD_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DSAPMODSTARTDATE::VARCHAR AS DATE) as DSAP_MOD_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DSAP1MODENDDATE::VARCHAR AS DATE) as DSAP1_MOD_END_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:DSAP2MODENDDATE::VARCHAR AS DATE) as DSAP2_MOD_END_DATE
,CUSTOM_FIELD_VALUES:SCRAFLAG::VARCHAR as SCRA_FLAG
,CUSTOM_FIELD_VALUES:CPDNEWDAY::VARCHAR as CPD_NEW_DAY
,CUSTOM_FIELD_VALUES:CLSAPR::VARCHAR as CLS_APR
,TRY_CAST(CUSTOM_FIELD_VALUES:CLSMATURITYDATE::VARCHAR AS DATE) as CLS_MATURITY_DATE
,CUSTOM_FIELD_VALUES:UTMCAMPAIGN::VARCHAR as UTM_CAMPAIGN
,CUSTOM_FIELD_VALUES:UTMMEDIUM::VARCHAR as  UTM_MEDIUM
,CUSTOM_FIELD_VALUES:UTMSOURCE::VARCHAR as  UTM_SOURCE
,CUSTOM_FIELD_VALUES:PLACEMENTSTATUS::VARCHAR AS PLACEMENT_STATUS
,TRY_CAST(CUSTOM_FIELD_VALUES:PLACEMENTSTATUSSTARTDATE::VARCHAR AS DATE) as PLACEMENT_STATUS_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:PLACEMENTSTATUSENDDATE::VARCHAR AS DATE) as PLACEMENT_STATUS_END_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:LPAPPLICATIONID::VARCHAR AS NUMERIC(30,0)) as LP_APPLICATION_ID
,TRY_CAST(CUSTOM_FIELD_VALUES:ORIGINATIONDATE::VARCHAR AS DATE) as CLS_ORIGINATION_DATE
,CUSTOM_FIELD_VALUES:MIGRATEDDATETIME::VARCHAR as MIGRATED_DATETIME
,CUSTOM_FIELD_VALUES:INCOMETYPE1::VARCHAR as INCOME_TYPE1
,CUSTOM_FIELD_VALUES:INCOMETYPE2::VARCHAR as INCOME_TYPE2
,CUSTOM_FIELD_VALUES:INCOMETYPE3::VARCHAR as INCOME_TYPE3
,CUSTOM_FIELD_VALUES:INCOMETYPE4::VARCHAR as INCOME_TYPE4
,CUSTOM_FIELD_VALUES:INCOMETYPE5::VARCHAR as INCOME_TYPE5
,CUSTOM_FIELD_VALUES:MODFLAG::VARCHAR AS MOD_FLAG
,CUSTOM_FIELD_VALUES:MODTYPE::VARCHAR AS MOD_TYPE
,TRY_CAST(CUSTOM_FIELD_VALUES:PREVIOUSMODIFICATION::VARCHAR AS int) AS PREVIOUS_MODIFICATION
,CUSTOM_FIELD_VALUES:MODREASON::VARCHAR as MOD_REASON
,TRY_CAST(CUSTOM_FIELD_VALUES:MODREQUESTDATE::VARCHAR AS DATE) AS MOD_REQUEST_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:MODPROCESSINGDATE::VARCHAR AS DATE) AS MOD_PROCESSING_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:MODSTARTDATE::VARCHAR AS DATE)  as MOD_START_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:MODENDDATE::VARCHAR AS DATE)  as MOD_END_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:NUMBERPAYMENTSDEFERRED::VARCHAR AS NUMERIC(12,0)) as NUMBER_PAYMENTS_DEFERRED
,TRY_CAST(CUSTOM_FIELD_VALUES:MODMATURITYDATE::VARCHAR AS DATE) as MOD_MATURITY_DATE
,TRY_CAST(CUSTOM_FIELD_VALUES:MODPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2)) as MOD_PAYMENT_AMOUNT
,TRY_CAST(CUSTOM_FIELD_VALUES:PPRPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2)) as PPR_PAYMENT_AMOUNT
,TRY_CAST(CUSTOM_FIELD_VALUES:TPRPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2)) as TPR_PAYMENT_AMOUNT
,CUSTOM_FIELD_VALUES:SETTLEMENTSTATUS::VARCHAR AS SETTLEMENTSTATUS
,TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTCOMPLETIONDATE::VARCHAR AS DATE) AS SETTLEMENTCOMPLETIONDATE
,CUSTOM_FIELD_VALUES:SETTLEMENTCOMPLETIONPERCENTAGE::VARCHAR AS SETTLEMENTCOMPLETIONPERCENTAGE
,CUSTOM_FIELD_VALUES:DEBTSETTLEMENTPAYMENTTERMS::VARCHAR AS DEBTSETTLEMENTPAYMENTTERMS
,CUSTOM_FIELD_VALUES:SETTLEMENTCOMPANY::VARCHAR AS SETTLEMENTCOMPANY
,CUSTOM_FIELD_VALUES:SETTLEMENTAGREEMENTAMOUNT::VARCHAR AS SETTLEMENTAGREEMENTAMOUNT
,CUSTOM_FIELD_VALUES:SETTLEMENTSTARTDATE::VARCHAR AS SETTLEMENTSTARTDATE
,CUSTOM_FIELD_VALUES:PROOFOFCLAIMREQUIRED::VARCHAR AS PROOFOFCLAIMREQUIRED
,CUSTOM_FIELD_VALUES:NUMBEROFDEBTSETTLEMENTPAYMENTSEXPECTED::VARCHAR AS NUMBEROFDEBTSETTLEMENTPAYMENTSEXPECTED
,CUSTOM_FIELD_VALUES:DSCCONTACT::VARCHAR AS DSCCONTACT
,CUSTOM_FIELD_VALUES:EXPECTEDSETTLEMENTENDDATE::VARCHAR AS EXPECTEDSETTLEMENTENDDATE
,CUSTOM_FIELD_VALUES:DONOTCALL::VARCHAR AS DONOTCALL
,CUSTOM_FIELD_VALUES:DONOTEMAIL::VARCHAR AS DONOTEMAIL
,CUSTOM_FIELD_VALUES:DONOTMAIL::VARCHAR AS DONOTMAIL
,CUSTOM_FIELD_VALUES:DONOTSMS::VARCHAR AS DONOTSMS
,TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPREQUESTDATE::VARCHAR AS DATE) as HARDSHIP_REQUEST_DATE
        from ARCA.FRESHSNOW.TRANSFORMED_CUSTOM_FIELD_ENTITY_CURRENT cs
        join ARCA.FRESHSNOW.LOAN_ENTITY_CURRENT le
            on cs.entity_id = le.id
        and cs.schema_name = ARCA.config.lms_schema()
        and le.schema_name = ARCA.config.lms_schema();