-- DI-1151: Upload Bounce 2025 Q2 Debt Sale Data
-- Upload debt sale population data to BUSINESS_INTELLIGENCE_DEV.CRON_STORE

-- Create table for Bounce 2025 Q2 Debt Sale CSV upload data (all records)
-- NOTE: This is separate from the main BOUNCE_DEBT_SALE_Q2_2025_SALE table created in DI-1141
CREATE OR REPLACE TABLE BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE_CSV_UPLOAD (
    ASSIGNMENT_DATE VARCHAR,
    STATUS VARCHAR,
    BATCH VARCHAR,
    PRODUCT VARCHAR,
    ORIGINAL_CREDITOR VARCHAR,
    ACCOUNT_PUBLIC_ID VARCHAR,
    EXTERNAL_ACCOUNT_ID VARCHAR,
    CREDITOR_RECALLED VARCHAR,
    HAS_VALID_SSN VARCHAR,
    HAS_USER_NAME VARCHAR,
    HAS_EMAIL VARCHAR,
    HAS_PHONE VARCHAR,
    HAS_ADDRESS VARCHAR,
    NO_ORIGINATION_DATE VARCHAR,
    IS_DECEASED VARCHAR,
    IS_BANKRUPTCY VARCHAR,
    USER_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CHARGE_OFF_AMOUNT VARCHAR,
    CHARGE_OFF_DATE VARCHAR,
    LAST_PAYMENT_AMOUNT VARCHAR,
    LAST_PAYMENT_DATE VARCHAR,
    FACE_VALUE VARCHAR
);

-- Create selected population table (status = 'Included' only)
-- NOTE: This references the CSV upload table, not the main DI-1141 analysis table
CREATE OR REPLACE TABLE BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE_CSV_SELECTED (
    LOANID VARCHAR,
    PORTFOLIONAME VARCHAR,
    UNPAIDBALANCEDUE VARCHAR
);

-- Create file format for CSV upload
CREATE OR REPLACE FILE FORMAT BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
NULL_IF = ('', 'NULL', 'null');