-- DI-1151: Credit Reporting List for Bounce 2025 Q2 Debt Sale
-- FINAL VERSION: Uses SELECTED table as base with main table join

SET START_DATE = '2025-08-06';

-- Credit_Reporting_File_Bounce_2025_Q2_SALE
SELECT UPPER(ds.LOANID) as loan_id,
       UPPER(ds.FIRSTNAME) as first_name,
       UPPER(ds.LASTNAME) as last_name,
       $START_DATE as PLACEMENT_STATUS_STARTDATE
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE_SELECTED sel
INNER JOIN BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE ds
    ON sel.LOANID = ds.LOANID;