-- ============================================================================
-- TABLE-BASED APPROACH: TBL_ORDER_ANALYTICS_MULTI_GRAIN
-- With stored procedure and task for scheduled refresh
-- Target Schema: ANALYTICS.DEVELOPMENT (change to PRODUCTION when ready)
-- ============================================================================

-- ============================================================================
-- STEP 1: CREATE THE TABLE (Initial Load)
-- ============================================================================
CREATE OR REPLACE TABLE ANALYTICS.DEVELOPMENT.TBL_ORDER_ANALYTICS_MULTI_GRAIN AS

WITH order_metrics AS (
    SELECT
        L_ORDERKEY,
        SUM(L_EXTENDEDPRICE) AS ORDER_TOTAL,
        COUNT(*) AS ORDER_LINE_COUNT,
        AVG(L_EXTENDEDPRICE) AS ORDER_AVG_LINE_VALUE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
    GROUP BY L_ORDERKEY
),

customer_metrics AS (
    SELECT
        o.O_CUSTKEY,
        SUM(o.O_TOTALPRICE) AS CUSTOMER_LIFETIME_VALUE,
        COUNT(DISTINCT o.O_ORDERKEY) AS CUSTOMER_TOTAL_ORDERS,
        AVG(o.O_TOTALPRICE) AS CUSTOMER_AVG_ORDER_VALUE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS o
    WHERE o.O_ORDERSTATUS = 'F'
    GROUP BY o.O_CUSTKEY
),

regional_totals AS (
    SELECT
        r.R_REGIONKEY,
        r.R_NAME AS REGION_NAME,
        SUM(o.O_TOTALPRICE) AS REGIONAL_TOTAL_REVENUE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS o
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
    WHERE o.O_ORDERSTATUS = 'F'
    GROUP BY r.R_REGIONKEY, r.R_NAME
),

customer_rankings AS (
    SELECT
        c.C_CUSTKEY,
        n.N_REGIONKEY,
        cm.CUSTOMER_LIFETIME_VALUE,
        rt.REGIONAL_TOTAL_REVENUE,
        RANK() OVER (PARTITION BY n.N_REGIONKEY ORDER BY cm.CUSTOMER_LIFETIME_VALUE DESC) AS CUSTOMER_RANK_IN_REGION,
        ROUND(cm.CUSTOMER_LIFETIME_VALUE / NULLIF(rt.REGIONAL_TOTAL_REVENUE, 0) * 100, 6) AS CUSTOMER_PCT_OF_REGIONAL_REVENUE
    FROM customer_metrics cm
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER c ON cm.O_CUSTKEY = c.C_CUSTKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
    JOIN regional_totals rt ON n.N_REGIONKEY = rt.R_REGIONKEY
)

SELECT
    l.L_ORDERKEY,
    l.L_LINENUMBER,
    l.L_PARTKEY,
    l.L_SUPPKEY,
    l.L_QUANTITY,
    l.L_EXTENDEDPRICE,
    l.L_DISCOUNT,
    l.L_TAX,
    l.L_RETURNFLAG,
    l.L_LINESTATUS,
    l.L_SHIPDATE,
    l.L_COMMITDATE,
    l.L_RECEIPTDATE,
    l.L_SHIPINSTRUCT,
    l.L_SHIPMODE,
    p.P_NAME AS PART_NAME,
    p.P_BRAND AS PART_BRAND,
    p.P_TYPE AS PART_TYPE,
    p.P_CONTAINER AS PART_CONTAINER,
    s.S_NAME AS SUPPLIER_NAME,
    sn.N_NAME AS SUPPLIER_NATION,
    o.O_ORDERDATE,
    o.O_ORDERSTATUS,
    o.O_ORDERPRIORITY,
    om.ORDER_TOTAL,
    om.ORDER_LINE_COUNT,
    om.ORDER_AVG_LINE_VALUE,
    c.C_CUSTKEY,
    c.C_NAME AS CUSTOMER_NAME,
    c.C_MKTSEGMENT AS CUSTOMER_SEGMENT,
    cm.CUSTOMER_LIFETIME_VALUE,
    cm.CUSTOMER_TOTAL_ORDERS,
    cm.CUSTOMER_AVG_ORDER_VALUE,
    n.N_NAME AS NATION_NAME,
    r.R_NAME AS REGION_NAME,
    cr.CUSTOMER_RANK_IN_REGION,
    cr.CUSTOMER_PCT_OF_REGIONAL_REVENUE,
    CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM l
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS o ON l.L_ORDERKEY = o.O_ORDERKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART p ON l.L_PARTKEY = p.P_PARTKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER s ON l.L_SUPPKEY = s.S_SUPPKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION sn ON s.S_NATIONKEY = sn.N_NATIONKEY
INNER JOIN order_metrics om ON l.L_ORDERKEY = om.L_ORDERKEY
INNER JOIN customer_metrics cm ON o.O_CUSTKEY = cm.O_CUSTKEY
INNER JOIN customer_rankings cr ON c.C_CUSTKEY = cr.C_CUSTKEY
WHERE o.O_ORDERSTATUS = 'F';

-- Add comment
COMMENT ON TABLE ANALYTICS.DEVELOPMENT.TBL_ORDER_ANALYTICS_MULTI_GRAIN IS
'Multi-grain order analytics table. Refreshed via SP_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN. Check REFRESH_TIMESTAMP for last update.';


-- ============================================================================
-- STEP 2: CREATE THE STORED PROCEDURE (Refresh Logic)
-- ============================================================================
CREATE OR REPLACE PROCEDURE ANALYTICS.DEVELOPMENT.SP_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Use CREATE OR REPLACE to atomically swap the table
    -- This avoids downtime compared to TRUNCATE + INSERT
    CREATE OR REPLACE TABLE ANALYTICS.DEVELOPMENT.TBL_ORDER_ANALYTICS_MULTI_GRAIN AS

    WITH order_metrics AS (
        SELECT
            L_ORDERKEY,
            SUM(L_EXTENDEDPRICE) AS ORDER_TOTAL,
            COUNT(*) AS ORDER_LINE_COUNT,
            AVG(L_EXTENDEDPRICE) AS ORDER_AVG_LINE_VALUE
        FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
        GROUP BY L_ORDERKEY
    ),

    customer_metrics AS (
        SELECT
            o.O_CUSTKEY,
            SUM(o.O_TOTALPRICE) AS CUSTOMER_LIFETIME_VALUE,
            COUNT(DISTINCT o.O_ORDERKEY) AS CUSTOMER_TOTAL_ORDERS,
            AVG(o.O_TOTALPRICE) AS CUSTOMER_AVG_ORDER_VALUE
        FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS o
        WHERE o.O_ORDERSTATUS = 'F'
        GROUP BY o.O_CUSTKEY
    ),

    regional_totals AS (
        SELECT
            r.R_REGIONKEY,
            r.R_NAME AS REGION_NAME,
            SUM(o.O_TOTALPRICE) AS REGIONAL_TOTAL_REVENUE
        FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS o
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
        WHERE o.O_ORDERSTATUS = 'F'
        GROUP BY r.R_REGIONKEY, r.R_NAME
    ),

    customer_rankings AS (
        SELECT
            c.C_CUSTKEY,
            n.N_REGIONKEY,
            cm.CUSTOMER_LIFETIME_VALUE,
            rt.REGIONAL_TOTAL_REVENUE,
            RANK() OVER (PARTITION BY n.N_REGIONKEY ORDER BY cm.CUSTOMER_LIFETIME_VALUE DESC) AS CUSTOMER_RANK_IN_REGION,
            ROUND(cm.CUSTOMER_LIFETIME_VALUE / NULLIF(rt.REGIONAL_TOTAL_REVENUE, 0) * 100, 6) AS CUSTOMER_PCT_OF_REGIONAL_REVENUE
        FROM customer_metrics cm
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER c ON cm.O_CUSTKEY = c.C_CUSTKEY
        JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
        JOIN regional_totals rt ON n.N_REGIONKEY = rt.R_REGIONKEY
    )

    SELECT
        l.L_ORDERKEY,
        l.L_LINENUMBER,
        l.L_PARTKEY,
        l.L_SUPPKEY,
        l.L_QUANTITY,
        l.L_EXTENDEDPRICE,
        l.L_DISCOUNT,
        l.L_TAX,
        l.L_RETURNFLAG,
        l.L_LINESTATUS,
        l.L_SHIPDATE,
        l.L_COMMITDATE,
        l.L_RECEIPTDATE,
        l.L_SHIPINSTRUCT,
        l.L_SHIPMODE,
        p.P_NAME AS PART_NAME,
        p.P_BRAND AS PART_BRAND,
        p.P_TYPE AS PART_TYPE,
        p.P_CONTAINER AS PART_CONTAINER,
        s.S_NAME AS SUPPLIER_NAME,
        sn.N_NAME AS SUPPLIER_NATION,
        o.O_ORDERDATE,
        o.O_ORDERSTATUS,
        o.O_ORDERPRIORITY,
        om.ORDER_TOTAL,
        om.ORDER_LINE_COUNT,
        om.ORDER_AVG_LINE_VALUE,
        c.C_CUSTKEY,
        c.C_NAME AS CUSTOMER_NAME,
        c.C_MKTSEGMENT AS CUSTOMER_SEGMENT,
        cm.CUSTOMER_LIFETIME_VALUE,
        cm.CUSTOMER_TOTAL_ORDERS,
        cm.CUSTOMER_AVG_ORDER_VALUE,
        n.N_NAME AS NATION_NAME,
        r.R_NAME AS REGION_NAME,
        cr.CUSTOMER_RANK_IN_REGION,
        cr.CUSTOMER_PCT_OF_REGIONAL_REVENUE,
        CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM l
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS o ON l.L_ORDERKEY = o.O_ORDERKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART p ON l.L_PARTKEY = p.P_PARTKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER s ON l.L_SUPPKEY = s.S_SUPPKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION sn ON s.S_NATIONKEY = sn.N_NATIONKEY
    INNER JOIN order_metrics om ON l.L_ORDERKEY = om.L_ORDERKEY
    INNER JOIN customer_metrics cm ON o.O_CUSTKEY = cm.O_CUSTKEY
    INNER JOIN customer_rankings cr ON c.C_CUSTKEY = cr.C_CUSTKEY
    WHERE o.O_ORDERSTATUS = 'F';

    RETURN 'Table refreshed successfully at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;


-- ============================================================================
-- STEP 3: CREATE THE TASK (Scheduled Refresh)
-- ============================================================================
-- Daily refresh at 2 AM UTC (adjust schedule as needed)
CREATE OR REPLACE TASK ANALYTICS.DEVELOPMENT.TASK_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN
    WAREHOUSE = COMPUTE_EXTRA_SMALL
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
    COMMENT = 'Daily refresh of TBL_ORDER_ANALYTICS_MULTI_GRAIN at 2 AM UTC'
AS
    CALL ANALYTICS.DEVELOPMENT.SP_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN();


-- ============================================================================
-- STEP 4: ENABLE THE TASK (Run after creating all objects)
-- ============================================================================
-- Tasks are created in SUSPENDED state by default - enable when ready
ALTER TASK ANALYTICS.DEVELOPMENT.TASK_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN RESUME;


-- ============================================================================
-- USEFUL COMMANDS
-- ============================================================================
-- Check task status:
-- SHOW TASKS IN SCHEMA ANALYTICS.DEVELOPMENT;

-- View task history:
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
-- WHERE NAME = 'TASK_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN' ORDER BY SCHEDULED_TIME DESC;

-- Manually run the refresh:
-- CALL ANALYTICS.DEVELOPMENT.SP_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN();

-- Suspend the task:
-- ALTER TASK ANALYTICS.DEVELOPMENT.TASK_REFRESH_ORDER_ANALYTICS_MULTI_GRAIN SUSPEND;

-- Check last refresh time:
-- SELECT MAX(REFRESH_TIMESTAMP) FROM ANALYTICS.DEVELOPMENT.TBL_ORDER_ANALYTICS_MULTI_GRAIN;
