-- Detailed Column Differences

-- Columns missing in FRESHSNOW
SELECT 
    'MISSING IN FRESHSNOW' as STATUS,
    COLUMN_NAME,
    DATA_TYPE as DATA_STORE_TYPE
FROM BUSINESS_INTELLIGENCE.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'DATA_STORE' 
AND TABLE_NAME = 'VW_PLAID_TRANSACTION_DETAIL'
AND COLUMN_NAME NOT IN (
    SELECT COLUMN_NAME 
    FROM DEVELOPMENT.INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = 'FRESHSNOW' 
    AND TABLE_NAME = 'VW_OSCILAR_PLAID_TRANSACTION_DETAIL'
)

UNION ALL

-- Columns new in FRESHSNOW
SELECT 
    'NEW IN FRESHSNOW' as STATUS,
    COLUMN_NAME,
    DATA_TYPE as FRESHSNOW_TYPE
FROM DEVELOPMENT.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'FRESHSNOW' 
AND TABLE_NAME = 'VW_OSCILAR_PLAID_TRANSACTION_DETAIL'
AND COLUMN_NAME NOT IN (
    SELECT COLUMN_NAME 
    FROM BUSINESS_INTELLIGENCE.INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = 'DATA_STORE' 
    AND TABLE_NAME = 'VW_PLAID_TRANSACTION_DETAIL'
)
ORDER BY STATUS, COLUMN_NAME;