-- Create a sample table from FRESHSNOW view for faster QC queries
-- Using a smaller sample to avoid timeout
CREATE OR REPLACE TABLE DEVELOPMENT.FRESHSNOW.TEMP_OSCILAR_PLAID_SAMPLE AS
SELECT *
FROM DEVELOPMENT.FRESHSNOW.VW_OSCILAR_PLAID_TRANSACTION_DETAIL
LIMIT 10000;