-- Approach 2: Create a materialized version using Snowflake Tasks
-- This runs during off-peak hours to avoid timeout

-- Create the target table structure first
CREATE TABLE IF NOT EXISTS DEVELOPMENT.FRESHSNOW.MATERIALIZED_OSCILAR_PLAID_DETAIL
LIKE DEVELOPMENT.FRESHSNOW.VW_OSCILAR_PLAID_TRANSACTION_DETAIL;

-- Create a task to populate it incrementally
CREATE OR REPLACE TASK DEVELOPMENT.FRESHSNOW.MATERIALIZE_OSCILAR_PLAID_TASK
  WAREHOUSE = BUSINESS_INTELLIGENCE_WH
  SCHEDULE = 'USING CRON 0 2 * * * America/Los_Angeles'  -- 2 AM PST daily
AS
  INSERT OVERWRITE INTO DEVELOPMENT.FRESHSNOW.MATERIALIZED_OSCILAR_PLAID_DETAIL
  SELECT * FROM DEVELOPMENT.FRESHSNOW.VW_OSCILAR_PLAID_TRANSACTION_DETAIL;

-- To run it manually once:
-- ALTER TASK DEVELOPMENT.FRESHSNOW.MATERIALIZE_OSCILAR_PLAID_TASK RESUME;
-- EXECUTE TASK DEVELOPMENT.FRESHSNOW.MATERIALIZE_OSCILAR_PLAID_TASK;