-- Data Alignment QC Query
-- Comparing matching columns between DATA_STORE and FRESHSNOW views
-- Using a sample of records for performance

WITH matching_columns AS (
    -- Get only columns that exist in both views
    SELECT COLUMN_NAME
    FROM BUSINESS_INTELLIGENCE.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'DATA_STORE'
    AND TABLE_NAME = 'VW_PLAID_TRANSACTION_DETAIL'
    INTERSECT
    SELECT COLUMN_NAME
    FROM DEVELOPMENT.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'FRESHSNOW'
    AND TABLE_NAME = 'VW_OSCILAR_PLAID_TRANSACTION_DETAIL'
),
-- Sample from DATA_STORE view
data_store_sample AS (
    SELECT *
    FROM BUSINESS_INTELLIGENCE.DATA_STORE.VW_PLAID_TRANSACTION_DETAIL
    WHERE LEAD_ID IS NOT NULL
    LIMIT 1000
),
-- Sample from FRESHSNOW using specific columns to avoid timeout
freshsnow_sample AS (
    SELECT 
        RECORD_CREATE_DATETIME,
        LEAD_GUID,
        LEAD_ID,
        MEMBER_ID,
        PLAID_REQUEST_ID,
        TOTAL_TRANSACTIONS,
        SCHEMA_VERSION,
        PLAID_CREATE_DATE,
        ACCOUNT_INDEX,
        ACCOUNT_ID,
        TRANSACTION_AUTHORIZED_DATE,
        TRANSACTION_CATEGORY,
        TRANSACTION_CATEGORY_ID,
        TRANSACTION_DATE,
        TRANSACTION_ISO_CURRENCY_CODE,
        TRANSACTION_LOCATION,
        TRANSACTION_MERCHANT_NAME,
        TRANSACTION_NAME,
        TRANSACTION_ORIGINAL_DESCRIPTION,
        TRANSACTION_PAYMENT_CHANNEL,
        TRANSACTION_PAYMENT_META,
        TRANSACTION_PENDING,
        TRANSACTION_PENDING_TRANSACTION_ID,
        TRANSACTION_CODE,
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        TRANSACTION_UNOFFICIAL_CURRENCY_CODE
    FROM DEVELOPMENT.FRESHSNOW.VW_OSCILAR_PLAID_TRANSACTION_DETAIL
    WHERE LEAD_ID IS NOT NULL
    LIMIT 1000
)
-- Compare key metrics
SELECT 
    'Row Count Comparison' AS QC_CHECK,
    (SELECT COUNT(*) FROM data_store_sample) AS DATA_STORE_COUNT,
    (SELECT COUNT(*) FROM freshsnow_sample) AS FRESHSNOW_COUNT,
    NULL AS DATA_STORE_VALUE,
    NULL AS FRESHSNOW_VALUE,
    NULL AS MATCH_STATUS

UNION ALL

-- Check distinct LEAD_ID counts
SELECT 
    'Distinct LEAD_ID Count' AS QC_CHECK,
    (SELECT COUNT(DISTINCT LEAD_ID) FROM data_store_sample) AS DATA_STORE_COUNT,
    (SELECT COUNT(DISTINCT LEAD_ID) FROM freshsnow_sample) AS FRESHSNOW_COUNT,
    NULL AS DATA_STORE_VALUE,
    NULL AS FRESHSNOW_VALUE,
    CASE 
        WHEN (SELECT COUNT(DISTINCT LEAD_ID) FROM data_store_sample) = 
             (SELECT COUNT(DISTINCT LEAD_ID) FROM freshsnow_sample) 
        THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS MATCH_STATUS

UNION ALL

-- Check distinct MEMBER_ID counts
SELECT 
    'Distinct MEMBER_ID Count' AS QC_CHECK,
    (SELECT COUNT(DISTINCT MEMBER_ID) FROM data_store_sample) AS DATA_STORE_COUNT,
    (SELECT COUNT(DISTINCT MEMBER_ID) FROM freshsnow_sample) AS FRESHSNOW_COUNT,
    NULL AS DATA_STORE_VALUE,
    NULL AS FRESHSNOW_VALUE,
    CASE 
        WHEN (SELECT COUNT(DISTINCT MEMBER_ID) FROM data_store_sample) = 
             (SELECT COUNT(DISTINCT MEMBER_ID) FROM freshsnow_sample) 
        THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS MATCH_STATUS

UNION ALL

-- Check TOTAL_TRANSACTIONS alignment
SELECT 
    'TOTAL_TRANSACTIONS Sum' AS QC_CHECK,
    (SELECT SUM(TOTAL_TRANSACTIONS) FROM data_store_sample) AS DATA_STORE_COUNT,
    (SELECT SUM(TOTAL_TRANSACTIONS) FROM freshsnow_sample) AS FRESHSNOW_COUNT,
    NULL AS DATA_STORE_VALUE,
    NULL AS FRESHSNOW_VALUE,
    CASE 
        WHEN (SELECT SUM(TOTAL_TRANSACTIONS) FROM data_store_sample) = 
             (SELECT SUM(TOTAL_TRANSACTIONS) FROM freshsnow_sample) 
        THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS MATCH_STATUS

ORDER BY QC_CHECK;