-- Analyze DATA_STORE view to understand the data
-- This will help us understand what to look for in FRESHSNOW

-- Get sample records from DATA_STORE
WITH data_store_sample AS (
    SELECT 
        LEAD_ID,
        LEAD_GUID,
        MEMBER_ID,
        PLAID_REQUEST_ID,
        ACCOUNT_ID,
        TRANSACTION_ID,
        TRANSACTION_DATE,
        TRANSACTION_NAME,
        PLAID_CREATE_DATE,
        RECORD_CREATE_DATETIME
    FROM BUSINESS_INTELLIGENCE.DATA_STORE.VW_PLAID_TRANSACTION_DETAIL
    WHERE RECORD_CREATE_DATETIME >= DATEADD('day', -30, CURRENT_DATE())
    AND LEAD_ID IS NOT NULL
    LIMIT 10
)
SELECT 
    LEAD_ID,
    LEAD_GUID,
    MEMBER_ID,
    PLAID_REQUEST_ID,
    DATE(PLAID_CREATE_DATE) as PLAID_DATE,
    DATE(RECORD_CREATE_DATETIME) as RECORD_DATE,
    COUNT(DISTINCT ACCOUNT_ID) as ACCOUNT_COUNT,
    COUNT(DISTINCT TRANSACTION_ID) as TRANSACTION_COUNT
FROM data_store_sample
GROUP BY 1,2,3,4,5,6
ORDER BY RECORD_DATE DESC;