-- Detailed Comparison Query between DATA_STORE and FRESHSNOW views
-- Testing with specific LEAD_IDs for better performance

-- First, let's check if we can match records using a specific lead
WITH sample_leads AS (
    SELECT DISTINCT LEAD_ID 
    FROM BUSINESS_INTELLIGENCE.DATA_STORE.VW_PLAID_TRANSACTION_DETAIL
    WHERE LEAD_ID IS NOT NULL
    LIMIT 5
),
data_store_records AS (
    SELECT 
        LEAD_ID,
        LEAD_GUID,
        MEMBER_ID,
        PLAID_REQUEST_ID,
        COUNT(*) as transaction_count,
        SUM(CAST(TOTAL_TRANSACTIONS AS INT)) as total_transactions_sum,
        MIN(PLAID_CREATE_DATE) as min_plaid_date,
        MAX(PLAID_CREATE_DATE) as max_plaid_date
    FROM BUSINESS_INTELLIGENCE.DATA_STORE.VW_PLAID_TRANSACTION_DETAIL
    WHERE LEAD_ID IN (SELECT LEAD_ID FROM sample_leads)
    GROUP BY 1,2,3,4
)
SELECT 
    'Sample Lead IDs from DATA_STORE' as description,
    LEAD_ID,
    LEAD_GUID,
    MEMBER_ID,
    transaction_count,
    total_transactions_sum
FROM data_store_records
ORDER BY LEAD_ID
LIMIT 10;

-- Second query to check schema differences in detail
WITH column_comparison AS (
    SELECT 
        ds.COLUMN_NAME,
        ds.DATA_TYPE as DS_TYPE,
        ds.CHARACTER_MAXIMUM_LENGTH as DS_LENGTH,
        ds.NUMERIC_PRECISION as DS_PRECISION,
        fs.DATA_TYPE as FS_TYPE,
        fs.CHARACTER_MAXIMUM_LENGTH as FS_LENGTH,
        fs.NUMERIC_PRECISION as FS_PRECISION,
        CASE 
            WHEN ds.COLUMN_NAME IS NULL THEN 'NEW IN FRESHSNOW'
            WHEN fs.COLUMN_NAME IS NULL THEN 'MISSING IN FRESHSNOW'
            WHEN ds.DATA_TYPE = fs.DATA_TYPE 
                AND (ds.CHARACTER_MAXIMUM_LENGTH = fs.CHARACTER_MAXIMUM_LENGTH OR (ds.CHARACTER_MAXIMUM_LENGTH IS NULL AND fs.CHARACTER_MAXIMUM_LENGTH IS NULL))
                AND (ds.NUMERIC_PRECISION = fs.NUMERIC_PRECISION OR (ds.NUMERIC_PRECISION IS NULL AND fs.NUMERIC_PRECISION IS NULL))
            THEN 'EXACT MATCH'
            WHEN ds.DATA_TYPE = fs.DATA_TYPE THEN 'TYPE MATCH, SIZE DIFFERS'
            ELSE 'TYPE MISMATCH'
        END as COMPARISON_STATUS
    FROM 
        (SELECT * FROM BUSINESS_INTELLIGENCE.INFORMATION_SCHEMA.COLUMNS 
         WHERE TABLE_SCHEMA = 'DATA_STORE' AND TABLE_NAME = 'VW_PLAID_TRANSACTION_DETAIL') ds
    FULL OUTER JOIN 
        (SELECT * FROM DEVELOPMENT.INFORMATION_SCHEMA.COLUMNS 
         WHERE TABLE_SCHEMA = 'FRESHSNOW' AND TABLE_NAME = 'VW_OSCILAR_PLAID_TRANSACTION_DETAIL') fs
    ON ds.COLUMN_NAME = fs.COLUMN_NAME
)
SELECT 
    COMPARISON_STATUS,
    COUNT(*) as column_count,
    LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_NAME) as columns
FROM column_comparison
GROUP BY COMPARISON_STATUS
ORDER BY COMPARISON_STATUS;