-- Schema Summary Comparison

-- Summary of schema differences
WITH column_comparison AS (
    SELECT 
        ds.COLUMN_NAME,
        ds.DATA_TYPE as DS_TYPE,
        fs.DATA_TYPE as FS_TYPE,
        CASE 
            WHEN ds.COLUMN_NAME IS NULL THEN 'NEW IN FRESHSNOW'
            WHEN fs.COLUMN_NAME IS NULL THEN 'MISSING IN FRESHSNOW'
            WHEN ds.DATA_TYPE = fs.DATA_TYPE THEN 'MATCH'
            ELSE 'TYPE MISMATCH'
        END as STATUS
    FROM 
        (SELECT COLUMN_NAME, DATA_TYPE FROM BUSINESS_INTELLIGENCE.INFORMATION_SCHEMA.COLUMNS 
         WHERE TABLE_SCHEMA = 'DATA_STORE' AND TABLE_NAME = 'VW_PLAID_TRANSACTION_DETAIL') ds
    FULL OUTER JOIN 
        (SELECT COLUMN_NAME, DATA_TYPE FROM DEVELOPMENT.INFORMATION_SCHEMA.COLUMNS 
         WHERE TABLE_SCHEMA = 'FRESHSNOW' AND TABLE_NAME = 'VW_OSCILAR_PLAID_TRANSACTION_DETAIL') fs
    ON ds.COLUMN_NAME = fs.COLUMN_NAME
)
SELECT 
    STATUS,
    COUNT(*) as COLUMN_COUNT
FROM column_comparison
GROUP BY STATUS
ORDER BY STATUS;