-- Schema Comparison Query for VW_PLAID_TRANSACTION_DETAIL views
-- Comparing BUSINESS_INTELLIGENCE.DATA_STORE vs DEVELOPMENT.FRESHSNOW

-- Get column information for both views
WITH data_store_columns AS (
    SELECT 
        COLUMN_NAME,
        DATA_TYPE,
        ORDINAL_POSITION,
        IS_NULLABLE,
        NUMERIC_PRECISION,
        NUMERIC_SCALE
    FROM BUSINESS_INTELLIGENCE.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'DATA_STORE'
    AND TABLE_NAME = 'VW_PLAID_TRANSACTION_DETAIL'
),
freshsnow_columns AS (
    SELECT 
        COLUMN_NAME,
        DATA_TYPE,
        ORDINAL_POSITION,
        IS_NULLABLE,
        NUMERIC_PRECISION,
        NUMERIC_SCALE
    FROM DEVELOPMENT.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'FRESHSNOW'
    AND TABLE_NAME = 'VW_OSCILAR_PLAID_TRANSACTION_DETAIL'
)
-- Compare schemas
SELECT 
    COALESCE(ds.COLUMN_NAME, fs.COLUMN_NAME) AS COLUMN_NAME,
    ds.DATA_TYPE AS DS_DATA_TYPE,
    fs.DATA_TYPE AS FS_DATA_TYPE,
    ds.ORDINAL_POSITION AS DS_POSITION,
    fs.ORDINAL_POSITION AS FS_POSITION,
    CASE 
        WHEN ds.COLUMN_NAME IS NULL THEN 'MISSING IN DATA_STORE'
        WHEN fs.COLUMN_NAME IS NULL THEN 'MISSING IN FRESHSNOW'
        WHEN ds.DATA_TYPE != fs.DATA_TYPE THEN 'TYPE MISMATCH'
        ELSE 'MATCH'
    END AS STATUS
FROM data_store_columns ds
FULL OUTER JOIN freshsnow_columns fs
    ON ds.COLUMN_NAME = fs.COLUMN_NAME
ORDER BY 
    COALESCE(ds.ORDINAL_POSITION, 999), 
    COALESCE(fs.ORDINAL_POSITION, 999);