/*
================================================================================
DI-1211 QC: Record Counts and Distribution
================================================================================
*/

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
USE ROLE BUSINESS_INTELLIGENCE_PII;

--1.1: Total Placement Status Distribution
SELECT
    lcs.PLACEMENT_STATUS,
    COUNT(DISTINCT vl.LOAN_ID) AS LOAN_COUNT
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN vl
INNER JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT lcs
    ON vl.LOAN_ID = lcs.LOAN_ID
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT lds
    ON vl.LOAN_ID = lds.LOAN_ID
WHERE vl.CHARGE_OFF_DATE IS NOT NULL
    AND lcs.PLACEMENT_STATUS IN ('Bounce', 'Resurgent')
    AND (
        lds.SETTLEMENTSTATUS IN ('Active', 'Complete')
        OR lds.CURRENT_STATUS IN ('Active', 'Complete')
    )
GROUP BY lcs.PLACEMENT_STATUS
ORDER BY lcs.PLACEMENT_STATUS;

--1.2: Settlement Status Breakdown
SELECT
    COALESCE(lds.SETTLEMENTSTATUS, lds.CURRENT_STATUS, 'None') AS SETTLEMENT_STATUS,
    COUNT(DISTINCT vl.LOAN_ID) AS LOAN_COUNT
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN vl
INNER JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT lcs
    ON vl.LOAN_ID = lcs.LOAN_ID
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT lds
    ON vl.LOAN_ID = lds.LOAN_ID
WHERE vl.CHARGE_OFF_DATE IS NOT NULL
    AND lcs.PLACEMENT_STATUS IN ('Bounce', 'Resurgent')
    AND (
        lds.SETTLEMENTSTATUS IN ('Active', 'Complete')
        OR lds.CURRENT_STATUS IN ('Active', 'Complete')
    )
GROUP BY SETTLEMENT_STATUS
ORDER BY LOAN_COUNT DESC;

--1.3: Charge-Off Date Range
SELECT
    MIN(vl.CHARGE_OFF_DATE) AS EARLIEST_CHARGEOFF,
    MAX(vl.CHARGE_OFF_DATE) AS LATEST_CHARGEOFF,
    COUNT(DISTINCT vl.LOAN_ID) AS TOTAL_LOANS
FROM BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN vl
INNER JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT lcs
    ON vl.LOAN_ID = lcs.LOAN_ID
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN_DEBT_SETTLEMENT lds
    ON vl.LOAN_ID = lds.LOAN_ID
WHERE vl.CHARGE_OFF_DATE IS NOT NULL
    AND lcs.PLACEMENT_STATUS IN ('Bounce', 'Resurgent')
    AND (
        lds.SETTLEMENTSTATUS IN ('Active', 'Complete')
        OR lds.CURRENT_STATUS IN ('Active', 'Complete')
    );
