/*
================================================================================
DI-1211 QC: Placement Status Distribution
================================================================================
*/

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
USE ROLE BUSINESS_INTELLIGENCE;

--2.1: Placement Status Breakdown
SELECT
    PLACEMENT_STATUS,
    COUNT(*) AS LOAN_COUNT,
    SUM(TOTAL_PAYMENTS_POST_CHARGEOFF) AS TOTAL_PAYMENTS,
    AVG(TOTAL_PAYMENTS_POST_CHARGEOFF) AS AVG_PAYMENTS,
    SUM(CASE WHEN AUTOPAY_STATUS = 'Y' THEN 1 ELSE 0 END) AS AUTOPAY_COUNT,
    SUM(CASE WHEN FUTURE_SCHEDULED_PAYMENTS = 'Y' THEN 1 ELSE 0 END) AS FUTURE_PAYMENT_COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.DI_1211_PLACEMENT_DATA_QUALITY
GROUP BY PLACEMENT_STATUS
ORDER BY LOAN_COUNT DESC;

--2.2: Data Quality Issue Type Breakdown
SELECT
    PLACEMENT_STATUS,
    SUM(CASE WHEN TOTAL_PAYMENTS_POST_CHARGEOFF > 0 THEN 1 ELSE 0 END) AS HAS_POST_CHARGEOFF_PAYMENTS,
    SUM(CASE WHEN SETTLEMENT_STATUS IN ('Active', 'Complete') THEN 1 ELSE 0 END) AS HAS_SETTLEMENT,
    SUM(CASE WHEN AUTOPAY_STATUS = 'Y' THEN 1 ELSE 0 END) AS HAS_AUTOPAY,
    SUM(CASE WHEN FUTURE_SCHEDULED_PAYMENTS = 'Y' THEN 1 ELSE 0 END) AS HAS_FUTURE_PAYMENTS
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.DI_1211_PLACEMENT_DATA_QUALITY
GROUP BY PLACEMENT_STATUS;
