/*
================================================================================
DI-1211 QC: Settlement Status Breakdown
================================================================================
*/

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
USE ROLE BUSINESS_INTELLIGENCE;

--3.1: Settlement Status Distribution
SELECT
    SETTLEMENT_STATUS,
    PLACEMENT_STATUS,
    COUNT(*) AS LOAN_COUNT,
    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,
    SUM(SETTLEMENT_AMOUNT_PAID) AS TOTAL_AMOUNT_PAID
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.DI_1211_PLACEMENT_DATA_QUALITY
GROUP BY SETTLEMENT_STATUS, PLACEMENT_STATUS
ORDER BY LOAN_COUNT DESC;

--3.2: Payment Activity Summary
SELECT
    CASE
        WHEN TOTAL_PAYMENTS_POST_CHARGEOFF = 0 THEN '$0'
        WHEN TOTAL_PAYMENTS_POST_CHARGEOFF < 100 THEN '$1-$99'
        WHEN TOTAL_PAYMENTS_POST_CHARGEOFF < 500 THEN '$100-$499'
        WHEN TOTAL_PAYMENTS_POST_CHARGEOFF < 1000 THEN '$500-$999'
        WHEN TOTAL_PAYMENTS_POST_CHARGEOFF < 5000 THEN '$1,000-$4,999'
        ELSE '$5,000+'
    END AS PAYMENT_RANGE,
    COUNT(*) AS LOAN_COUNT,
    SUM(TOTAL_PAYMENTS_POST_CHARGEOFF) AS TOTAL_PAYMENTS
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.DI_1211_PLACEMENT_DATA_QUALITY
GROUP BY 1
ORDER BY
    CASE PAYMENT_RANGE
        WHEN '$0' THEN 1
        WHEN '$1-$99' THEN 2
        WHEN '$100-$499' THEN 3
        WHEN '$500-$999' THEN 4
        WHEN '$1,000-$4,999' THEN 5
        ELSE 6
    END;
