-- Test email_platform CSV header format
USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;

SELECT
    a.EVENT_DATE AS sent,
    a.JOB_ID,
    a.LIST_ID,
    a.BATCH_ID,
    a.SUBSCRIBER_ID,
    a.SUBSCRIBER_KEY,
    a.EMAIL_ID,
    a.EMAIL_NAME,
    a.SUBJECT,
    a.DERIVED_PAYOFFUID AS PAYOFFUID,
    b.LEGACY_LOAN_ID AS PAYOFFLOANID,
    a.EVENT_TYPE,
    a.CAMPAIGN
FROM BUSINESS_INTELLIGENCE.CRON_STORE.DSH_EMAIL_MONITORING_EVENTS a
INNER JOIN BUSINESS_INTELLIGENCE.DATA_STORE.MVW_LOAN_TAPE_DAILY_HISTORY b
    ON a.DERIVED_PAYOFFUID = b.PAYOFFUID
    AND DATE(a.EVENT_DATE) = DATEADD('day', 1, b.ASOFDATE)
JOIN cron_store.temp_target_payoff_uids tpl
    ON b.payoffuid = tpl.payoff_uid
WHERE DATE(a.EVENT_DATE) BETWEEN $q3_start_date AND $q3_end_date
    AND UPPER(a.CAMPAIGN) = UPPER('delinquent')
    AND UPPER(a.EVENT_TYPE) = UPPER('Sent')
ORDER BY a.EVENT_DATE, a.EMAIL_NAME;
