/***********************************************************************************************************************
DI-1131 PRODUCTION Email Dynamic Table Deployment Script - ULTIMATE OPTIMIZED WITH UNIVERSAL APP DATES
Date: 2025-08-21
Author: Kyle Chalmers

Purpose: Deploy ultimate optimized email lookup logic to PRODUCTION dynamic table using universal APPLICATION_STARTED_DATE from BRIDGE.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT
Target: BUSINESS_INTELLIGENCE.PII.DT_LKP_EMAIL_TO_PAYOFFUID_MATCH
Sources: Production ANALYTICS_PII tables + BRIDGE.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT

ULTIMATE OPTIMIZATIONS:
1. Removed REGEXP_REPLACE for IN-MIGRATION pattern
2. Consolidated duplicate subqueries using single email counting CTE
3. Combined similar window function logic
4. Simplified redundant UPPER() calls by doing it once
5. Uses APPLICATION_STARTED_DATE from VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT as universal start date for BOTH loans and non-loans
6. Optimized with TO_DATE for faster performance
***********************************************************************************************************************/

-- Drop and recreate the dynamic table with ultimate enhanced logic
CREATE OR REPLACE DYNAMIC TABLE BUSINESS_INTELLIGENCE.PII.DT_LKP_EMAIL_TO_PAYOFFUID_MATCH
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '12 hours'
AS

-- -- -- -- -- -- -- -- -- MEMBER PII BASE (HIGHEST PRIORITY) -- -- -- -- -- -- -- -- --
WITH MEMBER_EMAIL_COUNTS AS (
    -- Count loans per email once for reuse
    SELECT 
        UPPER(m.EMAIL) as EMAIL,
        COUNT(DISTINCT vl.LEAD_GUID) as LOAN_COUNT
    FROM BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII m
    INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN vl ON vl.MEMBER_ID = m.MEMBER_ID
    WHERE m.EMAIL IS NOT NULL
    GROUP BY UPPER(m.EMAIL)
),

MEMBER_BASE AS (
    -- Single scan of member data with universal application dates from LOS custom settings
    SELECT 
        UPPER(m.EMAIL) as EMAIL,
        vl.LEAD_GUID as PAYOFFUID,
        TRUE AS IS_LOAN,
        vl.LOAN_CLOSED_DATE AS END_DATE,
        vl.ORIGINATION_DATE,
        TRY_TO_TIMESTAMP(los.APPLICATION_STARTED_DATE)::DATE AS APPLICATION_STARTED_DATE,
        ec.LOAN_COUNT
    FROM BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII m
    INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN vl ON vl.MEMBER_ID = m.MEMBER_ID
    INNER JOIN MEMBER_EMAIL_COUNTS ec ON ec.EMAIL = UPPER(m.EMAIL)
    LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT los ON los.LEAD_GUID = vl.LEAD_GUID
    WHERE m.EMAIL IS NOT NULL
),

MEMBER_CONTACT_DATES AS (
    SELECT
        EMAIL,
        PAYOFFUID,
        IS_LOAN,
        LOAN_COUNT,
        CASE 
            WHEN LOAN_COUNT = 1 THEN NULL
            WHEN LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NOT NULL 
            THEN DATEADD('day', 1, LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)))
            WHEN LAG(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NOT NULL 
            THEN DATEADD('day', 1, LAG(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)))
            ELSE NULL
        END AS FIRST_POSSIBLE_CONTACT_DATE,
        CASE 
            WHEN LOAN_COUNT = 1 THEN NULL
            WHEN LEAD(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NOT NULL
            THEN END_DATE
            WHEN LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NULL
                 AND (END_DATE IS NOT NULL OR APPLICATION_STARTED_DATE IS NOT NULL)
            THEN COALESCE(END_DATE, APPLICATION_STARTED_DATE)
            ELSE NULL
        END AS LAST_POSSIBLE_CONTACT_DATE
    FROM MEMBER_BASE
),

FULL_LKP_EMAIL_LOAN_MATCHING_MEMBER AS (
    SELECT EMAIL, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
    FROM MEMBER_CONTACT_DATES
    WHERE LOAN_COUNT = 1
       OR IFNULL(FIRST_POSSIBLE_CONTACT_DATE,'1999-02-01') <> IFNULL(LAST_POSSIBLE_CONTACT_DATE,'1999-02-01')
),

-- -- -- -- -- -- -- -- -- APPLICATION PII BASE (MIDDLE PRIORITY) -- -- -- -- -- -- -- -- --
APP_EMAIL_COUNTS AS (
    -- Count applications per email, excluding already matched member emails
    SELECT 
        UPPER(a.EMAIL) as EMAIL,
        COUNT(DISTINCT a.LEAD_GUID) as APP_COUNT
    FROM BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_APPLICATION_PII a
    LEFT JOIN FULL_LKP_EMAIL_LOAN_MATCHING_MEMBER m ON m.EMAIL = UPPER(a.EMAIL)
    WHERE a.EMAIL IS NOT NULL AND m.EMAIL IS NULL
    GROUP BY UPPER(a.EMAIL)
),

APP_BASE AS (
    SELECT 
        UPPER(a.EMAIL) as EMAIL,
        a.LEAD_GUID as PAYOFFUID,
        IFF(vl.LEAD_GUID IS NULL, FALSE, TRUE) AS IS_LOAN,
        vl.LOAN_CLOSED_DATE AS END_DATE,
        vl.ORIGINATION_DATE,
        TRY_TO_TIMESTAMP(los.APPLICATION_STARTED_DATE)::DATE AS APPLICATION_STARTED_DATE,
        ac.APP_COUNT
    FROM BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_APPLICATION_PII a
    INNER JOIN APP_EMAIL_COUNTS ac ON ac.EMAIL = UPPER(a.EMAIL)
    LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN vl ON vl.LEAD_GUID = a.LEAD_GUID
    LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT los ON los.LEAD_GUID = a.LEAD_GUID
    WHERE a.EMAIL IS NOT NULL
),

APP_CONTACT_DATES AS (
    SELECT
        EMAIL,
        PAYOFFUID,
        IS_LOAN,
        APP_COUNT,
        CASE 
            WHEN APP_COUNT = 1 THEN NULL
            WHEN LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NOT NULL 
            THEN DATEADD('day', 1, LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)))
            WHEN LAG(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NOT NULL 
            THEN DATEADD('day', 1, LAG(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)))
            ELSE NULL
        END AS FIRST_POSSIBLE_CONTACT_DATE,
        CASE 
            WHEN APP_COUNT = 1 THEN NULL
            WHEN LEAD(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NOT NULL
            THEN COALESCE(END_DATE, APPLICATION_STARTED_DATE)
            WHEN LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, END_DATE)) IS NULL
                 AND (END_DATE IS NOT NULL OR APPLICATION_STARTED_DATE IS NOT NULL)
            THEN COALESCE(END_DATE, APPLICATION_STARTED_DATE)
            ELSE NULL
        END AS LAST_POSSIBLE_CONTACT_DATE
    FROM APP_BASE
    WHERE APP_COUNT = 1 OR (END_DATE IS NOT NULL OR ORIGINATION_DATE IS NOT NULL OR APPLICATION_STARTED_DATE IS NOT NULL)
),

FULL_LKP_EMAIL_LOAN_MATCHING_MEMBER_AND_APP AS (
    SELECT EMAIL, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
    FROM FULL_LKP_EMAIL_LOAN_MATCHING_MEMBER
    
    UNION 
    
    SELECT EMAIL, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
    FROM APP_CONTACT_DATES
    WHERE APP_COUNT = 1
       OR IFNULL(FIRST_POSSIBLE_CONTACT_DATE,'1999-02-01') <> IFNULL(LAST_POSSIBLE_CONTACT_DATE,'1999-02-01')
),

-- -- -- -- -- -- -- -- -- LEAD PII BASE (LOWEST PRIORITY) -- -- -- -- -- -- -- -- --
LEAD_BASE_FILTERED AS (
    -- Exclude already matched emails and prepare lead data
    SELECT 
        UPPER(l.EMAIL) AS EMAIL,
        l.LEAD_GUID AS PAYOFFUID,
        l.SSN
    FROM BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_LEAD_PII l
    LEFT JOIN FULL_LKP_EMAIL_LOAN_MATCHING_MEMBER_AND_APP ma ON ma.EMAIL = UPPER(l.EMAIL)
    WHERE l.EMAIL IS NOT NULL AND ma.EMAIL IS NULL
),

MOST_USED_EMAIL AS (
    SELECT SSN, EMAIL
    FROM (
        SELECT SSN, EMAIL, COUNT(*) AS TIMES_USED
        FROM LEAD_BASE_FILTERED
        WHERE EMAIL IS NOT NULL AND SSN IS NOT NULL
        GROUP BY SSN, EMAIL
    )
    QUALIFY DENSE_RANK() OVER (PARTITION BY SSN ORDER BY TIMES_USED DESC, EMAIL) = 1
),

LEAD_ENHANCED AS (
    SELECT 
        COALESCE(l.EMAIL, m.EMAIL) AS EMAIL,
        l.PAYOFFUID
    FROM LEAD_BASE_FILTERED l
    LEFT JOIN MOST_USED_EMAIL m ON l.SSN = m.SSN
),

LEAD_EMAIL_COUNTS AS (
    SELECT EMAIL, COUNT(DISTINCT PAYOFFUID) as LEAD_COUNT
    FROM LEAD_ENHANCED
    WHERE EMAIL IS NOT NULL
    GROUP BY EMAIL
),

LEAD_WITH_LOAN_INFO AS (
    SELECT 
        le.EMAIL,
        le.PAYOFFUID,
        IFF(vl.LEAD_GUID IS NULL, FALSE, TRUE) AS IS_LOAN,
        vl.ORIGINATION_DATE,
        vl.LOAN_CLOSED_DATE AS END_DATE,
        TRY_TO_TIMESTAMP(los.APPLICATION_STARTED_DATE)::DATE AS APPLICATION_STARTED_DATE,
        lc.LEAD_COUNT
    FROM LEAD_ENHANCED le
    INNER JOIN LEAD_EMAIL_COUNTS lc ON lc.EMAIL = le.EMAIL
    LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN vl ON vl.LEAD_GUID = le.PAYOFFUID
    LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOS_CUSTOM_LOAN_SETTINGS_CURRENT los ON los.LEAD_GUID = le.PAYOFFUID
),

LEAD_CONTACT_DATES AS (
    SELECT
        EMAIL,
        PAYOFFUID,
        IS_LOAN,
        LEAD_COUNT,
        CASE 
            WHEN LEAD_COUNT = 1 THEN NULL
            WHEN APPLICATION_STARTED_DATE IS NOT NULL 
                 AND LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, CURRENT_DATE)) IS NOT NULL
            THEN DATEADD('day', 1, LAG(END_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, CURRENT_DATE)))
            WHEN APPLICATION_STARTED_DATE IS NOT NULL 
                 AND LAG(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, CURRENT_DATE)) IS NOT NULL
            THEN DATEADD('day', 1, LAG(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, CURRENT_DATE)))
            ELSE NULL
        END AS FIRST_POSSIBLE_CONTACT_DATE,
        CASE 
            WHEN LEAD_COUNT = 1 THEN NULL
            WHEN END_DATE IS NOT NULL 
                 AND LEAD(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, CURRENT_DATE)) IS NOT NULL
            THEN END_DATE
            WHEN APPLICATION_STARTED_DATE IS NOT NULL
                 AND LEAD(APPLICATION_STARTED_DATE) OVER (PARTITION BY EMAIL ORDER BY COALESCE(APPLICATION_STARTED_DATE, CURRENT_DATE)) IS NOT NULL
            THEN APPLICATION_STARTED_DATE
            ELSE NULL
        END AS LAST_POSSIBLE_CONTACT_DATE
    FROM LEAD_WITH_LOAN_INFO
)

-- FINAL UNION QUERY
SELECT EMAIL, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE
FROM FULL_LKP_EMAIL_LOAN_MATCHING_MEMBER_AND_APP

UNION

SELECT EMAIL, PAYOFFUID, IS_LOAN, FIRST_POSSIBLE_CONTACT_DATE, LAST_POSSIBLE_CONTACT_DATE 
FROM LEAD_CONTACT_DATES
WHERE LEAD_COUNT = 1
   OR IFNULL(FIRST_POSSIBLE_CONTACT_DATE,'1999-02-01') <> IFNULL(LAST_POSSIBLE_CONTACT_DATE,'1999-02-01')
   OR (FIRST_POSSIBLE_CONTACT_DATE IS NULL AND LAST_POSSIBLE_CONTACT_DATE IS NULL);