-- Current Production Field Value Distribution Analysis
-- Analyzes existing 278 fields in ARCA.FRESHSNOW.VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
-- Shows count and percentage breakdown for each distinct value in every field (including NULLs)

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
--current_selected_prod_field_value_distribution_qc
WITH base_data AS (
    SELECT
        -- LOAN_ID and SETTINGS_ID (2 fields)
        COALESCE(TO_VARCHAR(le.id), 'NULL') AS LOAN_ID,
        COALESCE(TO_VARCHAR(cs.entity_id), 'NULL') AS SETTINGS_ID,

        -- PROCESSING AND BANKRUPTCY FIELDS (10 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PROCESSINGFEESPAID::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PROCESSING_FEES_PAID,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYCASENUMBER::VARCHAR, 'NULL') AS BANKRUPTCY_CASE_NUMBER,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYCOURTDISTRICT::VARCHAR, 'NULL') AS BANKRUPTCY_COURT_DISTRICT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYFILINGDATE::VARCHAR AS DATE)), 'NULL') AS BANKRUPTCY_FILING_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYVENDOR::VARCHAR, 'NULL') AS BANKRUPTCY_VENDOR,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWLOANAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS BANKRUPTCY_ORDERED_NEW_LOAN_AMOUNT,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWINTERESTRATE::VARCHAR, 'NULL') AS BANKRUPTCY_ORDERED_NEW_INTEREST_RATE,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNUMBEROFPAYMENTS::VARCHAR, 'NULL') AS BANKRUPTCY_ORDERED_NUMBER_OF_PAYMENTS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS BANKRUPTCY_ORDERED_NEW_PAYMENT_AMOUNT,
        COALESCE(CUSTOM_FIELD_VALUES:COMPLIANCECONDITIONCODE::VARCHAR, 'NULL') AS COMPLIANCE_CONDITION_CODE,

        -- REPOSSESSION FIELDS (10 fields)
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONREVIEWDECISION::VARCHAR, 'NULL') AS REPOSSESSION_REVIEW_DECISION,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYNAME::VARCHAR, 'NULL') AS REPOSSESSION_COMPANY_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYCONTACTNAME::VARCHAR, 'NULL') AS REPOSSESSION_COMPANY_CONTACT_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYPHONENUMBER::VARCHAR, 'NULL') AS REPOSSESSION_COMPANY_PHONE_NUMBER,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYEMAILADDRESS::VARCHAR, 'NULL') AS REPOSSESSION_COMPANY_EMAIL_ADDRESS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REPOSSESSIONMANAGERDECLINEDATE::VARCHAR AS DATE)), 'NULL') AS REPOSSESSION_MANAGER_DECLINE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCITY::VARCHAR, 'NULL') AS REPOSSESSION_CITY,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCOUNTY::VARCHAR, 'NULL') AS REPOSSESSION_COUNTY,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONSTATE::VARCHAR, 'NULL') AS REPOSSESSION_STATE,
        COALESCE(CUSTOM_FIELD_VALUES:REPOSSESSIONCASENUMBER::VARCHAR, 'NULL') AS REPOSSESSION_CASE_NUMBER,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REPOSSESSIONDATE::VARCHAR AS DATE)), 'NULL') AS REPOSSESSION_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:CUSTOMERREDEEMEDCOLLATERAL::VARCHAR, 'NULL') AS CUSTOMER_REDEEMED_COLLATERAL,

        -- CHARGE OFF AND DECEASED FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:COLLECTIBLECHARGEOFFDATE::VARCHAR AS DATE)), 'NULL') AS COLLECTIBLE_CHARGE_OFF_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDATE::VARCHAR AS DATE)), 'NULL') AS CHARGE_OFF_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEOFDEATH::VARCHAR AS DATE)), 'NULL') AS DATE_OF_DEATH,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DECEASEDNOTIFICATIONDATE::VARCHAR AS DATE)), 'NULL') AS DECEASED_NOTIFICATION_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BALANCEATTHETIMEOFDECEASEDNOTIFICATION::VARCHAR AS NUMERIC(30,2))), 'NULL') AS BALANCE_AT_THE_TIME_OF_DECEASED_NOTIFICATION,

        -- FRAUD FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDINVESTIGATIONRESULTS::VARCHAR, 'NULL') AS FRAUD_INVESTIGATION_RESULTS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:FRAUDCONFIRMEDDATE::VARCHAR AS DATE)), 'NULL') AS FRAUD_CONFIRMED_DATE,

        -- ATTORNEY FIELDS (11 fields)
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYRETAINED::VARCHAR, 'NULL') AS ATTORNEY_RETAINED,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYTYPE::VARCHAR, 'NULL') AS ATTORNEY_TYPE,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYNAME::VARCHAR, 'NULL') AS ATTORNEY_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:FIRMNAME::VARCHAR, 'NULL') AS FIRM_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYADDRESS::VARCHAR, 'NULL') AS ATTORNEY_ADDRESS,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYCITY::VARCHAR, 'NULL') AS ATTORNEY_CITY,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYSTATE::VARCHAR, 'NULL') AS ATTORNEY_STATE,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYZIP::VARCHAR, 'NULL') AS ATTORNEY_ZIP,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYPHONE::VARCHAR, 'NULL') AS ATTORNEY_PHONE,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYFAX::VARCHAR, 'NULL') AS ATTORNEY_FAX,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYEMAIL::VARCHAR, 'NULL') AS ATTORNEY_EMAIL,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:ATTORNEYRETAINEDDATE::VARCHAR AS DATE)), 'NULL') AS ATTORNEY_RETAINED_DATE,

        -- SCRA NOTIFICATION FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE1::VARCHAR AS DATE)), 'NULL') AS SCRA_NOTIFICATION_DATE1,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE2::VARCHAR AS DATE)), 'NULL') AS SCRA_NOTIFICATION_DATE2,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE3::VARCHAR AS DATE)), 'NULL') AS SCRA_NOTIFICATION_DATE3,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE4::VARCHAR AS DATE)), 'NULL') AS SCRA_NOTIFICATION_DATE4,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE5::VARCHAR AS DATE)), 'NULL') AS SCRA_NOTIFICATION_DATE5,

        -- SCRA ACTIVE DUTY START FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE1::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_START_DATE1,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE2::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_START_DATE2,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE3::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_START_DATE3,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE4::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_START_DATE4,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE5::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_START_DATE5,

        -- SCRA ACTIVE DUTY END FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE1::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_END_DATE1,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE2::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_END_DATE2,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE3::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_END_DATE3,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE4::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_END_DATE4,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE5::VARCHAR AS DATE)), 'NULL') AS SCRA_ACTIVE_DUTY_END_DATE5,

        -- SCRA OTHER FIELDS (7 fields)
        COALESCE(CUSTOM_FIELD_VALUES:SCRACUSTOMERISTHESERVICEMEMBER::VARCHAR, 'NULL') AS SCRA_CUSTOMER_IS_THE_SERVICE_MEMBER,
        COALESCE(CUSTOM_FIELD_VALUES:SCRACUSTOMERISADEPENDENTOFTHESERVICEMEMBER::VARCHAR, 'NULL') AS SCRA_CUSTOMER_IS_A_DEPENDENT_OF_THE_SERVICE_MEMBER,
        COALESCE(CUSTOM_FIELD_VALUES:SCRATYPEOFSERVICE::VARCHAR, 'NULL') AS SCRA_TYPE_OF_SERVICE,
        COALESCE(CUSTOM_FIELD_VALUES:SCRADECLINEREASON::VARCHAR, 'NULL') AS SCRA_DECLINE_REASON,
        COALESCE(CUSTOM_FIELD_VALUES:SCRAORDERSRECEIVED::VARCHAR, 'NULL') AS SCRA_ORDERS_RECEIVED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAORDERSRECEIVEDDATE::VARCHAR AS DATE)), 'NULL') AS SCRA_ORDERS_RECEIVED_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:SCRAINTERESTRATEADJUSTED::VARCHAR, 'NULL') AS SCRA_INTEREST_RATE_ADJUSTED,

        -- BANKRUPTCY ADDITIONAL FIELDS (4 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYNOTIFICATIONRECEIVEDDATE::VARCHAR AS DATE)), 'NULL') AS BANKRUPTCY_NOTIFICATION_RECEIVED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DISCHARGEDATE::VARCHAR AS DATE)), 'NULL') AS DISCHARGE_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DISMISSALDATE::VARCHAR AS DATE)), 'NULL') AS DISMISSAL_DATE,

        -- STATUS AND FUNDING FIELDS (6 fields)
        COALESCE(CUSTOM_FIELD_VALUES:COMPLAINTSTATUS::VARCHAR, 'NULL') AS COMPLAINT_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:FUNDINGSTATUS::VARCHAR, 'NULL') AS FUNDING_STATUS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REQUESTEDFIRSTPAYMENTDATE::VARCHAR AS DATE)), 'NULL') AS REQUESTED_FIRST_PAYMENT_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:PAYMENTRATING::VARCHAR, 'NULL') AS PAYMENT_RATING,
        COALESCE(CUSTOM_FIELD_VALUES:SPECIALCOMMENT::VARCHAR, 'NULL') AS SPECIAL_COMMENT,
        COALESCE(CUSTOM_FIELD_VALUES:CONSUMERINDICATOR::VARCHAR, 'NULL') AS CONSUMER_INDICATOR,

        -- DEBT SALE FIELDS (7 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SOLDDATE::VARCHAR AS DATE)), 'NULL') AS SOLD_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTSALESTATUS::VARCHAR, 'NULL') AS DEBT_SALE_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTBUYER::VARCHAR, 'NULL') AS DEBT_BUYER,
        COALESCE(CUSTOM_FIELD_VALUES:VALIDATIONOFDEBTSTATUS::VARCHAR, 'NULL') AS VALIDATION_OF_DEBT_STATUS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DEBTREQUESTTEST::VARCHAR AS DATE)), 'NULL') AS DEBT_REQUEST_TEST,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DEBTREQUESTSENTTEST::VARCHAR AS DATE)), 'NULL') AS DEBT_REQUEST_SENT_TEST,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PROMOPERIODEXPIRATIONDATE::VARCHAR AS DATE)), 'NULL') AS PROMO_PERIOD_EXPIRATION_DATE,

        -- BANKRUPTCY AND CHARGE OFF ADDITIONAL (6 fields)
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYSTATUS::VARCHAR, 'NULL') AS BANKRUPTCY_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:FUNDINGCANCELLATIONREASON::VARCHAR, 'NULL') AS FUNDING_CANCELLATION_REASON,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDUEPRINCIPAL::VARCHAR AS NUMERIC(30,2))), 'NULL') AS CHARGE_OFF_DUE_PRINCIPAL,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDUEINTEREST::VARCHAR AS NUMERIC(30,2))), 'NULL') AS CHARGE_OFF_DUE_INTEREST,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CHARGEOFFDUEFEES::VARCHAR AS NUMERIC(30,2))), 'NULL') AS CHARGE_OFF_DUE_FEES,

        -- HARDSHIP FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:HARDSHIPDESCRIPTION::VARCHAR, 'NULL') AS HARDSHIP_DESCRIPTION,
        COALESCE(CUSTOM_FIELD_VALUES:DPDATHARDSHIPENROLLMENT::VARCHAR, 'NULL') AS DPD_AT_HARDSHIP_ENROLLMENT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPENROLLMENTSTARTDATE::VARCHAR AS DATE)), 'NULL') AS HARDSHIP_ENROLLMENT_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPENROLLMENTENDDATE::VARCHAR AS DATE)), 'NULL') AS HARDSHIP_ENROLLMENT_END_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:HARDSHIPDURATION::VARCHAR, 'NULL') AS HARDSHIP_DURATION,

        -- SETTLEMENT FIELDS (9 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS SETTLEMENT_AMOUNT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTACCEPTEDDATE::VARCHAR AS DATE)), 'NULL') AS SETTLEMENT_ACCEPTED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PAYOFFATTHETIMEOFSETTLEMENTARRANGEMENT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTSETUPDATE::VARCHAR AS DATE)), 'NULL') AS SETTLEMENT_SETUP_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTFORGIVEN::VARCHAR AS NUMERIC(30,2))), 'NULL') AS AMOUNT_FORGIVEN,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTAMOUNTPAID::VARCHAR AS NUMERIC(30,2))), 'NULL') AS SETTLEMENT_AMOUNT_PAID,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:UNPAIDSETTLEMENTBALANCE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS UNPAID_SETTLEMENT_BALANCE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BALANCEATTIMEOFDEBTSALE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS BALANCE_AT_TIME_OF_DEBT_SALE,

        -- COLLECTIONS AND CREDIT FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:STATERATE::VARCHAR, 'NULL') AS STATE_RATE,
        COALESCE(CUSTOM_FIELD_VALUES:CREDITCOUNSELORCOMPANY::VARCHAR, 'NULL') AS CREDIT_COUNSELOR_COMPANY,
        COALESCE(CUSTOM_FIELD_VALUES:THIRDPARTYCOLLECTIONAGENCY::VARCHAR, 'NULL') AS THIRD_PARTY_COLLECTION_AGENCY,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REPURCHASEAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS REPURCHASE_AMOUNT,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTREPURCHASESTATUS::VARCHAR, 'NULL') AS DEBT_REPURCHASE_STATUS,

        -- SETTLEMENT ADDITIONAL (3 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TOTALPAIDATTIMEOFSETTLEMENT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS TOTAL_PAID_AT_TIME_OF_SETTLEMENT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTENDDATE::VARCHAR AS DATE)), 'NULL') AS SETTLEMENT_END_DATE,

        -- PROGRAM AND EXECUTION FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:PROGRAMID::VARCHAR, 'NULL') AS PROGRAM_ID,
        COALESCE(TO_VARCHAR(COALESCE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', TRY_CAST(CUSTOM_FIELD_VALUES:EXECUTIONDATE::VARCHAR AS TIMESTAMP_NTZ))::date, TRY_CAST(CUSTOM_FIELD_VALUES:EXECUTIONDATE::VARCHAR AS DATE))), 'NULL') AS EXECUTION_DATE,

        -- INDIRECT LENDING FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:INDIRECTPURCHASEDATE::VARCHAR AS DATE)), 'NULL') AS INDIRECT_PURCHASE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:INDIRECTLENDERORIGINATIONFEE::VARCHAR, 'NULL') AS INDIRECT_LENDER_ORIGINATION_FEE,
        COALESCE(CUSTOM_FIELD_VALUES:INDIRECTAMOUNTORIGINATIONINTEREST::VARCHAR, 'NULL') AS INDIRECT_AMOUNT_ORIGINATION_INTEREST,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PREMIUMRATE::VARCHAR AS NUMERIC(30,3))), 'NULL') AS PREMIUM_RATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PREMIUMAMOUNT::VARCHAR AS NUMERIC(30,3))), 'NULL') AS PREMIUM_AMOUNT,

        -- TENANT AND CHANNEL FIELDS (7 fields)
        COALESCE(CUSTOM_FIELD_VALUES:TENANT_ID::VARCHAR, 'NULL') AS TENANT_ID,
        COALESCE(CUSTOM_FIELD_VALUES:CHANNEL::VARCHAR, 'NULL') AS CHANNEL,
        COALESCE(CUSTOM_FIELD_VALUES:LOANPURPOSE::VARCHAR, 'NULL') AS LOAN_PURPOSE,
        COALESCE(CUSTOM_FIELD_VALUES:LOANTIER::VARCHAR, 'NULL') AS LOAN_TIER,
        COALESCE(CUSTOM_FIELD_VALUES:CPVERSION::VARCHAR, 'NULL') AS CP_VERSION,
        COALESCE(CUSTOM_FIELD_VALUES:APPLICANTRESIDENCESTATE::VARCHAR, 'NULL') AS APPLICANT_RESIDENCE_STATE,

        -- APPLICANT INFO FIELDS (9 fields)
        COALESCE(CUSTOM_FIELD_VALUES:EMPLOYMENTSTATUS::VARCHAR, 'NULL') AS EMPLOYMENT_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:HOUSINGSTATUS::VARCHAR, 'NULL') AS HOUSING_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:ANNUALINCOME::VARCHAR, 'NULL') AS ANNUAL_INCOME,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BUREAUSCORE::VARCHAR AS NUMERIC(30,0))), 'NULL') AS BUREAU_SCORE,
        COALESCE(CUSTOM_FIELD_VALUES:BUREAUSCORETYPE::VARCHAR, 'NULL') AS BUREAU_SCORE_TYPE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:NDI::VARCHAR AS NUMERIC(30,2))), 'NULL') AS NDI,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DTI::VARCHAR AS NUMERIC(30,3))), 'NULL') AS DTI,
        COALESCE(CUSTOM_FIELD_VALUES:APPMOSSINCEDEROGPUBREC::VARCHAR, 'NULL') AS APP_MOS_SINCE_DEROG_PUB_REC,
        COALESCE(CUSTOM_FIELD_VALUES:MLAFLAG::VARCHAR, 'NULL') AS MLA_FLAG,

        -- BUREAU SCORE REFRESH FIELDS (2 fields)
        COALESCE(CUSTOM_FIELD_VALUES:REFRESHEDBUREAUSCORE::VARCHAR, 'NULL') AS REFRESHED_BUREAU_SCORE,
        COALESCE(CUSTOM_FIELD_VALUES:REFRESHEDBUREAUSCOREDATE::VARCHAR, 'NULL') AS REFRESHED_BUREAU_SCORE_DATE,

        -- SECONDARY MARKET FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:SECONDARYBUYER::VARCHAR, 'NULL') AS SECONDARY_BUYER,
        COALESCE(CUSTOM_FIELD_VALUES:SECONDARYSELLER::VARCHAR, 'NULL') AS SECONDARY_SELLER,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SECONDARYPURCHASEDATE::VARCHAR AS DATE)), 'NULL') AS SECONDARY_PURCHASE_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SECONDARYSOLDDATE::VARCHAR AS DATE)), 'NULL') AS SECONDARY_SOLD_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:CPDFLAG::VARCHAR, 'NULL') AS CPD_FLAG,

        -- SCRA DATE FIELDS (3 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRASTARTDATE::VARCHAR AS DATE)), 'NULL') AS SCRA_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAENDDATE::VARCHAR AS DATE)), 'NULL') AS SCRA_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CPDPROCESSINGDATE::VARCHAR AS DATE)), 'NULL') AS CPD_PROCESSING_DATE,

        -- INSURANCE FIELDS (4 fields)
        COALESCE(CUSTOM_FIELD_VALUES:INSURANCEFLAG::VARCHAR, 'NULL') AS INSURANCE_FLAG,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:INSURANCESTARTDATE::VARCHAR AS DATE)), 'NULL') AS INSURANCE_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:INSURANCEENDDATE::VARCHAR AS DATE)), 'NULL') AS INSURANCE_END_DATE,

        -- AUTOPAY AND DEBT SETTLEMENT FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:AUTOPAYOPTIN::VARCHAR, 'NULL') AS AUTOPAY_OPT_IN,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTSETTLEMENTCOMPANY::VARCHAR, 'NULL') AS DEBT_SETTLEMENT_COMPANY,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CEASEANDDESISTDATE::VARCHAR AS DATE)), 'NULL') AS CEASE_AND_DESIST_DATE,

        -- PRINCIPAL ADVANCE AND ORIGINATION FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PRINCIPALADVANCEREMAINING::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PRINCIPAL_ADVANCE_REMAINING,
        COALESCE(CUSTOM_FIELD_VALUES:ORIGINATINGPARTNER::VARCHAR, 'NULL') AS ORIGINATING_PARTNER,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:ORIGINATIONFEE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS ORIGINATION_FEE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS LOAN_AMOUNT_C,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTFUNDED::VARCHAR AS NUMERIC(30,2))), 'NULL') AS AMOUNT_FUNDED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TOTALPREPAIDFEES::VARCHAR AS NUMERIC(30,2))), 'NULL') AS TOTAL_PREPAID_FEES,

        -- COMMUNICATION AND DELINQUENCY FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:THIRDPARTYCOMMUNICATIONWITHHMABOUTDEBT::VARCHAR, 'NULL') AS THIRD_PARTY_COMMUNICATION_WITH_HM_ABOUT_DEBT,
        COALESCE(CUSTOM_FIELD_VALUES:DELINQUENCYREASON::VARCHAR, 'NULL') AS DELINQUENCY_REASON,

        -- FRAUD ADDITIONAL FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDCONTACTEMAIL::VARCHAR, 'NULL') AS FRAUD_CONTACT_EMAIL,
        COALESCE(CUSTOM_FIELD_VALUES:FOLLOWUPINFORMATION::VARCHAR, 'NULL') AS FOLLOW_UP_INFORMATION,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:FRAUDNOTIFICATIONRECEIVED::VARCHAR AS DATE)), 'NULL') AS FRAUD_NOTIFICATION_RECEIVED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:EXPECTEDRESPONSEDATE::VARCHAR AS DATE)), 'NULL') AS EXPECTED_RESPONSE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:EOSCARDISPUTECODE::VARCHAR, 'NULL') AS EOS_CARD_DISPUTE_CODE,

        -- ORIGINATOR AND REFERRAL FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:ORIGINATOR::VARCHAR, 'NULL') AS ORIGINATOR,
        COALESCE(CUSTOM_FIELD_VALUES:ACDVNUMBER::VARCHAR, 'NULL') AS ACDV_NUMBER,
        COALESCE(CUSTOM_FIELD_VALUES:SOURCEOFREFERRAL::VARCHAR, 'NULL') AS SOURCE_OF_REFERRAL,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATE_SUBMITTED_TO_REFERRER::VARCHAR AS DATE)), 'NULL') AS DATE_SUBMITTED_TO_REFERRER,

        -- BANKRUPTCY AND CREDIT REPORTING FIELDS (4 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REAFFIRMATIONDATE::VARCHAR AS DATE)), 'NULL') AS REAFFIRMATION_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:INCORRECTCREDITREPORTINGITEM::VARCHAR, 'NULL') AS INCORRECT_CREDIT_REPORTING_ITEM,
        COALESCE(CUSTOM_FIELD_VALUES:CORRECTEDCREDITREPORTINGITEM::VARCHAR, 'NULL') AS CORRECTED_CREDIT_REPORTING_ITEM,

        -- COLLECTIONS WORKABLE DATES (3 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:NEXTWORKABLEDATE::VARCHAR AS DATE)), 'NULL') AS NEXT_WORKABLE_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LASTCOLLECTIONSCONTACTDATE::VARCHAR AS DATE)), 'NULL') AS LAST_COLLECTIONS_CONTACT_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:NUMBEROFSKIPS::VARCHAR, 'NULL') AS NUMBER_OF_SKIPS,

        -- DCA SETTLEMENT FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTSTATUSDCA::VARCHAR, 'NULL') AS SETTLEMENT_STATUS_DCA,
        COALESCE(CUSTOM_FIELD_VALUES:FEERATEDCA::VARCHAR, 'NULL') AS FEE_RATE_DCA,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTDUETOHAPPYMONEYDCA::VARCHAR AS NUMERIC(30,2))), 'NULL') AS AMOUNT_DUE_TO_HAPPY_MONEY_DCA,
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTCOMPANYDCA::VARCHAR, 'NULL') AS SETTLEMENT_COMPANY_DCA,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTAGREEMENTAMOUNTDCA::VARCHAR AS NUMERIC(30,2))), 'NULL') AS SETTLEMENT_AGREEMENT_AMOUNT_DCA,

        -- HARDSHIP AND LOAN MOD FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:HARDSHIPREASON::VARCHAR, 'NULL') AS HARDSHIP_REASON,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODIFICATIONAGREEMENTSENTDATE::VARCHAR AS DATE)), 'NULL') AS LOAN_MODIFICATION_AGREEMENT_SENT_DATE,

        -- INVESTOR FIELDS (15 fields)
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR1::VARCHAR, 'NULL') AS INVESTOR1,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR2::VARCHAR, 'NULL') AS INVESTOR2,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR3::VARCHAR, 'NULL') AS INVESTOR3,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR4::VARCHAR, 'NULL') AS INVESTOR4,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR5::VARCHAR, 'NULL') AS INVESTOR5,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR6::VARCHAR, 'NULL') AS INVESTOR6,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR7::VARCHAR, 'NULL') AS INVESTOR7,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR8::VARCHAR, 'NULL') AS INVESTOR8,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR9::VARCHAR, 'NULL') AS INVESTOR9,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR10::VARCHAR, 'NULL') AS INVESTOR10,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR11::VARCHAR, 'NULL') AS INVESTOR11,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR12::VARCHAR, 'NULL') AS INVESTOR12,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR13::VARCHAR, 'NULL') AS INVESTOR13,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR14::VARCHAR, 'NULL') AS INVESTOR14,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR15::VARCHAR, 'NULL') AS INVESTOR15,

        -- DNU AND MOD AGREEMENT FIELDS (4 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DNU::VARCHAR AS NUMERIC(30,2))), 'NULL') AS DNU,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODIFICATIONAGREEMENTEXPIRATIONDATE::VARCHAR AS DATE)), 'NULL') AS MODIFICATION_AGREEMENT_EXPIRATION_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODIFICATIONAGREEMENTSIGNEDDATE::VARCHAR AS DATE)), 'NULL') AS LOAN_MODIFICATION_AGREEMENT_SIGNED_DATE,

        -- SKIP A PAY AND PAYMENT REDUCTION FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:STANDARDSKIPAPAYENROLLMENTSTARTDATE::VARCHAR AS DATE)), 'NULL') AS STANDARD_SKIP_A_PAY_ENROLLMENT_START_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:TEMPORARYPAYMENTREDUCTIONTERM::VARCHAR, 'NULL') AS TEMPORARY_PAYMENT_REDUCTION_TERM,
        COALESCE(CUSTOM_FIELD_VALUES:PERCENTAGEOFCURRENTPAYMENT::VARCHAR, 'NULL') AS PERCENTAGE_OF_CURRENT_PAYMENT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TEMPORARYPAYMENTREDUCTIONENROLLMENTDATE::VARCHAR AS DATE)), 'NULL') AS TEMPORARY_PAYMENT_REDUCTION_ENROLLMENT_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANBALANCEATMODIFICATION::VARCHAR AS NUMERIC(30,2))), 'NULL') AS LOAN_BALANCE_AT_MODIFICATION,

        -- CLS AND PAYOFF FIELDS (4 fields)
        COALESCE(CUSTOM_FIELD_VALUES:CLSLOANACCOUNTID::VARCHAR, 'NULL') AS CLS_LOAN_ACCOUNT_ID,
        COALESCE(CUSTOM_FIELD_VALUES:CLSLOANACCOUNTNAME::VARCHAR, 'NULL') AS CLS_LOAN_ACCOUNT_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:PAYOFFLOANID::VARCHAR, 'NULL') AS PAYOFF_LOAN_ID,
        COALESCE(CUSTOM_FIELD_VALUES:LEADGUID::VARCHAR, 'NULL') AS LEAD_GUID,

        -- MIGRATION AND MOD PAYMENT FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PAYMENTAMOUNTBEFOREMODIFICATION::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PAYMENT_AMOUNT_BEFORE_MODIFICATION,
        COALESCE(CUSTOM_FIELD_VALUES:MIGRATEDFROMCLS::VARCHAR, 'NULL') AS MIGRATED_FROM_CLS,
        COALESCE(CUSTOM_FIELD_VALUES:MIGRATEDFROMLAPRO::VARCHAR, 'NULL') AS MIGRATED_FROM_LA_PRO,
        COALESCE(CUSTOM_FIELD_VALUES:MIGRATIONBATCHID::VARCHAR, 'NULL') AS MIGRATION_BATCH_ID,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PERMANENTPAYMENTREDUCTIONENROLLMENTDATE::VARCHAR AS DATE)), 'NULL') AS PERMANENT_PAYMENT_REDUCTION_ENROLLMENT_DATE,

        -- DISASTER AND PAYMENT REDUCTION FIELDS (3 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DISASTERSKIPAPAYENROLLMENT::VARCHAR AS DATE)), 'NULL') AS DISASTER_SKIP_A_PAY_ENROLLMENT,
        COALESCE(CUSTOM_FIELD_VALUES:MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE::VARCHAR, 'NULL') AS MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE_C,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEY_PREFERRED_METHOD_OF_CONTACT::VARCHAR, 'NULL') AS ATTORNEY_PREFERRED_METHOD_OF_CONTACT_C,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MATURITY_DATE_BEFORE_MOD::VARCHAR AS DATE)), 'NULL') AS MATURITY_DATE_BEFORE_MOD_C,
        COALESCE(CUSTOM_FIELD_VALUES:MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT::VARCHAR, 'NULL') AS MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT_C,

        -- TRUSTAGE FIELDS (4 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TRUSTAGESTARTDATE::VARCHAR AS DATE)), 'NULL') AS TRUSTAGE_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TRUSTAGEENDDATE::VARCHAR AS DATE)), 'NULL') AS TRUSTAGE_END_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:TRUSTAGECLAIMNUMBER::VARCHAR, 'NULL') AS TRUSTAGE_CLAIM_NUMBER,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TRUSTAGEPAYMENTGUARDINSURANCEPROGRAMENROLLMENTDATE::VARCHAR AS DATE)), 'NULL') AS TRUSTAGE_PAYMENT_GUARD_INSURANCE_PROGRAM_ENROLLMENT_DATE,

        -- MOD STATUS AND PAYMENT FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:STATUSPRIORTOMODIFICATION::VARCHAR, 'NULL') AS STATUS_PRIOR_TO_MODIFICATION,
        COALESCE(CUSTOM_FIELD_VALUES:NUMBERPAYMENTSSKIPPED::VARCHAR, 'NULL') AS NUMBER_PAYMENTS_SKIPPED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PAYMENTFORBEARANCEAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PAYMENT_FOR_BEARANCE_AMOUNT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BALLOONPAYMENT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS BALLOON_PAYMENT,
        COALESCE(CUSTOM_FIELD_VALUES:MODTERMEXTENSION::VARCHAR, 'NULL') AS MOD_TERM_EXTENSION,

        -- PORTFOLIO AND BANKRUPTCY FIELDS (4 fields)
        COALESCE(CUSTOM_FIELD_VALUES:PORTFOLIOID::VARCHAR, 'NULL') AS PORTFOLIO_ID_C,
        COALESCE(CUSTOM_FIELD_VALUES:PORTFOLIONAME::VARCHAR, 'NULL') AS PORTFOLIO_NAME_C,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYFLAG::VARCHAR, 'NULL') AS BANKRUPTCY_FLAG,
        COALESCE(CUSTOM_FIELD_VALUES:BAKRUPTCYCHAPTER::VARCHAR, 'NULL') AS BANKRUPTCY_CHAPTER,

        -- SSAP AND TPR MOD DATE FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SSAP2MODENDDATE::VARCHAR AS DATE)), 'NULL') AS SSAP2_MOD_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TPRMODSTARTDATE::VARCHAR AS DATE)), 'NULL') AS TPR_MOD_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TPRMODENDDATE::VARCHAR AS DATE)), 'NULL') AS TPR_MOD_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PPRMODSTARTDATE::VARCHAR AS DATE)), 'NULL') AS PPR_MOD_START_DATE,

        -- DSAP MOD DATE FIELDS (3 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DSAPMODSTARTDATE::VARCHAR AS DATE)), 'NULL') AS DSAP_MOD_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DSAP1MODENDDATE::VARCHAR AS DATE)), 'NULL') AS DSAP1_MOD_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DSAP2MODENDDATE::VARCHAR AS DATE)), 'NULL') AS DSAP2_MOD_END_DATE,

        -- SCRA AND CPD FLAG FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:SCRAFLAG::VARCHAR, 'NULL') AS SCRA_FLAG,
        COALESCE(CUSTOM_FIELD_VALUES:CPDNEWDAY::VARCHAR, 'NULL') AS CPD_NEW_DAY,

        -- CLS APR AND MATURITY FIELDS (2 fields)
        COALESCE(CUSTOM_FIELD_VALUES:CLSAPR::VARCHAR, 'NULL') AS CLS_APR,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLSMATURITYDATE::VARCHAR AS DATE)), 'NULL') AS CLS_MATURITY_DATE,

        -- UTM TRACKING FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:UTMCAMPAIGN::VARCHAR, 'NULL') AS UTM_CAMPAIGN,
        COALESCE(CUSTOM_FIELD_VALUES:UTMMEDIUM::VARCHAR, 'NULL') AS UTM_MEDIUM,
        COALESCE(CUSTOM_FIELD_VALUES:UTMSOURCE::VARCHAR, 'NULL') AS UTM_SOURCE,

        -- PLACEMENT STATUS FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:PLACEMENTSTATUS::VARCHAR, 'NULL') AS PLACEMENT_STATUS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PLACEMENTSTATUSSTARTDATE::VARCHAR AS DATE)), 'NULL') AS PLACEMENT_STATUS_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PLACEMENTSTATUSENDDATE::VARCHAR AS DATE)), 'NULL') AS PLACEMENT_STATUS_END_DATE,

        -- LP APPLICATION AND ORIGINATION FIELDS (3 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LPAPPLICATIONID::VARCHAR AS NUMERIC(30,0))), 'NULL') AS LP_APPLICATION_ID,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:ORIGINATIONDATE::VARCHAR AS DATE)), 'NULL') AS CLS_ORIGINATION_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:MIGRATEDDATETIME::VARCHAR, 'NULL') AS MIGRATED_DATETIME,

        -- INCOME TYPE FIELDS (5 fields)
        COALESCE(CUSTOM_FIELD_VALUES:INCOMETYPE1::VARCHAR, 'NULL') AS INCOME_TYPE1,
        COALESCE(CUSTOM_FIELD_VALUES:INCOMETYPE2::VARCHAR, 'NULL') AS INCOME_TYPE2,
        COALESCE(CUSTOM_FIELD_VALUES:INCOMETYPE3::VARCHAR, 'NULL') AS INCOME_TYPE3,
        COALESCE(CUSTOM_FIELD_VALUES:INCOMETYPE4::VARCHAR, 'NULL') AS INCOME_TYPE4,
        COALESCE(CUSTOM_FIELD_VALUES:INCOMETYPE5::VARCHAR, 'NULL') AS INCOME_TYPE5,

        -- MOD FLAG AND TYPE FIELDS (8 fields)
        COALESCE(CUSTOM_FIELD_VALUES:MODFLAG::VARCHAR, 'NULL') AS MOD_FLAG,
        COALESCE(CUSTOM_FIELD_VALUES:MODTYPE::VARCHAR, 'NULL') AS MOD_TYPE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PREVIOUSMODIFICATION::VARCHAR AS INT)), 'NULL') AS PREVIOUS_MODIFICATION,
        COALESCE(CUSTOM_FIELD_VALUES:MODREASON::VARCHAR, 'NULL') AS MOD_REASON,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS MOD_REQUEST_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODPROCESSINGDATE::VARCHAR AS DATE)), 'NULL') AS MOD_PROCESSING_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODSTARTDATE::VARCHAR AS DATE)), 'NULL') AS MOD_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODENDDATE::VARCHAR AS DATE)), 'NULL') AS MOD_END_DATE,

        -- MOD PAYMENT DEFERRED AND MATURITY FIELDS (5 fields)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:NUMBERPAYMENTSDEFERRED::VARCHAR AS NUMERIC(12,0))), 'NULL') AS NUMBER_PAYMENTS_DEFERRED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODMATURITYDATE::VARCHAR AS DATE)), 'NULL') AS MOD_MATURITY_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MODPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS MOD_PAYMENT_AMOUNT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PPRPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PPR_PAYMENT_AMOUNT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TPRPAYMENTAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS TPR_PAYMENT_AMOUNT,

        -- SETTLEMENT STATUS FIELDS (8 fields)
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTSTATUS::VARCHAR, 'NULL') AS SETTLEMENTSTATUS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SETTLEMENTCOMPLETIONDATE::VARCHAR AS DATE)), 'NULL') AS SETTLEMENTCOMPLETIONDATE,
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTCOMPLETIONPERCENTAGE::VARCHAR, 'NULL') AS SETTLEMENTCOMPLETIONPERCENTAGE,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTSETTLEMENTPAYMENTTERMS::VARCHAR, 'NULL') AS DEBTSETTLEMENTPAYMENTTERMS,
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTCOMPANY::VARCHAR, 'NULL') AS SETTLEMENTCOMPANY,
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTAGREEMENTAMOUNT::VARCHAR, 'NULL') AS SETTLEMENTAGREEMENTAMOUNT,
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTSTARTDATE::VARCHAR, 'NULL') AS SETTLEMENTSTARTDATE,
        COALESCE(CUSTOM_FIELD_VALUES:PROOFOFCLAIMREQUIRED::VARCHAR, 'NULL') AS PROOFOFCLAIMREQUIRED,

        -- DEBT SETTLEMENT PAYMENTS AND DSC CONTACT FIELDS (3 fields)
        COALESCE(CUSTOM_FIELD_VALUES:NUMBEROFDEBTSETTLEMENTPAYMENTSEXPECTED::VARCHAR, 'NULL') AS NUMBEROFDEBTSETTLEMENTPAYMENTSEXPECTED,
        COALESCE(CUSTOM_FIELD_VALUES:DSCCONTACT::VARCHAR, 'NULL') AS DSCCONTACT,
        COALESCE(CUSTOM_FIELD_VALUES:EXPECTEDSETTLEMENTENDDATE::VARCHAR, 'NULL') AS EXPECTEDSETTLEMENTENDDATE,

        -- DO NOT CONTACT PREFERENCES (4 fields)
        COALESCE(CUSTOM_FIELD_VALUES:DONOTCALL::VARCHAR, 'NULL') AS DONOTCALL,
        COALESCE(CUSTOM_FIELD_VALUES:DONOTEMAIL::VARCHAR, 'NULL') AS DONOTEMAIL,
        COALESCE(CUSTOM_FIELD_VALUES:DONOTMAIL::VARCHAR, 'NULL') AS DONOTMAIL,
        COALESCE(CUSTOM_FIELD_VALUES:DONOTSMS::VARCHAR, 'NULL') AS DONOTSMS,

        -- HARDSHIP REQUEST DATE (1 field)
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS HARDSHIP_REQUEST_DATE

    FROM ARCA.FRESHSNOW.TRANSFORMED_CUSTOM_FIELD_ENTITY_CURRENT cs
    INNER JOIN ARCA.FRESHSNOW.LOAN_ENTITY_CURRENT le ON (cs.entity_id = le.settings_id)
    WHERE 1 = 1
      AND cs.entity_type = 'Entity.LoanSettings'
      AND cs.schema_name = ARCA.CONFIG.LMS_SCHEMA()
      AND le.schema_name = ARCA.CONFIG.LMS_SCHEMA()
),

unpivoted_data AS (
    SELECT *
    FROM base_data
    UNPIVOT (
        field_value FOR field_name IN (
            LOAN_ID, SETTINGS_ID,
            PROCESSING_FEES_PAID, BANKRUPTCY_CASE_NUMBER, BANKRUPTCY_COURT_DISTRICT, BANKRUPTCY_FILING_DATE,
            BANKRUPTCY_VENDOR, BANKRUPTCY_ORDERED_NEW_LOAN_AMOUNT, BANKRUPTCY_ORDERED_NEW_INTEREST_RATE,
            BANKRUPTCY_ORDERED_NUMBER_OF_PAYMENTS, BANKRUPTCY_ORDERED_NEW_PAYMENT_AMOUNT, COMPLIANCE_CONDITION_CODE,
            REPOSSESSION_REVIEW_DECISION, REPOSSESSION_COMPANY_NAME, REPOSSESSION_COMPANY_CONTACT_NAME,
            REPOSSESSION_COMPANY_PHONE_NUMBER, REPOSSESSION_COMPANY_EMAIL_ADDRESS, REPOSSESSION_MANAGER_DECLINE_DATE,
            REPOSSESSION_CITY, REPOSSESSION_COUNTY, REPOSSESSION_STATE, REPOSSESSION_CASE_NUMBER, REPOSSESSION_DATE,
            CUSTOMER_REDEEMED_COLLATERAL, COLLECTIBLE_CHARGE_OFF_DATE, CHARGE_OFF_DATE, DATE_OF_DEATH,
            DECEASED_NOTIFICATION_DATE, BALANCE_AT_THE_TIME_OF_DECEASED_NOTIFICATION, FRAUD_INVESTIGATION_RESULTS,
            FRAUD_CONFIRMED_DATE, ATTORNEY_RETAINED, ATTORNEY_TYPE, ATTORNEY_NAME, FIRM_NAME, ATTORNEY_ADDRESS,
            ATTORNEY_CITY, ATTORNEY_STATE, ATTORNEY_ZIP, ATTORNEY_PHONE, ATTORNEY_FAX, ATTORNEY_EMAIL,
            ATTORNEY_RETAINED_DATE, SCRA_NOTIFICATION_DATE1, SCRA_NOTIFICATION_DATE2, SCRA_NOTIFICATION_DATE3,
            SCRA_NOTIFICATION_DATE4, SCRA_NOTIFICATION_DATE5, SCRA_ACTIVE_DUTY_START_DATE1, SCRA_ACTIVE_DUTY_START_DATE2,
            SCRA_ACTIVE_DUTY_START_DATE3, SCRA_ACTIVE_DUTY_START_DATE4, SCRA_ACTIVE_DUTY_START_DATE5,
            SCRA_ACTIVE_DUTY_END_DATE1, SCRA_ACTIVE_DUTY_END_DATE2, SCRA_ACTIVE_DUTY_END_DATE3,
            SCRA_ACTIVE_DUTY_END_DATE4, SCRA_ACTIVE_DUTY_END_DATE5, SCRA_CUSTOMER_IS_THE_SERVICE_MEMBER,
            SCRA_CUSTOMER_IS_A_DEPENDENT_OF_THE_SERVICE_MEMBER, SCRA_TYPE_OF_SERVICE, SCRA_DECLINE_REASON,
            SCRA_ORDERS_RECEIVED, SCRA_ORDERS_RECEIVED_DATE, SCRA_INTEREST_RATE_ADJUSTED,
            BANKRUPTCY_NOTIFICATION_RECEIVED_DATE, DISCHARGE_DATE, DISMISSAL_DATE, COMPLAINT_STATUS, FUNDING_STATUS,
            REQUESTED_FIRST_PAYMENT_DATE, PAYMENT_RATING, SPECIAL_COMMENT, CONSUMER_INDICATOR, SOLD_DATE,
            DEBT_SALE_STATUS, DEBT_BUYER, VALIDATION_OF_DEBT_STATUS, DEBT_REQUEST_TEST, DEBT_REQUEST_SENT_TEST,
            PROMO_PERIOD_EXPIRATION_DATE, BANKRUPTCY_STATUS, FUNDING_CANCELLATION_REASON, CHARGE_OFF_DUE_PRINCIPAL,
            CHARGE_OFF_DUE_INTEREST, CHARGE_OFF_DUE_FEES, HARDSHIP_DESCRIPTION, DPD_AT_HARDSHIP_ENROLLMENT,
            HARDSHIP_ENROLLMENT_START_DATE, HARDSHIP_ENROLLMENT_END_DATE, HARDSHIP_DURATION, SETTLEMENT_AMOUNT,
            SETTLEMENT_ACCEPTED_DATE, PAYOFF_AT_THE_TIME_OF_SETTLEMENT_ARRANGEMENT, SETTLEMENT_SETUP_DATE,
            AMOUNT_FORGIVEN, SETTLEMENT_AMOUNT_PAID, UNPAID_SETTLEMENT_BALANCE, BALANCE_AT_TIME_OF_DEBT_SALE,
            STATE_RATE, CREDIT_COUNSELOR_COMPANY, THIRD_PARTY_COLLECTION_AGENCY, REPURCHASE_AMOUNT,
            DEBT_REPURCHASE_STATUS, TOTAL_PAID_AT_TIME_OF_SETTLEMENT, SETTLEMENT_END_DATE, PROGRAM_ID, EXECUTION_DATE,
            INDIRECT_PURCHASE_DATE, INDIRECT_LENDER_ORIGINATION_FEE, INDIRECT_AMOUNT_ORIGINATION_INTEREST,
            PREMIUM_RATE, PREMIUM_AMOUNT, TENANT_ID, CHANNEL, LOAN_PURPOSE, LOAN_TIER, CP_VERSION,
            APPLICANT_RESIDENCE_STATE, EMPLOYMENT_STATUS, HOUSING_STATUS, ANNUAL_INCOME, BUREAU_SCORE,
            BUREAU_SCORE_TYPE, NDI, DTI, APP_MOS_SINCE_DEROG_PUB_REC, MLA_FLAG, REFRESHED_BUREAU_SCORE,
            REFRESHED_BUREAU_SCORE_DATE, SECONDARY_BUYER, SECONDARY_SELLER, SECONDARY_PURCHASE_DATE,
            SECONDARY_SOLD_DATE, CPD_FLAG, SCRA_START_DATE, SCRA_END_DATE, CPD_PROCESSING_DATE, INSURANCE_FLAG,
            INSURANCE_START_DATE, INSURANCE_END_DATE, AUTOPAY_OPT_IN, DEBT_SETTLEMENT_COMPANY, CEASE_AND_DESIST_DATE,
            PRINCIPAL_ADVANCE_REMAINING, ORIGINATING_PARTNER, ORIGINATION_FEE, LOAN_AMOUNT_C, AMOUNT_FUNDED,
            TOTAL_PREPAID_FEES, THIRD_PARTY_COMMUNICATION_WITH_HM_ABOUT_DEBT, DELINQUENCY_REASON, FRAUD_CONTACT_EMAIL,
            FOLLOW_UP_INFORMATION, FRAUD_NOTIFICATION_RECEIVED, EXPECTED_RESPONSE_DATE, EOS_CARD_DISPUTE_CODE,
            ORIGINATOR, ACDV_NUMBER, SOURCE_OF_REFERRAL, DATE_SUBMITTED_TO_REFERRER, REAFFIRMATION_DATE,
            INCORRECT_CREDIT_REPORTING_ITEM, CORRECTED_CREDIT_REPORTING_ITEM, NEXT_WORKABLE_DATE,
            LAST_COLLECTIONS_CONTACT_DATE, NUMBER_OF_SKIPS, SETTLEMENT_STATUS_DCA, FEE_RATE_DCA,
            AMOUNT_DUE_TO_HAPPY_MONEY_DCA, SETTLEMENT_COMPANY_DCA, SETTLEMENT_AGREEMENT_AMOUNT_DCA, HARDSHIP_REASON,
            LOAN_MODIFICATION_AGREEMENT_SENT_DATE, INVESTOR1, INVESTOR2, INVESTOR3, INVESTOR4, INVESTOR5, INVESTOR6,
            INVESTOR7, INVESTOR8, INVESTOR9, INVESTOR10, INVESTOR11, INVESTOR12, INVESTOR13, INVESTOR14, INVESTOR15,
            DNU, MODIFICATION_AGREEMENT_EXPIRATION_DATE, LOAN_MODIFICATION_AGREEMENT_SIGNED_DATE,
            STANDARD_SKIP_A_PAY_ENROLLMENT_START_DATE, TEMPORARY_PAYMENT_REDUCTION_TERM, PERCENTAGE_OF_CURRENT_PAYMENT,
            TEMPORARY_PAYMENT_REDUCTION_ENROLLMENT_DATE, LOAN_BALANCE_AT_MODIFICATION, CLS_LOAN_ACCOUNT_ID,
            CLS_LOAN_ACCOUNT_NAME, PAYOFF_LOAN_ID, LEAD_GUID, PAYMENT_AMOUNT_BEFORE_MODIFICATION, MIGRATED_FROM_CLS,
            MIGRATED_FROM_LA_PRO, MIGRATION_BATCH_ID, PERMANENT_PAYMENT_REDUCTION_ENROLLMENT_DATE,
            DISASTER_SKIP_A_PAY_ENROLLMENT, MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE_C,
            ATTORNEY_PREFERRED_METHOD_OF_CONTACT_C, MATURITY_DATE_BEFORE_MOD_C,
            MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT_C, TRUSTAGE_START_DATE, TRUSTAGE_END_DATE,
            TRUSTAGE_CLAIM_NUMBER, TRUSTAGE_PAYMENT_GUARD_INSURANCE_PROGRAM_ENROLLMENT_DATE,
            STATUS_PRIOR_TO_MODIFICATION, NUMBER_PAYMENTS_SKIPPED, PAYMENT_FOR_BEARANCE_AMOUNT, BALLOON_PAYMENT,
            MOD_TERM_EXTENSION, PORTFOLIO_ID_C, PORTFOLIO_NAME_C, BANKRUPTCY_FLAG, BANKRUPTCY_CHAPTER,
            SSAP2_MOD_END_DATE, TPR_MOD_START_DATE, TPR_MOD_END_DATE, PPR_MOD_START_DATE, DSAP_MOD_START_DATE,
            DSAP1_MOD_END_DATE, DSAP2_MOD_END_DATE, SCRA_FLAG, CPD_NEW_DAY, CLS_APR, CLS_MATURITY_DATE,
            UTM_CAMPAIGN, UTM_MEDIUM, UTM_SOURCE, PLACEMENT_STATUS, PLACEMENT_STATUS_START_DATE,
            PLACEMENT_STATUS_END_DATE, LP_APPLICATION_ID, CLS_ORIGINATION_DATE, MIGRATED_DATETIME, INCOME_TYPE1,
            INCOME_TYPE2, INCOME_TYPE3, INCOME_TYPE4, INCOME_TYPE5, MOD_FLAG, MOD_TYPE, PREVIOUS_MODIFICATION,
            MOD_REASON, MOD_REQUEST_DATE, MOD_PROCESSING_DATE, MOD_START_DATE, MOD_END_DATE, NUMBER_PAYMENTS_DEFERRED,
            MOD_MATURITY_DATE, MOD_PAYMENT_AMOUNT, PPR_PAYMENT_AMOUNT, TPR_PAYMENT_AMOUNT, SETTLEMENTSTATUS,
            SETTLEMENTCOMPLETIONDATE, SETTLEMENTCOMPLETIONPERCENTAGE, DEBTSETTLEMENTPAYMENTTERMS, SETTLEMENTCOMPANY,
            SETTLEMENTAGREEMENTAMOUNT, SETTLEMENTSTARTDATE, PROOFOFCLAIMREQUIRED, NUMBEROFDEBTSETTLEMENTPAYMENTSEXPECTED,
            DSCCONTACT, EXPECTEDSETTLEMENTENDDATE, DONOTCALL, DONOTEMAIL, DONOTMAIL, DONOTSMS, HARDSHIP_REQUEST_DATE
        )
    )
),

field_totals AS (
    SELECT
        field_name,
        COUNT(*) AS total_records
    FROM unpivoted_data
    GROUP BY field_name
),

value_counts AS (
    SELECT
        field_name,
        field_value AS value,
        COUNT(*) AS record_count
    FROM unpivoted_data
    GROUP BY field_name, field_value
)

SELECT
    vc.field_name AS FIELD_NAME,
    vc.value AS VALUE,
    vc.record_count AS RECORD_COUNT,
    ROUND((vc.record_count::FLOAT / ft.total_records) * 100, 2) AS PERCENTAGE
FROM value_counts vc
INNER JOIN field_totals ft ON vc.field_name = ft.field_name
ORDER BY vc.field_name, vc.record_count DESC;
