-- Field Value Distribution Analysis for VW_LMS_CUSTOM_LOAN_SETTINGS_CURRENT
-- Shows count and percentage breakdown for each distinct value in every field (including NULLs)
use warehouse BUSINESS_INTELLIGENCE_LARGE;
--missing_field_value_distribution_qc
WITH base_data AS (
    SELECT
        -- ========== FRAUD INVESTIGATION FIELDS (42 fields) ==========
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDTYPE::VARCHAR, 'NULL') AS FRAUD_TYPE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:FRAUDEXPECTEDRESPONSEDATE::VARCHAR AS DATE)), 'NULL') AS FRAUD_EXPECTED_RESPONSE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET1::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_1,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET2::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_2,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET3::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_3,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET4::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_4,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET5::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_5,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET6::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_6,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET7::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_7,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET8::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_8,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET9::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_9,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET10::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_10,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET11::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_11,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET12::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_12,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET13::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_13,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET14::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_14,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET15::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_15,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET16::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_16,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET17::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_17,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET18::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_18,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET19::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_19,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDJIRATICKET20::VARCHAR, 'NULL') AS FRAUD_JIRA_TICKET_20,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS1::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_1,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS2::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_2,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS3::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_3,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS4::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_4,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS5::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_5,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS6::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_6,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS7::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_7,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS8::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_8,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS9::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_9,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS10::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_10,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS11::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_11,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS12::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_12,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS13::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_13,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS14::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_14,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS15::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_15,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS16::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_16,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS17::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_17,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS18::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_18,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS19::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_19,
        COALESCE(CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS20::VARCHAR, 'NULL') AS FRAUD_STATUS_RESULTS_20,

        -- ========== ENHANCED ATTORNEY FIELDS (7 fields) ==========
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYORGANIZATION::VARCHAR, 'NULL') AS ATTORNEY_ORGANIZATION,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYPHONE2::VARCHAR, 'NULL') AS ATTORNEY_PHONE_2,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYPHONE3::VARCHAR, 'NULL') AS ATTORNEY_PHONE_3,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYSTREET1::VARCHAR, 'NULL') AS ATTORNEY_STREET_1,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYSTREET2::VARCHAR, 'NULL') AS ATTORNEY_STREET_2,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYSTREET3::VARCHAR, 'NULL') AS ATTORNEY_STREET_3,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYPREFERREDMETHODOFCONTACT::VARCHAR, 'NULL') AS ATTORNEY_PREFERRED_METHOD_OF_CONTACT,

        -- ========== LOAN MODIFICATION FIELDS (25 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODEFFECTIVEDATE::VARCHAR AS DATE)), 'NULL') AS LOAN_MOD_EFFECTIVE_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODBATCHDATE::VARCHAR AS DATE)), 'NULL') AS LOAN_MOD_BATCH_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LOANMODFORBEARANCESTARTDATE::VARCHAR AS DATE)), 'NULL') AS LOAN_MOD_FORBEARANCE_START_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:LOANMODFORBEARANCELENGTH::VARCHAR, 'NULL') AS LOAN_MOD_FORBEARANCE_LENGTH,
        COALESCE(CUSTOM_FIELD_VALUES:LOANMODTERMEXTLENGTH::VARCHAR, 'NULL') AS LOAN_MOD_TERM_EXT_LENGTH,
        COALESCE(CUSTOM_FIELD_VALUES:MODINPROGRESS::VARCHAR, 'NULL') AS MOD_IN_PROGRESS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PPRREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS PPR_REQUEST_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TPRMODREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS TPR_MOD_REQUEST_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SSAPREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS SSAP_REQUEST_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SSAPMODSTARTDATE::VARCHAR AS DATE)), 'NULL') AS SSAP_MOD_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SSAP1MODENDDATE::VARCHAR AS DATE)), 'NULL') AS SSAP1_MOD_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DSAPREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS DSAP_REQUEST_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DISASTERSKIPAPAYENROLLMENTDATE::VARCHAR AS DATE)), 'NULL') AS DISASTER_SKIP_A_PAY_ENROLLMENT_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:HARDSHIPNEWMATURITYDATE::VARCHAR AS DATE)), 'NULL') AS HARDSHIP_NEW_MATURITY_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:MANAGERREVIEWPERCENTAGEOFCURRENTPAYMENT::VARCHAR, 'NULL') AS MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:MATURITYDATEBEFOREMOD::VARCHAR AS DATE)), 'NULL') AS MATURITY_DATE_BEFORE_MOD,
        COALESCE(CUSTOM_FIELD_VALUES:MEMBERREQUESTEDPAYMENTREDUCTIONRANGE::VARCHAR, 'NULL') AS MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE,
        COALESCE(CUSTOM_FIELD_VALUES:LOANREFINANCED::VARCHAR, 'NULL') AS LOAN_REFINANCED,
        COALESCE(CUSTOM_FIELD_VALUES:LOANSTATUSATTIMEOFFRAUD::VARCHAR, 'NULL') AS LOAN_STATUS_AT_TIME_OF_FRAUD,
        COALESCE(CUSTOM_FIELD_VALUES:LOANSUBSTATUSATTIMEOFFRAUD::VARCHAR, 'NULL') AS LOAN_SUB_STATUS_AT_TIME_OF_FRAUD,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:NEWDUEDATE::VARCHAR AS DATE)), 'NULL') AS NEW_DUE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:SKIPPEDAPAY::VARCHAR, 'NULL') AS SKIPPED_A_PAY,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TOTALMODCOUNT::VARCHAR AS INT)), 'NULL') AS TOTAL_MOD_COUNT,
        COALESCE(CUSTOM_FIELD_VALUES:TOTALMODTERMEXTENSION::VARCHAR, 'NULL') AS TOTAL_MOD_TERM_EXTENSION,
        COALESCE(CUSTOM_FIELD_VALUES:TOTALNUMBEROFSKIPS::VARCHAR, 'NULL') AS TOTAL_NUMBER_OF_SKIPS,

        -- ========== SYSTEM INTEGRATION FIELDS (15 fields) ==========
        COALESCE(CUSTOM_FIELD_VALUES:CLSACCOUNTID::VARCHAR, 'NULL') AS CLS_ACCOUNT_ID,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLSCLEARINGDATE::VARCHAR AS DATE)), 'NULL') AS CLS_CLEARING_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLSCREATEDDATETIME::VARCHAR AS TIMESTAMP_NTZ)), 'NULL') AS CLS_CREATED_DATETIME,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLSLASTMODIFIEDDATETIME::VARCHAR AS TIMESTAMP_NTZ)), 'NULL') AS CLS_LAST_MODIFIED_DATETIME,
        COALESCE(CUSTOM_FIELD_VALUES:CLSREVERSALREASONCODE::VARCHAR, 'NULL') AS CLS_REVERSAL_REASON_CODE,
        COALESCE(CUSTOM_FIELD_VALUES:CLSREVERSALREFERENCE::VARCHAR, 'NULL') AS CLS_REVERSAL_REFERENCE,
        COALESCE(CUSTOM_FIELD_VALUES:CLSREVERSALTRANSACTIONNAME::VARCHAR, 'NULL') AS CLS_REVERSAL_TRANSACTION_NAME,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLSTRANSACTIONDATE::VARCHAR AS DATE)), 'NULL') AS CLS_TRANSACTION_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REVERSALTRANSACTIONDATETIME::VARCHAR AS TIMESTAMP_NTZ)), 'NULL') AS REVERSAL_TRANSACTION_DATETIME,
        COALESCE(CUSTOM_FIELD_VALUES:HMLOANID::VARCHAR, 'NULL') AS HM_LOAN_ID,
        COALESCE(CUSTOM_FIELD_VALUES:PAYOFFUID::VARCHAR, 'NULL') AS PAYOFF_UID,
        COALESCE(CUSTOM_FIELD_VALUES:EXTERNALDELIVERYID::VARCHAR, 'NULL') AS EXTERNAL_DELIVERY_ID,
        COALESCE(CUSTOM_FIELD_VALUES:BORROWERSUBSCRIBERID::VARCHAR, 'NULL') AS BORROWER_SUBSCRIBER_ID,
        COALESCE(CUSTOM_FIELD_VALUES:ISMIGRATED::VARCHAR, 'NULL') AS IS_MIGRATED,
        COALESCE(CUSTOM_FIELD_VALUES:TENANTID::VARCHAR, 'NULL') AS TENANT_ID_NEW,

        -- ========== LEGAL & COMPLIANCE FIELDS (33 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:BANKRUPTCYBALANCE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS BANKRUPTCY_BALANCE,
        COALESCE(CUSTOM_FIELD_VALUES:BANKRUPTCYCHAPTER::VARCHAR, 'NULL') AS BANKRUPTCY_CHAPTER,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DCASTARTDATE::VARCHAR AS DATE)), 'NULL') AS DCA_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DCAENDDATE::VARCHAR AS DATE)), 'NULL') AS DCA_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DCACLOSEDATE::VARCHAR AS DATE)), 'NULL') AS DCA_CLOSE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:DCACLOSEREASON::VARCHAR, 'NULL') AS DCA_CLOSE_REASON,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DCARECALLACKNOWLEDGMENTDATE::VARCHAR AS DATE)), 'NULL') AS DCA_RECALL_ACKNOWLEDGMENT_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PROOFOFCLAIMDEADLINEDATE::VARCHAR AS DATE)), 'NULL') AS PROOF_OF_CLAIM_DEADLINE_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PROOFOFCLAIMCOMPLETEDDATE::VARCHAR AS DATE)), 'NULL') AS PROOF_OF_CLAIM_COMPLETED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLAIMCOMPLETEDDATE::VARCHAR AS DATE)), 'NULL') AS CLAIM_COMPLETED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LASTDATETOFILECLAIMS::VARCHAR AS DATE)), 'NULL') AS LAST_DATE_TO_FILE_CLAIMS,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LASTDATETOFILECLAIMSGOVT::VARCHAR AS DATE)), 'NULL') AS LAST_DATE_TO_FILE_CLAIMS_GOVT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PLANCONFIRMEDDATE::VARCHAR AS DATE)), 'NULL') AS PLAN_CONFIRMED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEPLANCONFIRMED::VARCHAR AS DATE)), 'NULL') AS DATE_PLAN_CONFIRMED,
        COALESCE(CUSTOM_FIELD_VALUES:FILINGFEESTATUS::VARCHAR, 'NULL') AS FILING_FEE_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:CONTINGENCYSTATUSCODE::VARCHAR, 'NULL') AS CONTINGENCY_STATUS_CODE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CONTINGENCYSTATUSCODEAPPLYDATE::VARCHAR AS DATE)), 'NULL') AS CONTINGENCY_STATUS_CODE_APPLY_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:DISPOSITION::VARCHAR, 'NULL') AS DISPOSITION,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DISCHARGEDDATE::VARCHAR AS DATE)), 'NULL') AS DISCHARGED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEDISCHARGED::VARCHAR AS DATE)), 'NULL') AS DATE_DISCHARGED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEDISMISSED::VARCHAR AS DATE)), 'NULL') AS DATE_DISMISSED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:JOINTDEBTORDISCHARGEDDATE::VARCHAR AS DATE)), 'NULL') AS JOINT_DEBTOR_DISCHARGED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:JOINTDEBTORDISMISSEDDATE::VARCHAR AS DATE)), 'NULL') AS JOINT_DEBTOR_DISMISSED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEJOINTDEBTORDISCHARGED::VARCHAR AS DATE)), 'NULL') AS DATE_JOINT_DEBTOR_DISCHARGED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEJOINTDEBTORDISMISSED::VARCHAR AS DATE)), 'NULL') AS DATE_JOINT_DEBTOR_DISMISSED,
        COALESCE(CUSTOM_FIELD_VALUES:JOINTDEBTORDISPOSITION::VARCHAR, 'NULL') AS JOINT_DEBTOR_DISPOSITION,
        COALESCE(CUSTOM_FIELD_VALUES:SCRACERTIFIED::VARCHAR, 'NULL') AS SCRA_CERTIFIED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SCRAREQUESTRECEIVEDDATE::VARCHAR AS DATE)), 'NULL') AS SCRA_REQUEST_RECEIVED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:ACTIVEDUTYSTARTDATE::VARCHAR AS DATE)), 'NULL') AS ACTIVE_DUTY_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:ACTIVEDUTYENDDATE::VARCHAR AS DATE)), 'NULL') AS ACTIVE_DUTY_END_DATE,

        -- ========== SETTLEMENT ENHANCEMENT FIELDS (8 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:APPROVEDSETTLEMENTAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS APPROVED_SETTLEMENT_AMOUNT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:AMOUNTDUETOHAPPYMONEY::VARCHAR AS NUMERIC(30,2))), 'NULL') AS AMOUNT_DUE_TO_HAPPY_MONEY,
        COALESCE(CUSTOM_FIELD_VALUES:SETTLEMENTTYPE::VARCHAR, 'NULL') AS SETTLEMENT_TYPE,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTSETTLEMENTPAYMENTPLANSTATUS::VARCHAR, 'NULL') AS DEBT_SETTLEMENT_PAYMENT_PLAN_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:DEBTSETTLEMENTPAYMENTSEXPECTED::VARCHAR, 'NULL') AS DEBT_SETTLEMENT_PAYMENTS_EXPECTED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:HMRECALLDATE::VARCHAR AS DATE)), 'NULL') AS HM_RECALL_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:HMRECALLREASON::VARCHAR, 'NULL') AS HM_RECALL_REASON,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:RECALLOBJECTIONAPPROVEDDATE::VARCHAR AS DATE)), 'NULL') AS RECALL_OBJECTION_APPROVED_DATE,

        -- ========== ENHANCED ANALYTICS FIELDS (12 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:HAPPYSCORE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS HAPPY_SCORE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LATESTBUREAUSCORE::VARCHAR AS NUMERIC(30,0))), 'NULL') AS LATEST_BUREAU_SCORE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:LATESTBUREAUSCOREDATE::VARCHAR AS DATE)), 'NULL') AS LATEST_BUREAU_SCORE_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:USCITIZENSHIP::VARCHAR, 'NULL') AS US_CITIZENSHIP,
        COALESCE(CUSTOM_FIELD_VALUES:CHOSENNAME::VARCHAR, 'NULL') AS CHOSEN_NAME,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CALCULATEDMATURITYDATE::VARCHAR AS DATE)), 'NULL') AS CALCULATED_MATURITY_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CALCULATEDMONTHLYPAYMENT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS CALCULATED_MONTHLY_PAYMENT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PRINCIPALADVANCEPAID::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PRINCIPAL_ADVANCE_PAID,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:"10DAYPAYOFF"::VARCHAR AS NUMERIC(30,2))), 'NULL') AS TEN_DAY_PAYOFF,
        COALESCE(CUSTOM_FIELD_VALUES:ASSETS::VARCHAR, 'NULL') AS ASSETS,
        COALESCE(CUSTOM_FIELD_VALUES:MEMBERACTION::VARCHAR, 'NULL') AS MEMBER_ACTION,
        COALESCE(CUSTOM_FIELD_VALUES:MEMBERPORTALVERSION::VARCHAR, 'NULL') AS MEMBER_PORTAL_VERSION,

        -- ========== DATE TRACKING FIELDS (20 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEENTERED::VARCHAR AS DATE)), 'NULL') AS DATE_ENTERED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATETRANSFERRED::VARCHAR AS DATE)), 'NULL') AS DATE_TRANSFERRED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATECONVERTED::VARCHAR AS DATE)), 'NULL') AS DATE_CONVERTED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATECLOSED::VARCHAR AS DATE)), 'NULL') AS DATE_CLOSED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEREOPENED::VARCHAR AS DATE)), 'NULL') AS DATE_REOPENED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATETERMINATED::VARCHAR AS DATE)), 'NULL') AS DATE_TERMINATED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DATEOFFIRSTNOTICE::VARCHAR AS DATE)), 'NULL') AS DATE_OF_FIRST_NOTICE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:DEATHCONFIRMEDDATE::VARCHAR AS DATE)), 'NULL') AS DEATH_CONFIRMED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CONVERTEDDATE::VARCHAR AS DATE)), 'NULL') AS CONVERTED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:CLOSED::VARCHAR AS DATE)), 'NULL') AS CLOSED,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REOPENEDDATE::VARCHAR AS DATE)), 'NULL') AS REOPENED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:TERMINATEDDATE::VARCHAR AS DATE)), 'NULL') AS TERMINATED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:AGENTPROCESSEDDATE::VARCHAR AS DATE)), 'NULL') AS AGENT_PROCESSED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PROMISETOPAYDATE::VARCHAR AS DATE)), 'NULL') AS PROMISE_TO_PAY_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:REFERRALSHOWNDATE::VARCHAR AS DATE)), 'NULL') AS REFERRAL_SHOWN_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:RECALLOBJECTIONDENIEDDATE::VARCHAR AS DATE)), 'NULL') AS RECALL_OBJECTION_DENIED_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SERVICERSTARTDATE::VARCHAR AS DATE)), 'NULL') AS SERVICER_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SERVICERENDDATE::VARCHAR AS DATE)), 'NULL') AS SERVICER_END_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:AGENTNAMECOMPLETEDPOC::VARCHAR, 'NULL') AS AGENT_NAME_COMPLETED_POC,
        COALESCE(CUSTOM_FIELD_VALUES:SERVICERNAME::VARCHAR, 'NULL') AS SERVICER_NAME,

        -- ========== COMMUNICATION FIELDS (10 fields) ==========
        COALESCE(CUSTOM_FIELD_VALUES:COMMUNICATIONSTATUS::VARCHAR, 'NULL') AS COMMUNICATION_STATUS,
        COALESCE(CUSTOM_FIELD_VALUES:SUSPENDCOMMUNICATION::VARCHAR, 'NULL') AS SUSPEND_COMMUNICATION,
        COALESCE(CUSTOM_FIELD_VALUES:INCLUDEINCREDITREPORTING::VARCHAR, 'NULL') AS INCLUDE_IN_CREDIT_REPORTING,
        COALESCE(CUSTOM_FIELD_VALUES:THIRDPARTYCOMMUNICATIONINDICATOR::VARCHAR, 'NULL') AS THIRD_PARTY_COMMUNICATION_INDICATOR,
        COALESCE(CUSTOM_FIELD_VALUES:THIRDPARTYCONTACT::VARCHAR, 'NULL') AS THIRD_PARTY_CONTACT,
        COALESCE(CUSTOM_FIELD_VALUES:DISABLEAUTOMATIONENGINE::VARCHAR, 'NULL') AS DISABLE_AUTOMATION_ENGINE,
        COALESCE(CUSTOM_FIELD_VALUES:RETENTIONCONFIRMED::VARCHAR, 'NULL') AS RETENTION_CONFIRMED,
        COALESCE(CUSTOM_FIELD_VALUES:ADVERSE_ACTION_TEMPLATE_ID::VARCHAR, 'NULL') AS ADVERSE_ACTION_TEMPLATE_ID,
        COALESCE(CUSTOM_FIELD_VALUES:RECALLOBJECTIONREASON::VARCHAR, 'NULL') AS RECALL_OBJECTION_REASON,
        COALESCE(CUSTOM_FIELD_VALUES:MILITARYBRANCH::VARCHAR, 'NULL') AS MILITARY_BRANCH,

        -- ========== FEMA/DISASTER RELIEF FIELDS (4 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:FEMAACTIVESTARTDATE::VARCHAR AS DATE)), 'NULL') AS FEMA_ACTIVE_START_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:FEMAACTIVEENDDATE::VARCHAR AS DATE)), 'NULL') AS FEMA_ACTIVE_END_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:FEMAONGOINGATREQUESTDATE::VARCHAR AS DATE)), 'NULL') AS FEMA_ONGOING_AT_REQUEST_DATE,
        COALESCE(CUSTOM_FIELD_VALUES:INSURANCESTATUS::VARCHAR, 'NULL') AS INSURANCE_STATUS,

        -- ========== PURCHASE & SALE FIELDS (11 fields) ==========
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PURCHASEAMOUNT::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PURCHASE_AMOUNT,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PURCHASEDATE::VARCHAR AS DATE)), 'NULL') AS PURCHASE_DATE,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:PURCHASEPRICE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS PURCHASE_PRICE,
        COALESCE(CUSTOM_FIELD_VALUES:SALEFLAG::VARCHAR, 'NULL') AS SALE_FLAG,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:SALEDATECONFIGURATION::VARCHAR AS DATE)), 'NULL') AS SALE_DATE_CONFIGURATION,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR1NAME::VARCHAR, 'NULL') AS INVESTOR1_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR1PERCENTAGEOWNERSHIP::VARCHAR, 'NULL') AS INVESTOR1_PERCENTAGE_OWNERSHIP,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:INVESTOR1PRINCIPALATSALE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS INVESTOR1_PRINCIPAL_AT_SALE,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR2NAME::VARCHAR, 'NULL') AS INVESTOR2_NAME,
        COALESCE(CUSTOM_FIELD_VALUES:INVESTOR2PERCENTAGEOWNERSHIP::VARCHAR, 'NULL') AS INVESTOR2_PERCENTAGE_OWNERSHIP,
        COALESCE(TO_VARCHAR(TRY_CAST(CUSTOM_FIELD_VALUES:INVESTOR2PRINCIPALATSALE::VARCHAR AS NUMERIC(30,2))), 'NULL') AS INVESTOR2_PRINCIPAL_AT_SALE,

        -- ========== MISCELLANEOUS FIELDS (5 fields) ==========
        COALESCE(CUSTOM_FIELD_VALUES:REPURPOSE2::VARCHAR, 'NULL') AS REPURPOSE_2,
        COALESCE(CUSTOM_FIELD_VALUES:REPURPOSE3::VARCHAR, 'NULL') AS REPURPOSE_3,
        COALESCE(CUSTOM_FIELD_VALUES:REPURPOSE4::VARCHAR, 'NULL') AS REPURPOSE_4,
        COALESCE(CUSTOM_FIELD_VALUES:REPURPOSE_CF::VARCHAR, 'NULL') AS REPURPOSE_CF,
        COALESCE(CUSTOM_FIELD_VALUES:ATTORNEYPREFERREDMETHODOFCONTACT::VARCHAR, 'NULL') AS ATTORNEY_PREFERRED_METHOD_OF_CONTACT_NEW

    FROM ARCA.FRESHSNOW.TRANSFORMED_CUSTOM_FIELD_ENTITY_CURRENT cs
    INNER JOIN ARCA.FRESHSNOW.LOAN_ENTITY_CURRENT le ON (cs.entity_id = le.settings_id)
    WHERE 1 = 1
      AND cs.entity_type = 'Entity.LoanSettings'
      AND cs.schema_name = ARCA.CONFIG.LMS_SCHEMA()
      AND le.schema_name = ARCA.CONFIG.LMS_SCHEMA()
),
unpivoted_data AS (
    SELECT *
    FROM base_data
    UNPIVOT (
        field_value FOR field_name IN (
            -- FRAUD INVESTIGATION FIELDS
            FRAUD_TYPE, FRAUD_EXPECTED_RESPONSE_DATE,
            FRAUD_JIRA_TICKET_1, FRAUD_JIRA_TICKET_2, FRAUD_JIRA_TICKET_3, FRAUD_JIRA_TICKET_4, FRAUD_JIRA_TICKET_5,
            FRAUD_JIRA_TICKET_6, FRAUD_JIRA_TICKET_7, FRAUD_JIRA_TICKET_8, FRAUD_JIRA_TICKET_9, FRAUD_JIRA_TICKET_10,
            FRAUD_JIRA_TICKET_11, FRAUD_JIRA_TICKET_12, FRAUD_JIRA_TICKET_13, FRAUD_JIRA_TICKET_14, FRAUD_JIRA_TICKET_15,
            FRAUD_JIRA_TICKET_16, FRAUD_JIRA_TICKET_17, FRAUD_JIRA_TICKET_18, FRAUD_JIRA_TICKET_19, FRAUD_JIRA_TICKET_20,
            FRAUD_STATUS_RESULTS_1, FRAUD_STATUS_RESULTS_2, FRAUD_STATUS_RESULTS_3, FRAUD_STATUS_RESULTS_4, FRAUD_STATUS_RESULTS_5,
            FRAUD_STATUS_RESULTS_6, FRAUD_STATUS_RESULTS_7, FRAUD_STATUS_RESULTS_8, FRAUD_STATUS_RESULTS_9, FRAUD_STATUS_RESULTS_10,
            FRAUD_STATUS_RESULTS_11, FRAUD_STATUS_RESULTS_12, FRAUD_STATUS_RESULTS_13, FRAUD_STATUS_RESULTS_14, FRAUD_STATUS_RESULTS_15,
            FRAUD_STATUS_RESULTS_16, FRAUD_STATUS_RESULTS_17, FRAUD_STATUS_RESULTS_18, FRAUD_STATUS_RESULTS_19, FRAUD_STATUS_RESULTS_20,
            -- ATTORNEY FIELDS
            ATTORNEY_ORGANIZATION, ATTORNEY_PHONE_2, ATTORNEY_PHONE_3, ATTORNEY_STREET_1, ATTORNEY_STREET_2, ATTORNEY_STREET_3,
            ATTORNEY_PREFERRED_METHOD_OF_CONTACT,
            -- LOAN MODIFICATION FIELDS
            LOAN_MOD_EFFECTIVE_DATE, LOAN_MOD_BATCH_DATE, LOAN_MOD_FORBEARANCE_START_DATE, LOAN_MOD_FORBEARANCE_LENGTH,
            LOAN_MOD_TERM_EXT_LENGTH, MOD_IN_PROGRESS, PPR_REQUEST_DATE, TPR_MOD_REQUEST_DATE, SSAP_REQUEST_DATE,
            SSAP_MOD_START_DATE, SSAP1_MOD_END_DATE, DSAP_REQUEST_DATE, DISASTER_SKIP_A_PAY_ENROLLMENT_DATE,
            HARDSHIP_NEW_MATURITY_DATE, MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT, MATURITY_DATE_BEFORE_MOD,
            MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE, LOAN_REFINANCED, LOAN_STATUS_AT_TIME_OF_FRAUD,
            LOAN_SUB_STATUS_AT_TIME_OF_FRAUD, NEW_DUE_DATE, SKIPPED_A_PAY, TOTAL_MOD_COUNT,
            TOTAL_MOD_TERM_EXTENSION, TOTAL_NUMBER_OF_SKIPS,
            -- SYSTEM INTEGRATION FIELDS
            CLS_ACCOUNT_ID, CLS_CLEARING_DATE, CLS_CREATED_DATETIME, CLS_LAST_MODIFIED_DATETIME,
            CLS_REVERSAL_REASON_CODE, CLS_REVERSAL_REFERENCE, CLS_REVERSAL_TRANSACTION_NAME, CLS_TRANSACTION_DATE,
            REVERSAL_TRANSACTION_DATETIME, HM_LOAN_ID, PAYOFF_UID, EXTERNAL_DELIVERY_ID, BORROWER_SUBSCRIBER_ID,
            IS_MIGRATED, TENANT_ID_NEW,
            -- LEGAL & COMPLIANCE FIELDS
            BANKRUPTCY_BALANCE, BANKRUPTCY_CHAPTER, DCA_START_DATE, DCA_END_DATE, DCA_CLOSE_DATE,
            DCA_CLOSE_REASON, DCA_RECALL_ACKNOWLEDGMENT_DATE, PROOF_OF_CLAIM_DEADLINE_DATE,
            PROOF_OF_CLAIM_COMPLETED_DATE, CLAIM_COMPLETED_DATE, LAST_DATE_TO_FILE_CLAIMS,
            LAST_DATE_TO_FILE_CLAIMS_GOVT, PLAN_CONFIRMED_DATE, DATE_PLAN_CONFIRMED, FILING_FEE_STATUS,
            CONTINGENCY_STATUS_CODE, CONTINGENCY_STATUS_CODE_APPLY_DATE, DISPOSITION, DISCHARGED_DATE,
            DATE_DISCHARGED, DATE_DISMISSED, JOINT_DEBTOR_DISCHARGED_DATE, JOINT_DEBTOR_DISMISSED_DATE,
            DATE_JOINT_DEBTOR_DISCHARGED, DATE_JOINT_DEBTOR_DISMISSED, JOINT_DEBTOR_DISPOSITION,
            SCRA_CERTIFIED, SCRA_REQUEST_RECEIVED_DATE, ACTIVE_DUTY_START_DATE, ACTIVE_DUTY_END_DATE,
            -- SETTLEMENT ENHANCEMENT FIELDS
            APPROVED_SETTLEMENT_AMOUNT, AMOUNT_DUE_TO_HAPPY_MONEY, SETTLEMENT_TYPE,
            DEBT_SETTLEMENT_PAYMENT_PLAN_STATUS, DEBT_SETTLEMENT_PAYMENTS_EXPECTED, HM_RECALL_DATE,
            HM_RECALL_REASON, RECALL_OBJECTION_APPROVED_DATE,
            -- ENHANCED ANALYTICS FIELDS
            HAPPY_SCORE, LATEST_BUREAU_SCORE, LATEST_BUREAU_SCORE_DATE, US_CITIZENSHIP, CHOSEN_NAME,
            CALCULATED_MATURITY_DATE, CALCULATED_MONTHLY_PAYMENT, PRINCIPAL_ADVANCE_PAID, TEN_DAY_PAYOFF,
            ASSETS, MEMBER_ACTION, MEMBER_PORTAL_VERSION,
            -- DATE TRACKING FIELDS
            DATE_ENTERED, DATE_TRANSFERRED, DATE_CONVERTED, DATE_CLOSED, DATE_REOPENED, DATE_TERMINATED,
            DATE_OF_FIRST_NOTICE, DEATH_CONFIRMED_DATE, CONVERTED_DATE, CLOSED, REOPENED_DATE,
            TERMINATED_DATE, AGENT_PROCESSED_DATE, PROMISE_TO_PAY_DATE, REFERRAL_SHOWN_DATE,
            RECALL_OBJECTION_DENIED_DATE, SERVICER_START_DATE, SERVICER_END_DATE, AGENT_NAME_COMPLETED_POC,
            SERVICER_NAME,
            -- COMMUNICATION FIELDS
            COMMUNICATION_STATUS, SUSPEND_COMMUNICATION, INCLUDE_IN_CREDIT_REPORTING,
            THIRD_PARTY_COMMUNICATION_INDICATOR, THIRD_PARTY_CONTACT, DISABLE_AUTOMATION_ENGINE,
            RETENTION_CONFIRMED, ADVERSE_ACTION_TEMPLATE_ID, RECALL_OBJECTION_REASON, MILITARY_BRANCH,
            -- FEMA/DISASTER RELIEF FIELDS
            FEMA_ACTIVE_START_DATE, FEMA_ACTIVE_END_DATE, FEMA_ONGOING_AT_REQUEST_DATE, INSURANCE_STATUS,
            -- PURCHASE & SALE FIELDS
            PURCHASE_AMOUNT, PURCHASE_DATE, PURCHASE_PRICE, SALE_FLAG, SALE_DATE_CONFIGURATION,
            INVESTOR1_NAME, INVESTOR1_PERCENTAGE_OWNERSHIP, INVESTOR1_PRINCIPAL_AT_SALE, INVESTOR2_NAME,
            INVESTOR2_PERCENTAGE_OWNERSHIP, INVESTOR2_PRINCIPAL_AT_SALE,
            -- MISCELLANEOUS FIELDS
            REPURPOSE_2, REPURPOSE_3, REPURPOSE_4, REPURPOSE_CF, ATTORNEY_PREFERRED_METHOD_OF_CONTACT_NEW
        )
    )
),
field_totals AS (
    SELECT
        field_name,
        COUNT(*) AS total_records
    FROM unpivoted_data
    GROUP BY field_name
),
value_counts AS (
    SELECT
        field_name,
        COALESCE(TO_VARCHAR(field_value), 'NULL') AS value,
        COUNT(*) AS record_count
    FROM unpivoted_data
    GROUP BY field_name, COALESCE(TO_VARCHAR(field_value), 'NULL')
)
SELECT
    vc.field_name AS FIELD_NAME,
    vc.value AS VALUE,
    vc.record_count AS RECORD_COUNT,
    ROUND((vc.record_count::FLOAT / ft.total_records) * 100, 2) AS PERCENTAGE
FROM value_counts vc
INNER JOIN field_totals ft ON vc.field_name = ft.field_name
ORDER BY vc.field_name, vc.record_count DESC;
