-- Near-NULL Fields: 27 Fields with Minimal Data Population
-- Based on ticket-3 analysis validation results
-- Dataset: 127,023 loan_management_system records (September 2025)
-- These fields show some data but very low population rates

--near_null_fields_2025-09-30
SELECT
    COUNT(*) as total_records,

    -- Fraud Investigation (13 fields - slots 9-14 plus contact email)
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET9::VARCHAR AS FRAUD_JIRA_TICKET_9,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET10::VARCHAR AS FRAUD_JIRA_TICKET_10,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET11::VARCHAR AS FRAUD_JIRA_TICKET_11,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET12::VARCHAR AS FRAUD_JIRA_TICKET_12,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET13::VARCHAR AS FRAUD_JIRA_TICKET_13,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET14::VARCHAR AS FRAUD_JIRA_TICKET_14,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS9::VARCHAR AS FRAUD_STATUS_RESULTS_9,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS10::VARCHAR AS FRAUD_STATUS_RESULTS_10,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS11::VARCHAR AS FRAUD_STATUS_RESULTS_11,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS12::VARCHAR AS FRAUD_STATUS_RESULTS_12,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS13::VARCHAR AS FRAUD_STATUS_RESULTS_13,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS14::VARCHAR AS FRAUD_STATUS_RESULTS_14,
    CUSTOM_FIELD_VALUES:FRAUDCONTACTEMAIL::VARCHAR AS FRAUD_CONTACT_EMAIL,

    -- Bankruptcy (4 fields)
    --STILL NEEDED DO NOT REMOVE: CUSTOM_FIELD_VALUES:BANKRUPTCYCHAPTER::VARCHAR AS BANKRUPTCY_CHAPTER,
    CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWLOANAMOUNT::VARCHAR AS BANKRUPTCY_ORDERED_NEW_LOAN_AMOUNT,
    CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWPAYMENTAMOUNT::VARCHAR AS BANKRUPTCY_ORDERED_NEW_PAYMENT_AMOUNT,
    CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNUMBEROFPAYMENTS::VARCHAR AS BANKRUPTCY_ORDERED_NUMBER_OF_PAYMENTS,
    CUSTOM_FIELD_VALUES:DATECLOSED::VARCHAR AS DATE_CLOSED,

    -- SCRA/Military (4 fields)
    --ALL 4 FIELDS BELOW ARE STILL NEEDED DO NOT REMOVE
    /*CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYENDDATE5::VARCHAR AS SCRA_ACTIVE_DUTY_END_DATE5,
    CUSTOM_FIELD_VALUES:SCRAACTIVEDUTYSTARTDATE5::VARCHAR AS SCRA_ACTIVE_DUTY_START_DATE5,
    CUSTOM_FIELD_VALUES:SCRADECLINEREASON::VARCHAR AS SCRA_DECLINE_REASON,
    CUSTOM_FIELD_VALUES:SCRANOTIFICATIONDATE5::VARCHAR AS SCRA_NOTIFICATION_DATE5,*/

    -- Skip-A-Pay/Hardship (5 fields)
    CUSTOM_FIELD_VALUES:DSAP1MODENDDATE::VARCHAR AS DSAP1_MOD_END_DATE,
    CUSTOM_FIELD_VALUES:DSAP2MODENDDATE::VARCHAR AS DSAP2_MOD_END_DATE,
    CUSTOM_FIELD_VALUES:DSAPMODSTARTDATE::VARCHAR AS DSAP_MOD_START_DATE,
    CUSTOM_FIELD_VALUES:SSAP1MODENDDATE::VARCHAR AS SSAP1_MOD_END_DATE,
    CUSTOM_FIELD_VALUES:SSAPMODSTARTDATE::VARCHAR AS SSAP_MOD_START_DATE,
    CUSTOM_FIELD_VALUES:STANDARDSKIPAPAYENROLLMENTSTARTDATE::VARCHAR AS STANDARD_SKIP_A_PAY_ENROLLMENT_START_DATE,
    CUSTOM_FIELD_VALUES:HARDSHIPENROLLMENTSTARTDATE::VARCHAR AS HARDSHIP_ENROLLMENT_START_DATE,

    -- Loan Modification (1 field)
    CUSTOM_FIELD_VALUES:PAYMENTAMOUNTBEFOREMODIFICATION::VARCHAR AS PAYMENT_AMOUNT_BEFORE_MODIFICATION,

    -- Settlement (2 fields)
    CUSTOM_FIELD_VALUES:UNPAIDSETTLEMENTBALANCE::VARCHAR AS UNPAID_SETTLEMENT_BALANCE,
    CUSTOM_FIELD_VALUES:DEBTREPURCHASESTATUS::VARCHAR AS DEBT_REPURCHASE_STATUS,

    -- Debt Sale (2 fields)
    CUSTOM_FIELD_VALUES:DEBTSALESTATUS::VARCHAR AS DEBT_SALE_STATUS,
    CUSTOM_FIELD_VALUES:SOLDDATE::VARCHAR AS SOLD_DATE,

    -- Investor (1 field)
    CUSTOM_FIELD_VALUES:INVESTOR15::VARCHAR AS INVESTOR15,

    -- Trustage Insurance (1 field)
    CUSTOM_FIELD_VALUES:TRUSTAGECLAIMNUMBER::VARCHAR AS TRUSTAGE_CLAIM_NUMBER,

    -- Funding/Origination (1 field)
    CUSTOM_FIELD_VALUES:FUNDINGCANCELLATIONREASON::VARCHAR AS FUNDING_CANCELLATION_REASON,

    -- Miscellaneous/Legacy (5 fields)
    CUSTOM_FIELD_VALUES:HARDSHIPENROLLMENTENDDATE::VARCHAR AS HARDSHIP_ENROLLMENT_END_DATE,
    CUSTOM_FIELD_VALUES:INCOMETYPE5::VARCHAR AS INCOME_TYPE5,
    CUSTOM_FIELD_VALUES:STATERATE::VARCHAR AS STATE_RATE,
    CUSTOM_FIELD_VALUES:TENANTID::VARCHAR AS TENANT_ID,
    CUSTOM_FIELD_VALUES:"10DAYPAYOFF"::VARCHAR AS TEN_DAY_PAYOFF

FROM ARCA.FRESHSNOW.TRANSFORMED_CUSTOM_FIELD_ENTITY_CURRENT cs
INNER JOIN ARCA.FRESHSNOW.LOAN_ENTITY_CURRENT le ON (cs.entity_id = le.settings_id)
WHERE cs.entity_type = 'Entity.LoanSettings'
  AND cs.schema_name = ARCA.CONFIG.loan_management_system_SCHEMA()
  AND le.schema_name = ARCA.CONFIG.loan_management_system_SCHEMA()
GROUP BY ALL;

-- This query shows fields with minimal data population for potential Phase 2 cleanup
