-- Validation Query: 199 Fields That Are Truly 100% NULL
-- Based on ticket-3 analysis validation results
-- Dataset: 127,023 loan_management_system records (September 2025)
--100_percent_null_fields_2025-09-30
SELECT
    COUNT(*) as total_records,

    -- Repossession Fields (13 - all 100% NULL)
    CUSTOM_FIELD_VALUES:REPOSSESSIONCASENUMBER::VARCHAR AS REPOSSESSION_CASE_NUMBER,
    CUSTOM_FIELD_VALUES:REPOSSESSIONCITY::VARCHAR AS REPOSSESSION_CITY,
    CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYCONTACTNAME::VARCHAR AS REPOSSESSION_COMPANY_CONTACT_NAME,
    CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYEMAILADDRESS::VARCHAR AS REPOSSESSION_COMPANY_EMAIL_ADDRESS,
    CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYNAME::VARCHAR AS REPOSSESSION_COMPANY_NAME,
    CUSTOM_FIELD_VALUES:REPOSSESSIONCOMPANYPHONENUMBER::VARCHAR AS REPOSSESSION_COMPANY_PHONE_NUMBER,
    CUSTOM_FIELD_VALUES:REPOSSESSIONCOUNTY::VARCHAR AS REPOSSESSION_COUNTY,
    CUSTOM_FIELD_VALUES:REPOSSESSIONDATE::VARCHAR AS REPOSSESSION_DATE,
    CUSTOM_FIELD_VALUES:REPOSSESSIONMANAGERDECLINEDATE::VARCHAR AS REPOSSESSION_MANAGER_DECLINE_DATE,
    CUSTOM_FIELD_VALUES:REPOSSESSIONREVIEWDECISION::VARCHAR AS REPOSSESSION_REVIEW_DECISION,
    CUSTOM_FIELD_VALUES:REPOSSESSIONSTATE::VARCHAR AS REPOSSESSION_STATE,
    CUSTOM_FIELD_VALUES:CUSTOMERREDEEMEDCOLLATERAL::VARCHAR AS CUSTOMER_REDEEMED_COLLATERAL,
    CUSTOM_FIELD_VALUES:BALANCEATTIMEOFDEBTSAL::VARCHAR AS BALANCE_AT_TIME_OF_DEBT_SALE,

    -- Fraud Investigation Extended Slots (12 - slots 15-20 only)
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET15::VARCHAR AS FRAUD_JIRA_TICKET_15,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET16::VARCHAR AS FRAUD_JIRA_TICKET_16,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET17::VARCHAR AS FRAUD_JIRA_TICKET_17,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET18::VARCHAR AS FRAUD_JIRA_TICKET_18,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET19::VARCHAR AS FRAUD_JIRA_TICKET_19,
    CUSTOM_FIELD_VALUES:FRAUDJIRATICKET20::VARCHAR AS FRAUD_JIRA_TICKET_20,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS15::VARCHAR AS FRAUD_STATUS_RESULTS_15,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS16::VARCHAR AS FRAUD_STATUS_RESULTS_16,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS17::VARCHAR AS FRAUD_STATUS_RESULTS_17,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS18::VARCHAR AS FRAUD_STATUS_RESULTS_18,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS19::VARCHAR AS FRAUD_STATUS_RESULTS_19,
    CUSTOM_FIELD_VALUES:FRAUDSTATUSRESULTS20::VARCHAR AS FRAUD_STATUS_RESULTS_20,

    -- Investor Fields (14 - INVESTOR1-14 only, INVESTOR15 has data)
    CUSTOM_FIELD_VALUES:INVESTOR1::VARCHAR AS INVESTOR1,
    CUSTOM_FIELD_VALUES:INVESTOR2::VARCHAR AS INVESTOR2,
    CUSTOM_FIELD_VALUES:INVESTOR3::VARCHAR AS INVESTOR3,
    CUSTOM_FIELD_VALUES:INVESTOR4::VARCHAR AS INVESTOR4,
    CUSTOM_FIELD_VALUES:INVESTOR5::VARCHAR AS INVESTOR5,
    CUSTOM_FIELD_VALUES:INVESTOR6::VARCHAR AS INVESTOR6,
    CUSTOM_FIELD_VALUES:INVESTOR7::VARCHAR AS INVESTOR7,
    CUSTOM_FIELD_VALUES:INVESTOR8::VARCHAR AS INVESTOR8,
    CUSTOM_FIELD_VALUES:INVESTOR9::VARCHAR AS INVESTOR9,
    CUSTOM_FIELD_VALUES:INVESTOR10::VARCHAR AS INVESTOR10,
    CUSTOM_FIELD_VALUES:INVESTOR11::VARCHAR AS INVESTOR11,
    CUSTOM_FIELD_VALUES:INVESTOR12::VARCHAR AS INVESTOR12,
    CUSTOM_FIELD_VALUES:INVESTOR13::VARCHAR AS INVESTOR13,
    CUSTOM_FIELD_VALUES:INVESTOR14::VARCHAR AS INVESTOR14,

    -- CLS System Integration (9 - all 100% NULL)
    CUSTOM_FIELD_VALUES:CLSACCOUNTID::VARCHAR AS CLS_ACCOUNT_ID,
    CUSTOM_FIELD_VALUES:CLSCLEARINGDATE::VARCHAR AS CLS_CLEARING_DATE,
    CUSTOM_FIELD_VALUES:CLSCREATEDDATETIME::VARCHAR AS CLS_CREATED_DATETIME,
    CUSTOM_FIELD_VALUES:CLSLASTMODIFIEDDATETIME::VARCHAR AS CLS_LAST_MODIFIED_DATETIME,
    CUSTOM_FIELD_VALUES:CLSREVERSALREASONCODE::VARCHAR AS CLS_REVERSAL_REASON_CODE,
    CUSTOM_FIELD_VALUES:CLSREVERSALREFERENCE::VARCHAR AS CLS_REVERSAL_REFERENCE,
    CUSTOM_FIELD_VALUES:CLSREVERSALTRANSACTIONNAME::VARCHAR AS CLS_REVERSAL_TRANSACTION_NAME,
    CUSTOM_FIELD_VALUES:CLSTRANSACTIONDATE::VARCHAR AS CLS_TRANSACTION_DATE,
    CUSTOM_FIELD_VALUES:REVERSALTRANSACTIONDATETIME::VARCHAR AS REVERSAL_TRANSACTION_DATETIME,

    -- Bankruptcy Fields (16 - removed 4 with data)
    CUSTOM_FIELD_VALUES:BANKRUPTCYBALANCE::VARCHAR AS BANKRUPTCY_BALANCE,
    CUSTOM_FIELD_VALUES:BANKRUPTCYORDEREDNEWINTERESTRATE::VARCHAR AS BANKRUPTCY_ORDERED_NEW_INTEREST_RATE,
    CUSTOM_FIELD_VALUES:BANKRUPTCYVENDOR::VARCHAR AS BANKRUPTCY_VENDOR,
    CUSTOM_FIELD_VALUES:DATECONVERTED::VARCHAR AS DATE_CONVERTED,
    CUSTOM_FIELD_VALUES:DATEDISCHARGED::VARCHAR AS DATE_DISCHARGED,
    CUSTOM_FIELD_VALUES:DATEDISMISSED::VARCHAR AS DATE_DISMISSED,
    CUSTOM_FIELD_VALUES:DATEJOINTDEBTORDISCHARGED::VARCHAR AS DATE_JOINT_DEBTOR_DISCHARGED,
    CUSTOM_FIELD_VALUES:DATEJOINTDEBTORDISMISSED::VARCHAR AS DATE_JOINT_DEBTOR_DISMISSED,
    CUSTOM_FIELD_VALUES:DATEPLANCONFIRMED::VARCHAR AS DATE_PLAN_CONFIRMED,
    CUSTOM_FIELD_VALUES:DATEREOPENED::VARCHAR AS DATE_REOPENED,
    CUSTOM_FIELD_VALUES:DATETERMINATED::VARCHAR AS DATE_TERMINATED,
    CUSTOM_FIELD_VALUES:DATETRANSFERRED::VARCHAR AS DATE_TRANSFERRED,
    CUSTOM_FIELD_VALUES:JOINTDEBTORDISCHARGEDDATE::VARCHAR AS JOINT_DEBTOR_DISCHARGED_DATE,
    CUSTOM_FIELD_VALUES:JOINTDEBTORDISMISSEDDATE::VARCHAR AS JOINT_DEBTOR_DISMISSED_DATE,
    CUSTOM_FIELD_VALUES:JOINTDEBTORDISPOSITION::VARCHAR AS JOINT_DEBTOR_DISPOSITION,

    -- SCRA/Military Fields (8 - removed 4 with data)
    CUSTOM_FIELD_VALUES:ACTIVEDUTYENDDATE::VARCHAR AS ACTIVE_DUTY_END_DATE,
    CUSTOM_FIELD_VALUES:ACTIVEDUTYSTARTDATE::VARCHAR AS ACTIVE_DUTY_START_DATE,
    CUSTOM_FIELD_VALUES:MILITARYBRANCH::VARCHAR AS MILITARY_BRANCH,
    CUSTOM_FIELD_VALUES:SCRACERTIFIED::VARCHAR AS SCRA_CERTIFIED,
    CUSTOM_FIELD_VALUES:SCRAENDDATE::VARCHAR AS SCRA_END_DATE,
    CUSTOM_FIELD_VALUES:SCRAORDERSRECEIVEDDATE::VARCHAR AS SCRA_ORDERS_RECEIVED_DATE,
    CUSTOM_FIELD_VALUES:SCRAREQUESTRECEIVED::VARCHAR AS SCRA_REQUEST_RECEIVED_DATE,
    CUSTOM_FIELD_VALUES:SCRASTARTDATE::VARCHAR AS SCRA_START_DATE,

    -- Skip-A-Pay/Hardship Fields (4 - removed 5 with data)
    CUSTOM_FIELD_VALUES:DISASTERSKIPAPAYENROLLMENT::VARCHAR AS DISASTER_SKIP_A_PAY_ENROLLMENT,
    CUSTOM_FIELD_VALUES:SSAP2MODENDDATE::VARCHAR AS SSAP2_MOD_END_DATE,

    -- Loan Modification Fields (7 - removed 1 with data)
    CUSTOM_FIELD_VALUES:MODTERMEXTENSION::VARCHAR AS MOD_TERM_EXTENSION,
    CUSTOM_FIELD_VALUES:PERCENTAGEOFCURRENTPAYMENT::VARCHAR AS PERCENTAGE_OF_CURRENT_PAYMENT,
    CUSTOM_FIELD_VALUES:MANAGERREVIEWPERCENTAGEOFCURRENTPAYMENT::VARCHAR AS MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT,
    CUSTOM_FIELD_VALUES:MANAGERREVIEWPERCENTAGEOFCURRENTPAYMENTC::VARCHAR AS MANAGER_REVIEW_PERCENTAGE_OF_CURRENT_PAYMENT_C,
    CUSTOM_FIELD_VALUES:MEMBERREQUESTEDPAYMENTREDUCTIONRANGE::VARCHAR AS MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE,
    CUSTOM_FIELD_VALUES:MEMBERREQUESTEDPAYMENTREDUCTIONRANGEC::VARCHAR AS MEMBER_REQUESTED_PAYMENT_REDUCTION_RANGE_C,
    CUSTOM_FIELD_VALUES:MATURITYDATEBEFOREMODC::VARCHAR AS MATURITY_DATE_BEFORE_MOD_C,

    -- DCA/Collections Fields (8 - all 100% NULL)
    CUSTOM_FIELD_VALUES:DCACLOSEDATE::VARCHAR AS DCA_CLOSE_DATE,
    CUSTOM_FIELD_VALUES:DCACLOSEREASON::VARCHAR AS DCA_CLOSE_REASON,
    CUSTOM_FIELD_VALUES:DCAENDDATE::VARCHAR AS DCA_END_DATE,
    CUSTOM_FIELD_VALUES:DCARECALLACKNOWLEDGMENTDATE::VARCHAR AS DCA_RECALL_ACKNOWLEDGMENT_DATE,
    CUSTOM_FIELD_VALUES:DCASTARTDATE::VARCHAR AS DCA_START_DATE,
    CUSTOM_FIELD_VALUES:AMOUNTDUETOHAPPYMONEYDCA::VARCHAR AS AMOUNT_DUE_TO_HAPPY_MONEY_DCA,
    CUSTOM_FIELD_VALUES:FEERATEDCA::VARCHAR AS FEE_RATE_DCA,
    CUSTOM_FIELD_VALUES:THIRDPARTYCOLLECTIONAGENCY::VARCHAR AS THIRD_PARTY_COLLECTION_AGENCY,

    -- Settlement Fields (5 - removed 2 with data)
    CUSTOM_FIELD_VALUES:SETTLEMENTAGREEMENTAMOUNTDCA::VARCHAR AS SETTLEMENT_AGREEMENT_AMOUNT_DCA,
    CUSTOM_FIELD_VALUES:SETTLEMENTCOMPANYDCA::VARCHAR AS SETTLEMENT_COMPANY_DCA,
    CUSTOM_FIELD_VALUES:SETTLEMENTENDDATE::VARCHAR AS SETTLEMENT_END_DATE,
    CUSTOM_FIELD_VALUES:SETTLEMENTSETUPDATE::VARCHAR AS SETTLEMENT_SETUP_DATE,
    CUSTOM_FIELD_VALUES:SETTLEMENTSTATUSDCA::VARCHAR AS SETTLEMENT_STATUS_DCA,

    -- Debt Sale Fields (6 - removed 2 with data)
    CUSTOM_FIELD_VALUES:DEBTBUYER::VARCHAR AS DEBT_BUYER,
    CUSTOM_FIELD_VALUES:DEBTREQUESTSENTTEST::VARCHAR AS DEBT_REQUEST_SENT_TEST,
    CUSTOM_FIELD_VALUES:DEBTREQUESTTEST::VARCHAR AS DEBT_REQUEST_TEST,
    CUSTOM_FIELD_VALUES:SECONDARYBUYER::VARCHAR AS SECONDARY_BUYER,
    CUSTOM_FIELD_VALUES:SECONDARYSELLER::VARCHAR AS SECONDARY_SELLER,
    CUSTOM_FIELD_VALUES:DATESUBMITTEDTOREFERRER::VARCHAR AS DATE_SUBMITTED_TO_REFERRER,

    -- Attorney Fields (7 - all 100% NULL)
    CUSTOM_FIELD_VALUES:ATTORNEYORGANIZATION::VARCHAR AS ATTORNEY_ORGANIZATION,
    CUSTOM_FIELD_VALUES:ATTORNEYPHONE2::VARCHAR AS ATTORNEY_PHONE_2,
    CUSTOM_FIELD_VALUES:ATTORNEYPHONE3::VARCHAR AS ATTORNEY_PHONE_3,
    CUSTOM_FIELD_VALUES:ATTORNEYPREFERREDMETHODOFCONTACTC::VARCHAR AS ATTORNEY_PREFERRED_METHOD_OF_CONTACT_C,
    CUSTOM_FIELD_VALUES:ATTORNEYSTREET1::VARCHAR AS ATTORNEY_STREET_1,
    CUSTOM_FIELD_VALUES:ATTORNEYSTREET2::VARCHAR AS ATTORNEY_STREET_2,
    CUSTOM_FIELD_VALUES:ATTORNEYSTREET3::VARCHAR AS ATTORNEY_STREET_3,

    -- Trustage Insurance Fields (4 - removed 1 with data)
    CUSTOM_FIELD_VALUES:TRUSTAGEENDDATE::VARCHAR AS TRUSTAGE_END_DATE,
    CUSTOM_FIELD_VALUES:TRUSTAGEPAYMENTGUARDINSURANCEPROGRAMENROLLMENTDATE::VARCHAR AS TRUSTAGE_PAYMENT_GUARD_INSURANCE_PROGRAM_ENROLLMENT_DATE,
    CUSTOM_FIELD_VALUES:TRUSTAGESTARTDATE::VARCHAR AS TRUSTAGE_START_DATE,
    CUSTOM_FIELD_VALUES:HARDSHIPDESCRIPTION::VARCHAR AS HARDSHIP_DESCRIPTION,

    -- Credit Bureau/Reporting Fields (8 - all 100% NULL)
    CUSTOM_FIELD_VALUES:BORROWERSUBSCRIBERID::VARCHAR AS BORROWER_SUBSCRIBER_ID,
    CUSTOM_FIELD_VALUES:LATESTBUREAUSCORE::VARCHAR AS LATEST_BUREAU_SCORE,
    CUSTOM_FIELD_VALUES:LATESTBUREAUSCOREDATE::VARCHAR AS LATEST_BUREAU_SCORE_DATE,
    CUSTOM_FIELD_VALUES:REFRESHEDBUREAUSCORE::VARCHAR AS REFRESHED_BUREAU_SCORE,
    CUSTOM_FIELD_VALUES:REFRESHEDBUREAUSCOREDATE::VARCHAR AS REFRESHED_BUREAU_SCORE_DATE,
    CUSTOM_FIELD_VALUES:CORRECTEDCREDITREPORTINGITEM::VARCHAR AS CORRECTED_CREDIT_REPORTING_ITEM,
    CUSTOM_FIELD_VALUES:INCORRECTCREDITREPORTINGITEM::VARCHAR AS INCORRECT_CREDIT_REPORTING_ITEM,
    CUSTOM_FIELD_VALUES:COMPLAINTSTATUS::VARCHAR AS COMPLAINT_STATUS,

    -- Servicer/Third-Party Fields (6 - all 100% NULL)
    CUSTOM_FIELD_VALUES:SERVICERENDDATE::VARCHAR AS SERVICER_END_DATE,
    CUSTOM_FIELD_VALUES:SERVICERNAME::VARCHAR AS SERVICER_NAME,
    CUSTOM_FIELD_VALUES:SERVICERSTARTDATE::VARCHAR AS SERVICER_START_DATE,
    CUSTOM_FIELD_VALUES:THIRDPARTYCOMMUNICATIONWITHHMABOUTDEBT::VARCHAR AS THIRD_PARTY_COMMUNICATION_WITH_HM_ABOUT_DEBT,
    CUSTOM_FIELD_VALUES:THIRDPARTYCONTACT::VARCHAR AS THIRD_PARTY_CONTACT,
    CUSTOM_FIELD_VALUES:CREDITCOUNSELORCOMPANY::VARCHAR AS CREDIT_COUNSELOR_COMPANY,

    -- Recall/Objection Fields (5 - all 100% NULL)
    CUSTOM_FIELD_VALUES:HMRECALLDATE::VARCHAR AS HM_RECALL_DATE,
    CUSTOM_FIELD_VALUES:HMRECALLREASON::VARCHAR AS HM_RECALL_REASON,
    CUSTOM_FIELD_VALUES:RECALLOBJECTIONAPPROVEDDATE::VARCHAR AS RECALL_OBJECTION_APPROVED_DATE,
    CUSTOM_FIELD_VALUES:RECALLOBJECTIONDENIEDDATE::VARCHAR AS RECALL_OBJECTION_DENIED_DATE,
    CUSTOM_FIELD_VALUES:RECALLOBJECTIONREASON::VARCHAR AS RECALL_OBJECTION_REASON,

    -- Funding/Origination Fields (5 - removed 1 with data)
    CUSTOM_FIELD_VALUES:FUNDINGSTATUS::VARCHAR AS FUNDING_STATUS,
    CUSTOM_FIELD_VALUES:INDIRECTAMOUNTORIGINATIONINTEREST::VARCHAR AS INDIRECT_AMOUNT_ORIGINATION_INTEREST,
    CUSTOM_FIELD_VALUES:INDIRECTLENDERORIGINATIONFEE::VARCHAR AS INDIRECT_LENDER_ORIGINATION_FEE,
    CUSTOM_FIELD_VALUES:INDIRECTPURCHASEDATE::VARCHAR AS INDIRECT_PURCHASE_DATE,
    CUSTOM_FIELD_VALUES:ORIGINATIONFEE::VARCHAR AS ORIGINATION_FEE,

    -- Portfolio/Channel Fields (3 - all 100% NULL)
    CUSTOM_FIELD_VALUES:PORTFOLIOIDC::VARCHAR AS PORTFOLIO_ID_C,
    CUSTOM_FIELD_VALUES:PORTFOLIONAMEC::VARCHAR AS PORTFOLIO_NAME_C,
    CUSTOM_FIELD_VALUES:CHANNEL::VARCHAR AS CHANNEL,

    -- Miscellaneous/Legacy Fields (44 - removed 3 with data)
    CUSTOM_FIELD_VALUES:ADVERSEACTIONTEMPLATEID::VARCHAR AS ADVERSE_ACTION_TEMPLATE_ID,
    CUSTOM_FIELD_VALUES:AGENTNAMECOMPLETED::VARCHAR AS AGENT_NAME_COMPLETED_POC,
    CUSTOM_FIELD_VALUES:AMOUNTDUETOHAPPYMONEY::VARCHAR AS AMOUNT_DUE_TO_HAPPY_MONEY,
    CUSTOM_FIELD_VALUES:CHOSENNAME::VARCHAR AS CHOSEN_NAME,
    CUSTOM_FIELD_VALUES:CLAIMCOMPLETEDDATE::VARCHAR AS CLAIM_COMPLETED_DATE,
    CUSTOM_FIELD_VALUES:COMMUNICATIONSTATUS::VARCHAR AS COMMUNICATION_STATUS,
    CUSTOM_FIELD_VALUES:CONTINGENCYSTATUSCODE::VARCHAR AS CONTINGENCY_STATUS_CODE,
    CUSTOM_FIELD_VALUES:CONTINGENCYSTATUSCODEAPPLYDATE::VARCHAR AS CONTINGENCY_STATUS_CODE_APPLY_DATE,
    CUSTOM_FIELD_VALUES:CONVERTEDDATE::VARCHAR AS CONVERTED_DATE,
    CUSTOM_FIELD_VALUES:DATEENTERED::VARCHAR AS DATE_ENTERED,
    CUSTOM_FIELD_VALUES:DEATHCONFIRMEDDATE::VARCHAR AS DEATH_CONFIRMED_DATE,
    CUSTOM_FIELD_VALUES:DISCHARGEDDATE::VARCHAR AS DISCHARGED_DATE,
    CUSTOM_FIELD_VALUES:DISPOSITION::VARCHAR AS DISPOSITION,
    CUSTOM_FIELD_VALUES:DNU::VARCHAR AS DNU,
    CUSTOM_FIELD_VALUES:EXPECTEDRESPONSEDATE::VARCHAR AS EXPECTED_RESPONSE_DATE,
    CUSTOM_FIELD_VALUES:EXTERNALDELIVERYID::VARCHAR AS EXTERNAL_DELIVERY_ID,
    CUSTOM_FIELD_VALUES:FEMAACTIVEENDDATE::VARCHAR AS FEMA_ACTIVE_END_DATE,
    CUSTOM_FIELD_VALUES:FEMAACTIVESTARTDATE::VARCHAR AS FEMA_ACTIVE_START_DATE,
    CUSTOM_FIELD_VALUES:FILINGFEESTATUS::VARCHAR AS FILING_FEE_STATUS,
    CUSTOM_FIELD_VALUES:ISMIGRATED::VARCHAR AS IS_MIGRATED,
    CUSTOM_FIELD_VALUES:LASTDATETOFILECLAIMS::VARCHAR AS LAST_DATE_TO_FILE_CLAIMS,
    CUSTOM_FIELD_VALUES:LASTDATETOFILECLAIMSGOVT::VARCHAR AS LAST_DATE_TO_FILE_CLAIMS_GOVT,
    CUSTOM_FIELD_VALUES:MEMBERPORTALVERSION::VARCHAR AS MEMBER_PORTAL_VERSION,
    CUSTOM_FIELD_VALUES:NEWDUEDATE::VARCHAR AS NEW_DUE_DATE,
    CUSTOM_FIELD_VALUES:NUMBEROFSKIPS::VARCHAR AS NUMBER_OF_SKIPS,
    CUSTOM_FIELD_VALUES:NUMBERPAYMENTSSKIPPED::VARCHAR AS NUMBER_PAYMENTS_SKIPPED,
    CUSTOM_FIELD_VALUES:PAYOFFUID::VARCHAR AS PAYOFF_UID,
    CUSTOM_FIELD_VALUES:PLANCONFIRMEDDATE::VARCHAR AS PLAN_CONFIRMED_DATE,
    CUSTOM_FIELD_VALUES:PROMISETOPAYDATE::VARCHAR AS PROMISE_TO_PAY_DATE,
    CUSTOM_FIELD_VALUES:PROMOPERIODEXPIRATIONDATE::VARCHAR AS PROMO_PERIOD_EXPIRATION_DATE,
    CUSTOM_FIELD_VALUES:REAFFIRMATIONDATE::VARCHAR AS REAFFIRMATION_DATE,
    CUSTOM_FIELD_VALUES:REFERRALSHOWNDATE::VARCHAR AS REFERRAL_SHOWN_DATE,
    CUSTOM_FIELD_VALUES:REOPENEDDATE::VARCHAR AS REOPENED_DATE,
    CUSTOM_FIELD_VALUES:REPURPOSE2::VARCHAR AS REPURPOSE_2,
    CUSTOM_FIELD_VALUES:REPURPOSE3::VARCHAR AS REPURPOSE_3,
    CUSTOM_FIELD_VALUES:REPURPOSE4::VARCHAR AS REPURPOSE_4,
    CUSTOM_FIELD_VALUES:REPURPOSECF::VARCHAR AS REPURPOSE_CF,
    CUSTOM_FIELD_VALUES:REQUESTEDFIRSTPAYMENTDATE::VARCHAR AS REQUESTED_FIRST_PAYMENT_DATE,
    CUSTOM_FIELD_VALUES:SALEDATECONFIGURATION::VARCHAR AS SALE_DATE_CONFIGURATION,
    CUSTOM_FIELD_VALUES:SALEFLAG::VARCHAR AS SALE_FLAG,
    CUSTOM_FIELD_VALUES:SOURCEOFREFERRAL::VARCHAR AS SOURCE_OF_REFERRAL,
    CUSTOM_FIELD_VALUES:TEMPORARYPAYMENTREDUCTIONTERM::VARCHAR AS TEMPORARY_PAYMENT_REDUCTION_TERM,
    CUSTOM_FIELD_VALUES:USCITIZENSHIP::VARCHAR AS US_CITIZENSHIP,
    CUSTOM_FIELD_VALUES:VALIDATIONOFDEBT::VARCHAR AS VALIDATION_OF_DEBT_STATUS

FROM ARCA.FRESHSNOW.TRANSFORMED_CUSTOM_FIELD_ENTITY_CURRENT cs
INNER JOIN ARCA.FRESHSNOW.LOAN_ENTITY_CURRENT le ON (cs.entity_id = le.settings_id)
WHERE cs.entity_type = 'Entity.LoanSettings'
  AND cs.schema_name = ARCA.CONFIG.loan_management_system_SCHEMA()
  AND le.schema_name = ARCA.CONFIG.loan_management_system_SCHEMA()
GROUP BY ALL;

-- Expected Result: 127,023 total records with all 199 fields showing NULL
