-- DI-1151: QC Validation - Record Count Check
-- Verify record counts match expected population

-- Expected: 1483 selected loans (status = 'Included')
SELECT 'Selected Population' as source, COUNT(*) as record_count 
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE_SELECTED

UNION ALL

-- Check how many have matching loan data
SELECT 'With Loan Match' as source, COUNT(*) as record_count
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE_SELECTED C
INNER JOIN BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE A
    ON C.LOANID = A.ACCOUNT_PUBLIC_ID
INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
    ON LA.LEGACY_LOAN_ID = A.EXTERNAL_ACCOUNT_ID

UNION ALL

-- Check how many have PII data
SELECT 'With PII Match' as source, COUNT(*) as record_count
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE_SELECTED C
INNER JOIN BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q2_2025_SALE A
    ON C.LOANID = A.ACCOUNT_PUBLIC_ID
INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
    ON LA.LEGACY_LOAN_ID = A.EXTERNAL_ACCOUNT_ID
INNER JOIN BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII ci
    ON ci.MEMBER_ID::VARCHAR = la.MEMBER_ID::VARCHAR 
    AND ci.MEMBER_PII_END_DATE IS NULL;