/*
================================================================================
DI-1254 QC: Duplicate Loan Check
================================================================================
*/

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
USE ROLE BUSINESS_INTELLIGENCE;

--1.1: Duplicate LOANID Check - Should Return 0 Rows
SELECT
    COUNT(*) AS ROW_COUNT,
    LOANID
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
GROUP BY LOANID
HAVING COUNT(*) > 1
ORDER BY ROW_COUNT DESC;

--1.2: Duplicate LEAD_GUID Check - Should Return 0 Rows
SELECT
    COUNT(*) AS ROW_COUNT,
    LEAD_GUID
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
GROUP BY LEAD_GUID
HAVING COUNT(*) > 1
ORDER BY ROW_COUNT DESC;

--1.3: Duplicate LP_LOAN_ID Check - Should Return 0 Rows
SELECT
    COUNT(*) AS ROW_COUNT,
    LP_LOAN_ID
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
GROUP BY LP_LOAN_ID
HAVING COUNT(*) > 1
ORDER BY ROW_COUNT DESC;
