/*
================================================================================
DI-1254 QC: Record Count Summary
================================================================================
*/

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
USE ROLE BUSINESS_INTELLIGENCE;

--2.1: Population File Record Counts
SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(DISTINCT LOANID) AS DISTINCT_LOANID,
    COUNT(DISTINCT LEAD_GUID) AS DISTINCT_LEAD_GUID,
    COUNT(DISTINCT LP_LOAN_ID) AS DISTINCT_LP_LOAN_ID
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025;

--2.2: Transaction File Record Counts
SELECT
    COUNT(*) AS TOTAL_TRANSACTIONS,
    COUNT(DISTINCT LOANID) AS DISTINCT_LOANS_IN_TRANSACTIONS,
    COUNT(DISTINCT TRANSACTION_ID) AS DISTINCT_TRANSACTION_IDS
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025_TRANSACTIONS;

--2.3: Transaction Count Per Loan Summary
SELECT
    'Transaction Count Distribution' AS METRIC,
    MIN(TRANSACTION_COUNT) AS MIN_TRANSACTIONS,
    AVG(TRANSACTION_COUNT) AS AVG_TRANSACTIONS,
    MAX(TRANSACTION_COUNT) AS MAX_TRANSACTIONS,
    MEDIAN(TRANSACTION_COUNT) AS MEDIAN_TRANSACTIONS
FROM (
    SELECT
        LOANID,
        COUNT(*) AS TRANSACTION_COUNT
    FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025_TRANSACTIONS
    GROUP BY LOANID
);
