/*
================================================================================
DI-1254 QC: Exclusion Criteria Verification
================================================================================
Validates that excluded populations are not in the final dataset
*/

USE WAREHOUSE BUSINESS_INTELLIGENCE_LARGE;
USE ROLE BUSINESS_INTELLIGENCE;

--4.1: Fraud Exclusion Verification - Should Return 0
SELECT
    COUNT(*) AS FRAUD_LOANS_IN_POPULATION
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE FRAUD_INDICATOR = TRUE;

--4.2: Deceased Exclusion Verification - Should Return 0
SELECT
    COUNT(*) AS DECEASED_LOANS_IN_POPULATION
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE DECEASED_INDICATOR = TRUE;

--4.3: Placement Status Verification - Should Return 0
SELECT
    LOAN_CURRENT_PLACEMENT,
    COUNT(*) AS LOAN_COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE LOAN_CURRENT_PLACEMENT IN ('Resurgent', 'Bounce', 'Jefferson Capital', 'First Tech Credit Union', 'ARS', 'Remitter')
GROUP BY LOAN_CURRENT_PLACEMENT;

--4.4: Closed Loan Verification - Should Return 0
SELECT
    COUNT(*) AS CLOSED_LOANS_IN_POPULATION
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE LOAN_CLOSED_DATE IS NOT NULL;

--4.5: All Exclusions Summary
SELECT
    'Total Population' AS EXCLUSION_TYPE,
    COUNT(*) AS COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025

UNION ALL

SELECT
    'Fraud (Should be 0)' AS EXCLUSION_TYPE,
    COUNT(*) AS COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE FRAUD_INDICATOR = TRUE

UNION ALL

SELECT
    'Deceased (Should be 0)' AS EXCLUSION_TYPE,
    COUNT(*) AS COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE DECEASED_INDICATOR = TRUE

UNION ALL

SELECT
    'Existing Placements (Should be 0)' AS EXCLUSION_TYPE,
    COUNT(*) AS COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE LOAN_CURRENT_PLACEMENT IN ('Resurgent', 'Bounce', 'Jefferson Capital', 'First Tech Credit Union', 'ARS', 'Remitter')

UNION ALL

SELECT
    'Closed Loans (Should be 0)' AS EXCLUSION_TYPE,
    COUNT(*) AS COUNT
FROM BUSINESS_INTELLIGENCE_DEV.CRON_STORE.RESURGENT_BK_SALE_EVAL_2025
WHERE LOAN_CLOSED_DATE IS NOT NULL;
