SET START_DATE = '2025-06-18';

--Bulk_Upload_Placement_File_Bounce_H2_2024_SALE
Select LOAN_ID as LP_LOAN_ID,
        UPPER(LEGACY_LOAN_ID) as loanid,
        B.SETTINGS_ID,
       'Bounce' as Placement_Status,
       $START_DATE as Placement_Status_StartDate,
       NULL as Placement_Status_EndDate
from BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_H2_2024_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN A
ON A.LEGACY_LOAN_ID = C.LOANID
LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_ENTITY_CURRENT B
ON A.LOAN_ID::STRING = B.ID::STRING AND B.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA();

--Credit_Reporting_File_Bounce_H2_2024_SALE
Select UPPER(la.LEGACY_LOAN_ID) as loan_id,
       UPPER(ci.FIRST_NAME) as first_name,
       UPPER(ci.LAST_NAME) as last_name,
       $START_DATE as PLACEMENT_STATUS_STARTDATE
       --la.PLACEMENT_STATUS_STARTDATE
from BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_H2_2024_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
ON LA.LEGACY_LOAN_ID = C.LOANID
left join BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII ci
on ci.MEMBER_ID::VARCHAR = la.MEMBER_ID::VARCHAR and ci.MEMBER_PII_END_DATE is null;

--Bulk_Upload_Placement_File_Bounce_Q1_2025_FF_SALE
Select LOAN_ID as LP_LOAN_ID,
        UPPER(LEGACY_LOAN_ID) as loanid,
        B.SETTINGS_ID,
       'Bounce' as Placement_Status,
       $START_DATE as Placement_Status_StartDate,
       NULL as Placement_Status_EndDate
from BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q1_2025_FF_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN A
ON A.LEGACY_LOAN_ID = C.LOANID
LEFT JOIN BUSINESS_INTELLIGENCE.BRIDGE.VW_LOAN_ENTITY_CURRENT B
ON A.LOAN_ID::STRING = B.ID::STRING AND B.SCHEMA_NAME = ARCA.CONFIG.LMS_SCHEMA();

--Credit_Reporting_File_Bounce_Q1_2025_FF_SALE
Select UPPER(la.LEGACY_LOAN_ID) as loan_id,
       UPPER(ci.FIRST_NAME) as first_name,
       UPPER(ci.LAST_NAME) as last_name,
       $START_DATE as PLACEMENT_STATUS_STARTDATE
       --la.PLACEMENT_STATUS_STARTDATE
from BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q1_2025_FF_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
ON LA.LEGACY_LOAN_ID = C.LOANID
left join BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII ci
on ci.MEMBER_ID::VARCHAR = la.MEMBER_ID::VARCHAR and ci.MEMBER_PII_END_DATE is null;
