----- updated script to fill in null with 0's for Chargeoff Balance field

   SET SALE_DATE = '2025-06-11';

--Notice_of_Servicing_Transfer_Placement_File_Bounce_Q1_2025_FF_SALE
Select UPPER(la.LEGACY_LOAN_ID) as loan_id,
       lower(la.LEAD_GUID) as payoffuid,
       UPPER(ci.FIRST_NAME)      as first_name,
       UPPER(ci.LAST_NAME)       as last_name,
       ci.email,
       ci.ADDRESS_1 as streetaddress1,
       ci.ADDRESS_2 as streetaddress2,
       ci.city,
       ci.state,
       ci.ZIP_CODE as zipcode,
       cust.CUSTOMER_ID as SFMC_SUBSCRIBER_ID,
       A.CHARGEOFFDATE AS CHARGE_OFF_DATE,
       A.UNPAIDBALANCEDUE AS CURRENT_BALANCE,
       zeroifnull(A.PRINCIPALBALANCEATCHARGEOFF)+ zeroifnull(A.INTERESTBALANCEATCHARGEOFF) - zeroifnull(A.CHARGED_OFF_PRINCIPAL_ADJUSTMENT) AS CHARGE_OFF_BALANCE,
       REPLACE(A.PORTFOLIONAME,'Payoff FBO ','') AS CU_NAME,
       $SALE_DATE AS SALE_DATE,
       A.PRINCIPALBALANCEATCHARGEOFF,
       A.INTERESTBALANCEATCHARGEOFF,
       A.CHARGED_OFF_PRINCIPAL_ADJUSTMENT,
       A.RECOVERIESPAIDTODATE,
       A.TOTALPRINCIPALWAIVED
from BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q1_2025_FF_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
ON LA.LEGACY_LOAN_ID = C.LOANID
left join BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII ci
on ci.MEMBER_ID::VARCHAR = la.MEMBER_ID::VARCHAR and ci.MEMBER_PII_END_DATE is null
left join business_intelligence.bridge.vw_los_custom_loan_settings_current los
on los.APPLICATION_GUID = la.LEAD_GUID
inner join business_intelligence.bridge.VW_LOAN_CUSTOMER_CURRENT cust
on los.loan_id = cust.loan_id AND cust.SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LOS_SCHEMA()
INNER JOIN BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_Q1_2025_FF_SALE A
ON C.LOANID = A.LOANID;

--Notice_of_Servicing_Transfer_Placement_File_Bounce_H2_2024_SALE
Select UPPER(la.LEGACY_LOAN_ID) as loan_id,
       lower(la.LEAD_GUID) as payoffuid,
       UPPER(ci.FIRST_NAME)      as first_name,
       UPPER(ci.LAST_NAME)       as last_name,
       ci.email,
       ci.ADDRESS_1 as streetaddress1,
       ci.ADDRESS_2 as streetaddress2,
       ci.city,
       ci.state,
       ci.ZIP_CODE as zipcode,
       cust.CUSTOMER_ID as SFMC_SUBSCRIBER_ID,
       A.CHARGEOFFDATE AS CHARGE_OFF_DATE,
       A.UNPAIDBALANCEDUE AS CURRENT_BALANCE,
       zeroifnull(A.PRINCIPALBALANCEATCHARGEOFF)+ zeroifnull(A.INTERESTBALANCEATCHARGEOFF) - zeroifnull(A.CHARGED_OFF_PRINCIPAL_ADJUSTMENT) AS CHARGE_OFF_BALANCE,
       REPLACE(A.PORTFOLIONAME,'Payoff FBO ','') AS CU_NAME,
       $SALE_DATE AS SALE_DATE,
       A.PRINCIPALBALANCEATCHARGEOFF,
       A.INTERESTBALANCEATCHARGEOFF,
       A.CHARGED_OFF_PRINCIPAL_ADJUSTMENT,
       A.RECOVERIESPAIDTODATE,
       A.TOTALPRINCIPALWAIVED
from BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_H2_2024_SALE_SELECTED C
LEFT JOIN BUSINESS_INTELLIGENCE.ANALYTICS.VW_LOAN LA
ON LA.LEGACY_LOAN_ID = C.LOANID
left join BUSINESS_INTELLIGENCE.ANALYTICS_PII.VW_MEMBER_PII ci
on ci.MEMBER_ID::VARCHAR = la.MEMBER_ID::VARCHAR and ci.MEMBER_PII_END_DATE is null
left join business_intelligence.bridge.vw_los_custom_loan_settings_current los
on los.APPLICATION_GUID = la.LEAD_GUID
inner join business_intelligence.bridge.VW_LOAN_CUSTOMER_CURRENT cust
on los.loan_id = cust.loan_id AND cust.SCHEMA_NAME = BUSINESS_INTELLIGENCE.CONFIG.LOS_SCHEMA()
INNER JOIN BUSINESS_INTELLIGENCE_DEV.CRON_STORE.BOUNCE_DEBT_SALE_H2_2024_SALE A
ON C.LOANID = A.LOANID;


